-- Cached AI-generated cover backgrounds (deep river-green topo + Ozark river art).
-- One row per key: a river slug (per-river), plus 'forecast' and 'danger'.
-- Generated by scripts/social/generate-og-backgrounds.mjs (OpenAI gpt-image-1)
-- and read by the OG cover route, which composites the live text on top. The
-- model only makes the background art; text stays dynamic + always correct.
-- Generate-once + cache: OpenAI is hit at generation time, never per render.
create table if not exists og_backgrounds (
  key text primary key,
  url text not null,
  prompt text,
  updated_at timestamptz not null default now()
);

-- Service-role only (the OG route + generator use the service key, which bypasses
-- RLS); no public policies.
alter table og_backgrounds enable row level security;

drop trigger if exists og_backgrounds_updated_at on og_backgrounds;
create trigger og_backgrounds_updated_at
  before update on og_backgrounds
  for each row execute function update_updated_at();
