-- 00171_trim_river_descriptions.sql
-- Trim the newest rivers' hero descriptions down to the concise
-- 2-sentence Jacks Fork style. The long-form detail already lives in
-- river_sections / river_characteristics; the rivers.description field
-- is the identity blurb shown on the River Reports hero.
-- Idempotent: keyed by slug, safe to re-run.

UPDATE rivers SET description = 'A classic Ozark float and the main tributary of the Gasconade, winding north through Mark Twain National Forest past pine-topped limestone bluffs. Spring-fed but flashy, with clear water, Class I-II riffles, and some of Missouri''s best smallmouth fishing.' WHERE slug = 'big-piney';
UPDATE rivers SET description = 'A slow, scenic beginner (Class I) float rising in the St. Francois Mountains and winding north to the Meramec. Long pools, gravel-bar riffles, and historic mill sites, with Washington State Park a popular float base and a few low-head dams to portage.' WHERE slug = 'big-river';
UPDATE rivers SET description = 'A wild, spring-influenced Ozark float running south to meet the North Fork of the White River. Gentle Class I water with clear pools, bluffs, and gravel bars, prized for smallmouth and goggle-eye — narrower and flashier than the neighboring North Fork.' WHERE slug = 'bryant-creek';
UPDATE rivers SET description = 'The longest river entirely within Missouri and one of the world''s crookedest — a winding, low-gradient Ozark float to the Missouri River. Scenic dolostone bluffs, springs, and caves, with easy Class I water and quiet, uncrowded floating.' WHERE slug = 'gasconade';
UPDATE rivers SET description = 'Arkansas''s premier whitewater float, free-flowing out of the Boston Mountains in the Ozark National Forest. Scenic canyon walls and reliable Class I-II rapids that stiffen to III at high water — notoriously flashy and best run fall through spring.' WHERE slug = 'mulberry';
UPDATE rivers SET description = 'A clear, spring-fed Ouachita Mountain stream and one of Arkansas''s most popular family floats, running east past the boulder gorge at Caddo Gap toward DeGray Lake. The classic Caddo Gap-to-Glenwood run mixes fun Class I-II rock gardens with long, calm pools.' WHERE slug = 'caddo-river';
UPDATE rivers SET description = 'A scenic Class I Ozark float in northwest Arkansas, flowing past Withrow Springs State Park and the historic War Eagle Mill to Beaver Lake. Framed by tall limestone bluffs; a rain-dependent, flashy creek best floated during spring runoff.' WHERE slug = 'war-eagle-creek';
UPDATE rivers SET description = 'A clear, gravel-bottomed Ozark stream running across north-central Arkansas to the White River near Cotter. A Blue Ribbon smallmouth fishery with easy Class I floating past long gravel bars and riffles — entirely rain-fed, so it drops skinny in summer.' WHERE slug = 'crooked-creek';
UPDATE rivers SET description = 'The slowest large stream in the Ozarks and one of its crookedest, winding through farm country to the Meramec. Runoff-fed and often murky, with an unhurried pace favored by local anglers over the rental-canoe crowd; the upper half runs thin in dry summers.' WHERE slug = 'bourbeuse';
UPDATE rivers SET description = 'A warm, popular summer float in Missouri''s far southwestern corner around Pineville and Noel. Clear, spring-influenced water over gravel bars and beneath bluffs, with heavy party-float traffic in season — but rain-driven and prone to fast, flashy rises.' WHERE slug = 'elk';
UPDATE rivers SET description = 'A cold, clear, spring-fed float in north-central Arkansas, rising at Mammoth Spring and running past Hardy toward the Black River. Reliable year-round flow, trout in the upper reach and smallmouth below, and a few lively ledges like Saddler Falls.' WHERE slug = 'spring-river';
UPDATE rivers SET description = 'Missouri''s only whitewater river. The upper run through Millstream Gardens and the Tiemann Shut-ins is a rain-dependent, 2.3-mile Class II-IV pool-drop; below the shut-ins it mellows into an easy float toward Sam A. Baker State Park.' WHERE slug = 'st-francis';
UPDATE rivers SET description = 'A clear, popular southeast-Missouri Ozark float below the St. Francois Mountains. The Lesterville reach above Clearwater Lake is a summer-float hotspot of gravel bars and bluffs, fed by the East, Middle, and West Fork headwaters that converge nearby.' WHERE slug = 'black';

