-- 20260804210000_float_summary_follows_ladder.sql
--
-- Make rivers.float_summary agree with the float ladder it describes.
--
-- ── The defect ──────────────────────────────────────────────────────────────
--
-- float_summary is hand-authored prose about river_gauges thresholds, stored
-- apart from them, and nothing ever made the two agree. 00177 recalibrated the
-- cfs danger lines and named the exact problem in its own header:
--
--     Flood-flow-anchored danger lines that UNDER-warn: North Fork (8,440 cfs
--     on a river locals call high at ~1,000), James (4,410 vs observed flood
--     onset 3,000), Black @ Poplar Bluff (7,057).
--
-- It fixed river_gauges and left the prose alone. So the North Fork page has
-- been rating readings against a 2,200 cfs danger line while the paragraph
-- underneath said danger began near 8,440 — four times the real number, on the
-- reassuring side. The ladder computes the badge, so prose that disagrees can
-- never change the rating, only talk a reader out of believing it.
--
-- Five active rivers drift, in three distinct ways:
--
--   north-fork-white  stale pre-00177 figures (optimal 282-811, danger 8,440)
--   james             stale pre-00177 figures (high 3,079, danger 4,410)
--   mulberry          "8 ft and up is experts-only" above a 4.5 ft danger line
--   jacks-fork        prose entirely in FEET against a gauge Eddy reads in CFS
--   big-river         credits Byrnesville as primary; the primary is Richwoods,
--                     a different drainage area, so its numbers describe water
--                     the rating is not computed from
--
-- bryant-creek is corrected here too. It does not under-warn (its numbers sit
-- inside the ladder) but they match no threshold in it, so it is the same
-- authored-independently defect and is cheaper to fix now than to rediscover.
--
-- ── Provenance ──────────────────────────────────────────────────────────────
--
-- The stale prose was generated by scripts/ingestion/set-cold-start.ts and
-- set-cold-start-batch3.ts, whose headers still recorded the pre-00177 ladders
-- they were written from. Both scripts are idempotent and re-runnable, so this
-- migration alone would have been reverted by the next run. They are corrected
-- in the same commit.
--
-- ── Recurrence ──────────────────────────────────────────────────────────────
--
-- src/lib/trust/checks/float-summary.ts now fails on all three shapes above, so
-- the next recalibration that leaves prose behind raises a finding instead of
-- sitting in production for months. Verified against live data before this
-- migration: it flagged these five and none of the seven other rivers that
-- carry prose.
--
-- Every value below is read off river_gauges for that river's PRIMARY gauge.
-- Prior text is quoted above each statement so this is reversible by hand.

-- north-fork-white @ Tecumseh (07057500, cfs): 285 / 475 / 628-1000 / 1000 / 2200
-- WAS: "...282–811 cfs is the ideal float range. Above ~1,000 cfs the North Fork
--       runs high and cold; it becomes dangerous near 8,440 cfs. ..."
UPDATE rivers SET float_summary =
  'At the Tecumseh gauge (primary), 628–1,000 cfs is the ideal float range. Around 475 cfs it''s low, and below ~285 cfs you''ll drag. Above 1,000 cfs the North Fork runs high and cold, and 2,200 cfs and up is dangerous. Spring-fed baseflow from Rainbow and Blue Springs keeps it floatable most of the year, but it can jump quickly after heavy rain.'
WHERE slug = 'north-fork-white';

-- james @ Galena (07052500, cfs): 97 / 180 / 358-921 / 921 / 3000
-- WAS: "...180–937 cfs is the ideal range... Above ~3,079 cfs the James runs
--       high and fast; 4,410 cfs and up is dangerous—choose another day. ..."
UPDATE rivers SET float_summary =
  'At the Galena gauge (primary), 358–921 cfs is the ideal range for the classic Hootentown-to-Galena float. Below ~180 cfs it''s low, and below ~97 cfs you''ll drag. Above 921 cfs the James runs high and fast, and 3,000 cfs and up is dangerous—choose another day. On the upper river near Springfield (Boaz gauge), you''ll want at least ~150 cfs to avoid dragging.'
WHERE slug = 'james';

-- mulberry @ Mulberry (07252000, ft): 1.20 / 1.50 / 2.00-3.50 / 4.00 / 4.50
-- WAS: "...above ~4 ft it's pushy, and 8 ft and up is experts-only. ..."
--   8 ft is true of the real river and irrelevant to the badge: it implied the
--   3.5 ft between the danger line and 8 ft was merely "pushy".
UPDATE rivers SET float_summary =
  'At the Mulberry gauge (primary), about 2.0–3.5 ft is prime for Arkansas''s best-known float—lively Class I–II water; below ~1.2 ft you''ll drag. It stiffens fast as it rises: above ~4.0 ft it''s pushy, and by 4.5 ft it is dangerous whitewater rather than a float. The Mulberry is undammed and very flashy, usually floatable late October through mid-June.'
WHERE slug = 'mulberry';

-- jacks-fork @ Alley Spring (07065495, CFS): 76 / 100 / 159-637 / 637 / 1000
-- WAS: "...At Alley Spring (primary), 2.5–3.0 ft is ideal. Above 3.5 ft we
--       recommend another day—river closes at 4.0 ft. Below 2.0 ft you'll drag
--       with gear. At Eminence (lower), 2.0–3.0 ft is good; average is ~1.5 ft..."
--   Every number in that sentence was gauge height. Eddy reads this gauge in
--   cfs, so the reading on the page and the numbers under it shared no scale.
UPDATE rivers SET float_summary =
  'At the Alley Spring gauge (primary), 159–637 cfs is the ideal range on the Jacks Fork. Around 100 cfs it''s low and you''ll drag with gear, and below ~76 cfs it isn''t really floating. Above 637 cfs it runs high, and 1,000 cfs and up is dangerous—choose another day. These are cfs, not the gauge-height feet quoted on outfitter and Park Service boards, so don''t compare the two. The Jacks Fork is shallower and more rain-dependent than the Current.'
WHERE slug = 'jacks-fork';

-- big-river @ Richwoods (07018100, cfs): 60 / 90 / 100-400 / 600 / 800
-- WAS: "At the Byrnesville gauge (primary), roughly 200–600 cfs is comfortable
--       floating; below ~90 cfs you'll scrape... The popular Washington State
--       Park reach upstream runs a bit lower. ..."
--   Byrnesville (917 sq mi) is NOT the primary; Richwoods (735 sq mi) is, and
--   Richwoods is also the gauge that covers the Washington State Park float.
--   Byrnesville's numbers against a Richwoods reading run permissive at the top:
--   500 cfs at Richwoods earns a High badge under prose calling it comfortable.
UPDATE rivers SET float_summary =
  'At the Richwoods gauge (primary), roughly 100–400 cfs is comfortable floating; below ~90 cfs you''ll scrape, and below ~60 cfs the riffles between the long pools stop floating altogether. Above ~600 cfs it runs high and pushy for a beginner river, and 800 cfs and up is dangerous. Richwoods covers the popular Washington State Park reach; the Byrnesville gauge sits well downstream on a larger drainage and reads higher. Big River is a slow, scenic Ozark float.'
WHERE slug = 'big-river';

-- bryant-creek @ Tecumseh (07058000, cfs): 189 / 300 / 356-1050 / 1050 / 1930
-- WAS: "...about 300–600 cfs is comfortable... around 245 cfs it's low but
--       floatable (expect dragging), and below ~200 cfs most riffles drag. ..."
--   245 and 200 and 600 correspond to no line in the ladder.
UPDATE rivers SET float_summary =
  'At the Tecumseh gauge (primary), about 356–1,050 cfs is comfortable floating on Bryant Creek; around 300 cfs it''s low but floatable (expect dragging), and below ~189 cfs most riffles drag. Above 1,050 cfs it runs high, and 1,930 cfs and up is dangerous. The gauge sits at the mouth of the creek, so the water upstream at Vera Cruz or Bell Bridge runs thinner than the reading suggests. This spring-influenced Ozark creek runs lower and flashier than the neighboring North Fork, into which it empties.'
WHERE slug = 'bryant-creek';

-- ── Assertions ──────────────────────────────────────────────────────────────
DO $$
DECLARE
  stale_count int;
  updated_count int;
BEGIN
  -- No active river may still quote a figure 00177 retired, or the ft-based
  -- Jacks Fork copy. These strings are the fingerprints of the pre-fix prose.
  SELECT count(*) INTO stale_count
  FROM rivers
  WHERE active
    AND float_summary IS NOT NULL
    AND (float_summary LIKE '%8,440%'
      OR float_summary LIKE '%4,410%'
      OR float_summary LIKE '%3,079%'
      OR float_summary LIKE '%8 ft and up%'
      OR float_summary LIKE '%Byrnesville gauge (primary)%'
      OR float_summary LIKE '%2.5–3.0 ft is ideal%');
  IF stale_count <> 0 THEN
    RAISE EXCEPTION 'float_summary still carries retired thresholds on % river(s)', stale_count;
  END IF;

  -- All six rewritten rows must exist and name their real primary gauge.
  SELECT count(*) INTO updated_count
  FROM rivers
  WHERE slug IN ('north-fork-white','james','mulberry','jacks-fork','big-river','bryant-creek')
    AND float_summary IS NOT NULL;
  IF updated_count <> 6 THEN
    RAISE EXCEPTION 'expected 6 rewritten float summaries, found %', updated_count;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM rivers WHERE slug = 'big-river' AND float_summary LIKE '%Richwoods gauge (primary)%'
  ) THEN
    RAISE EXCEPTION 'big-river summary does not credit Richwoods as primary';
  END IF;
END $$;
