// src/lib/eddy/generate-global-update.ts
// Generates a global "overall Ozarks" Eddy quote by summarizing per-river updates.
// Called by the cron job after per-river updates are generated.

import Anthropic from '@anthropic-ai/sdk';
import { createAdminClient } from '@/lib/supabase/admin';
import { getActiveRiverContexts, DEFAULT_TIMEZONE } from '@/lib/rivers/context';
import { getLocalDateStrings } from '@/lib/social/local-time';

export interface GlobalUpdate {
  quoteText: string;
  sourcesUsed: string[];
}

const GLOBAL_SYSTEM_PROMPT = `You are Eddy, an AI otter mascot for a float trip planning app. You are writing a brief overall summary of conditions across all covered rivers.

VOICE: Friendly, knowledgeable, concise. Like a local outfitter giving a quick morning briefing.

RULES:
- Write 2-3 sentences maximum. This is a quick overview, not a detailed report.
- Mention how many rivers are in good shape and call out any that are problematic.
- If most rivers are optimal, be encouraging. If most are low or high, set expectations.
- If there are active weather alerts or dangerous conditions, lead with safety.
- Reference water trend patterns when useful (e.g. "Most rivers are holding steady this week, though smaller creeks are dropping after Monday's rain"). Do not classify rivers as "spring-fed" or "rain-fed" in the output.
- Cite specific river names when highlighting standouts (best or worst conditions).
- Do NOT use em dashes. Use commas, periods, or "and" instead.
- Do NOT use emojis, hashtags, or exclamation marks.
- Do NOT include a greeting or sign-off.
- Do NOT say "I" or refer to yourself.
- Output ONLY the quote text. No labels, no formatting, no quotes around it.`;

/**
 * Generates an overall Ozarks summary by reading recently generated per-river updates
 * and asking Sonnet to synthesize them into a brief overview.
 */
export async function generateGlobalUpdate(): Promise<GlobalUpdate | null> {
  const anthropicKey = process.env.ANTHROPIC_API_KEY;
  if (!anthropicKey) {
    console.error('[EddyGlobal] ANTHROPIC_API_KEY not configured');
    return null;
  }

  const supabase = createAdminClient();

  // Fetch per-river whole-river updates generated in the last 30 minutes
  // (they were just generated by the same cron run)
  const cutoff = new Date(Date.now() - 30 * 60 * 1000).toISOString();

  const { data: recentUpdates, error } = await supabase
    .from('eddy_updates')
    .select('river_slug, condition_code, gauge_height_ft, quote_text')
    .is('section_slug', null)
    .neq('river_slug', 'global')
    .gte('generated_at', cutoff)
    .order('river_slug');

  if (error) {
    console.error('[EddyGlobal] Failed to fetch recent updates:', error);
    return null;
  }

  if (!recentUpdates || recentUpdates.length === 0) {
    console.warn('[EddyGlobal] No recent per-river updates found to summarize');
    return null;
  }

  // Build the prompt with per-river summaries. Region label and timezone
  // come from the active rivers rather than assuming the Missouri Ozarks.
  const contexts = await getActiveRiverContexts().catch(() => []);
  const regions = Array.from(new Set(contexts.map((c) => c.region ?? '').filter(Boolean)));
  const regionLabel = regions.length > 0 ? regions.join(' and ') : 'Ozarks';
  const timezone = contexts[0]?.timezone ?? DEFAULT_TIMEZONE;

  const lines: string[] = [];

  const { dayOfWeek, dateStr } = getLocalDateStrings(timezone);
  lines.push(`Date: ${dayOfWeek}, ${dateStr}`);
  lines.push('');
  lines.push(`Generate a brief overall ${regionLabel} river conditions summary based on these per-river updates:`);
  lines.push('');

  for (const update of recentUpdates) {
    const gauge = update.gauge_height_ft !== null ? `${Number(update.gauge_height_ft).toFixed(1)} ft` : 'N/A';
    lines.push(`${update.river_slug}: ${update.condition_code} (${gauge})`);
    lines.push(`  "${update.quote_text.slice(0, 200)}"`);
    lines.push('');
  }

  const prompt = lines.join('\n');

  const client = new Anthropic({ apiKey: anthropicKey });

  try {
    const message = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 200,
      messages: [{ role: 'user', content: prompt }],
      system: GLOBAL_SYSTEM_PROMPT,
    });

    const textBlock = message.content.find((block) => block.type === 'text');
    const quoteText = textBlock?.text?.trim().replace(/\u2014/g, ',') || null;

    if (!quoteText) {
      console.error('[EddyGlobal] Empty response from model');
      return null;
    }

    return {
      quoteText,
      sourcesUsed: ['per-river updates', 'USGS gauge'],
    };
  } catch (e) {
    console.error('[EddyGlobal] Haiku call failed:', e);
    return null;
  }
}
