// Focused public API for the rivers domain.
export {
  fetchEddyUpdates,
  fetchRivers,
  fetchRiverDetail,
  fetchRiverAccessPoints,
  fetchAccessPointDetail,
  fetchStatewideNetwork,
  seedOfflineBundle,
  onOfflineBundleSeeded,
  fetchStatewideReadings,
  fetchRiverReaches,
  fetchServices,
  fetchRiverServices,
  fetchFloatPlan,
  fetchSavedPlan,
  saveFloatPlan,
  searchEddy,
  SEARCH_PAGE_SIZE,
  fetchCondition,
  fetchRiverOutlook,
  fetchRiverVisuals,
  fetchHazards,
} from '../implementation';
