// src/app/plan/[shortCode]/layout.tsx
// Layout for shared plan pages
// Exports generateMetadata for dynamic social media preview tags
// OG images are auto-generated by opengraph-image.tsx in this directory

import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { createClient } from '@/lib/supabase/server';

async function getBaseUrl(): Promise<string> {
  try {
    const headersList = await headers();
    const host = headersList.get('host');
    if (host) {
      const proto = headersList.get('x-forwarded-proto') || 'https';
      return `${proto}://${host}`;
    }
  } catch {
    // headers() not available outside request context
  }
  return process.env.NEXT_PUBLIC_BASE_URL
    || process.env.NEXT_PUBLIC_SITE_URL
    || 'https://eddy.guide';
}

interface PlanLayoutProps {
  children: React.ReactNode;
  params: Promise<{ shortCode: string }>;
}

function formatMinutes(totalMinutes: number): string {
  const hours = Math.floor(totalMinutes / 60);
  const mins = Math.round(totalMinutes % 60);
  if (hours === 0) return `${mins}min`;
  if (mins === 0) return `${hours}h`;
  return `${hours}h ${mins}m`;
}

export async function generateMetadata({ params }: PlanLayoutProps): Promise<Metadata> {
  try {
    const BASE_URL = await getBaseUrl();
    const resolvedParams = await params;
    const shortCode = resolvedParams?.shortCode;

    if (!shortCode) {
      return {
        title: 'Float Plan',
        description: 'View and share your Missouri float trip plan.',
      };
    }

    const supabase = await createClient();

    // Fetch the saved plan
    const { data: savedPlan, error: planError } = await supabase
      .from('float_plans')
      .select('*')
      .eq('short_code', shortCode)
      .single();

    if (planError || !savedPlan) {
      return {
        title: 'Plan Not Found',
        description: 'This float plan could not be found.',
      };
    }

    // Fetch river and access points in parallel
    const [riverResult, putInResult, takeOutResult] = await Promise.all([
      supabase.from('rivers').select('name, slug, region').eq('id', savedPlan.river_id).single(),
      supabase.from('access_points').select('name').eq('id', savedPlan.start_access_id).single(),
      supabase.from('access_points').select('name').eq('id', savedPlan.end_access_id).single(),
    ]);

    const riverName = riverResult.data?.name || 'Missouri River';
    const putInName = putInResult.data?.name || 'Start';
    const takeOutName = takeOutResult.data?.name || 'End';

    const distanceMiles = savedPlan.distance_miles
      ? parseFloat(savedPlan.distance_miles).toFixed(1)
      : '';
    const floatTimeFormatted = savedPlan.estimated_float_minutes
      ? formatMinutes(savedPlan.estimated_float_minutes)
      : '';
    const conditionCode = savedPlan.condition_at_creation || 'unknown';

    const conditionLabels: Record<string, string> = {
      optimal: 'Optimal',
      okay: 'Low - Floatable',
      low: 'Very Low',
      high: 'High Water',
      too_low: 'Too Low',
      dangerous: 'Dangerous',
      unknown: '',
    };

    const conditionText = conditionLabels[conditionCode] || '';

    const title = `${riverName} - ${putInName} to ${takeOutName}`;
    const descParts: string[] = [];
    if (distanceMiles) descParts.push(`${distanceMiles} mi`);
    if (floatTimeFormatted) descParts.push(`~${floatTimeFormatted} float`);
    if (conditionText) descParts.push(`Conditions: ${conditionText}`);

    const description = descParts.length > 0
      ? `${riverName} float plan - ${descParts.join(' | ')} | Check conditions on Eddy.`
      : `${riverName} float plan from ${putInName} to ${takeOutName}. Check conditions on Eddy.`;

    const pageUrl = `${BASE_URL}/plan/${shortCode}`;

    return {
      title,
      description,
      openGraph: {
        type: 'website',
        title: `${riverName} - ${putInName} to ${takeOutName}`,
        description,
        url: pageUrl,
        siteName: 'Eddy',
        // OG image is auto-discovered from opengraph-image.tsx
      },
      twitter: {
        card: 'summary_large_image',
        title: `${riverName}: ${putInName} to ${takeOutName}`,
        description,
        // Twitter image is auto-discovered from twitter-image.tsx
      },
    };
  } catch (error) {
    console.error('Error generating plan metadata:', error);
    return {
      title: 'Float Plan',
      description: 'View and share your Missouri float trip plan.',
      openGraph: {
        type: 'website',
        title: 'Float Plan | Eddy',
        description: 'View and share your Missouri float trip plan.',
        siteName: 'Eddy',
      },
      twitter: {
        card: 'summary_large_image',
        title: 'Float Plan | Eddy',
        description: 'View and share your Missouri float trip plan.',
      },
    };
  }
}

export default function PlanLayout({ children }: PlanLayoutProps) {
  return children;
}
