-- Stores AI-generated per-gauge condition updates.
-- Populated by /api/cron/generate-gauge-updates (Haiku 4.5) once daily,
-- targeting secondary gauges on active rivers. Primary-gauge / river-level
-- prose still lives in eddy_updates and is generated by Sonnet.

CREATE TABLE IF NOT EXISTS gauge_updates (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  gauge_station_id  UUID NOT NULL REFERENCES gauge_stations(id) ON DELETE CASCADE,
  usgs_site_id      TEXT NOT NULL,
  river_slug        TEXT,
  condition_code    TEXT NOT NULL,
  gauge_height_ft   NUMERIC,
  discharge_cfs     NUMERIC,
  quote_text        TEXT NOT NULL,
  summary_text      TEXT,
  sources_used      JSONB DEFAULT '[]',
  model_used        TEXT,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at        TIMESTAMPTZ NOT NULL
);

-- Fast lookup: latest update per gauge (used by /api/gauge-update/[siteId])
CREATE INDEX idx_gauge_updates_site_id_generated
  ON gauge_updates (usgs_site_id, generated_at DESC);

CREATE INDEX idx_gauge_updates_station_id_generated
  ON gauge_updates (gauge_station_id, generated_at DESC);

-- Cleanup: find expired updates
CREATE INDEX idx_gauge_updates_expires
  ON gauge_updates (expires_at);

-- RLS: public read, service-role write (mirrors eddy_updates)
ALTER TABLE gauge_updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read gauge updates"
  ON gauge_updates FOR SELECT
  USING (true);

CREATE POLICY "Service role can manage gauge updates"
  ON gauge_updates FOR ALL
  USING (auth.role() = 'service_role');
