#!/usr/bin/env npx tsx
/**
 * Import real NHD HR river geometry from USGS National Map S3 into rivers.geom.
 *
 * The original `scripts/import-nhd-rivers.ts` queries USGS NHDPlus_HR ArcGIS
 * REST and silently falls back to hand-typed seed coordinates when the WFS
 * call fails. That's why `rivers.geom` was historically a near-straight
 * polyline of ~30 vertices for every floatable river. This script replaces
 * that pipeline with HUC8 shapefile downloads from USGS TNM S3, which is
 * publicly reachable and ships authoritative NHDFlowline data.
 *
 * Pipeline (per river):
 *  1. Download `NHD_H_<HUC8>_HU8_Shape.zip` from prd-tnm.s3.amazonaws.com
 *     (cached in `tmp/nhd/`).
 *  2. Parse `NHDFlowline.shp` with shpjs.
 *  3. Filter to features with the river's `gnis_name` and FCode in
 *     {46006 perennial, 55800 connector, 46000 stream/river-unspecified}.
 *     (46000 is required for rivers like War Eagle Creek whose middle reach is
 *     tagged 46000 — excluding it splits the main stem and drops the lower half.)
 *  4. Build connected components by endpoint adjacency, walk each into a
 *     single LineString, return the LONGEST component (= the main channel).
 *  5. Simplify with Douglas-Peucker tolerance 0.0005 deg (~50m at MO lat).
 *  6. UPDATE rivers SET geom = ST_GeomFromText(...).
 *
 * Run:  npx tsx scripts/import-nhd-rivers-from-tnm.ts                 # all rivers
 *       npx tsx scripts/import-nhd-rivers-from-tnm.ts bourbeuse black # only these slugs
 *       npx tsx scripts/import-nhd-rivers-from-tnm.ts --out tmp/update.sql
 *       npx tsx scripts/import-nhd-rivers-from-tnm.ts bourbeuse --apply  # write to DB
 *
 * The script emits SQL to stdout (or to a file with --out), or writes rows
 * directly with --apply (needs NEXT_PUBLIC_SUPABASE_URL/SUPABASE_URL +
 * SUPABASE_SERVICE_ROLE_KEY/SUPABASE_KEY). Rivers already in prod get their
 * geometry refreshed (mode 'update'); rivers marked mode:'insert' are
 * created if absent, with metadata pulled from scripts/config/nhd-rivers.json
 * and active=false — activation stays a human call after
 * validate_river_data() (see ingestion/DEPLOYMENT-STATUS.md).
 * Emitted SQL can be applied via Supabase SQL editor or:
 *   psql "$DATABASE_URL" -f tmp/update.sql
 *
 * The committed migration `00116_import_real_nhd_river_geometry.sql`
 * already contains the geometry generated by this script for the original
 * seven rivers, so a fresh DB recreated via `npm run db:migrate` will get
 * the same data without needing to re-download HUC8 zips.
 *
 * Requires `tsx` + `shpjs` + `@turf/turf` (already in devDependencies).
 */

// shpjs's CJS bundle references browser-only `self`. Polyfill before the
// dynamic import below.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(globalThis as any).self = globalThis;

import { createWriteStream, existsSync, readFileSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { pipeline } from 'stream/promises';
import { createClient } from '@supabase/supabase-js';
import { simplify, lineString as turfLine, length as turfLength } from '@turf/turf';
import type { Feature, LineString } from 'geojson';

// Per-river spec: which GNIS names to match (NHD sometimes carries name
// variants — list them all) and which HUC8 basins the main stem crosses
// (a river spanning two HUC8s, like the Gasconade, needs both zips merged
// before dissolving). Verify a river's HUC8 by querying USGS WBD or by
// trial: shpjs the HU8 zip and group features by gnis_name.
// mode:'update' = row exists in prod, refresh geometry only.
// mode:'insert' = create the rivers row if absent (metadata from
// scripts/config/nhd-rivers.json, active=false).
interface RiverSpec {
  slug: string;
  gnisNames: string[];
  hucs: string[];
  mode: 'update' | 'insert';
}

const RIVERS: RiverSpec[] = [
  // Original seven (geometry source for migration 00116)
  { slug: 'current',      gnisNames: ['Current River'],      hucs: ['11010008'], mode: 'update' },
  { slug: 'jacks-fork',   gnisNames: ['Jacks Fork'],         hucs: ['11010008'], mode: 'update' },
  { slug: 'eleven-point', gnisNames: ['Eleven Point River'], hucs: ['11010011'], mode: 'update' },
  { slug: 'meramec',      gnisNames: ['Meramec River'],      hucs: ['07140102'], mode: 'update' },
  { slug: 'huzzah',       gnisNames: ['Huzzah Creek'],       hucs: ['07140102'], mode: 'update' },
  { slug: 'courtois',     gnisNames: ['Courtois Creek'],     hucs: ['07140102'], mode: 'update' },
  { slug: 'niangua',      gnisNames: ['Niangua River'],      hucs: ['10290110'], mode: 'update' },
  { slug: 'big-piney',    gnisNames: ['Big Piney River'],    hucs: ['10290202'], mode: 'update' },
  // 2026-07 onboarding batch (see scripts/ingestion/DEPLOYMENT-STATUS.md)
  { slug: 'bourbeuse',  gnisNames: ['Bourbeuse River'],  hucs: ['07140103'], mode: 'insert' },
  { slug: 'gasconade',  gnisNames: ['Gasconade River'],  hucs: ['10290201', '10290203'], mode: 'insert' },
  { slug: 'black',      gnisNames: ['Black River'],      hucs: ['11010007'], mode: 'insert' },
  { slug: 'st-francis', gnisNames: ['St. Francis River', 'Saint Francis River'], hucs: ['08020202'], mode: 'insert' },
  { slug: 'buffalo',    gnisNames: ['Buffalo River'],    hucs: ['11010005'], mode: 'insert' },
  // 2026-07 second onboarding batch (dossiers AWAITING SIGNOFF; see DEPLOYMENT-STATUS.md)
  { slug: 'north-fork-white', gnisNames: ['North Fork River', 'North Fork White River'], hucs: ['11010006'], mode: 'insert' },
  { slug: 'elk',              gnisNames: ['Elk River'],    hucs: ['11070208'], mode: 'insert' },
  { slug: 'james',            gnisNames: ['James River'],  hucs: ['11010002'], mode: 'insert' },
  { slug: 'spring-river',     gnisNames: ['Spring River'], hucs: ['11010010'], mode: 'insert' },
  // 2026-07 third onboarding batch (HUC8s pulled from each river's USGS gauge huc_cd)
  { slug: 'mulberry',        gnisNames: ['Mulberry River'],   hucs: ['11110201'], mode: 'insert' },
  { slug: 'kings-river',     gnisNames: ['Kings River'],      hucs: ['11010001'], mode: 'insert' },
  { slug: 'crooked-creek',   gnisNames: ['Crooked Creek'],    hucs: ['11010003'], mode: 'insert' },
  { slug: 'bryant-creek',    gnisNames: ['Bryant Creek'],     hucs: ['11010006'], mode: 'insert' },
  { slug: 'caddo-river',     gnisNames: ['Caddo River'],      hucs: ['08040102'], mode: 'insert' },
  { slug: 'war-eagle-creek', gnisNames: ['War Eagle Creek'],  hucs: ['11010001'], mode: 'update' },
  { slug: 'big-river',       gnisNames: ['Big River'],        hucs: ['07140104'], mode: 'insert' },
];

interface RiverMeta {
  name: string;
  slug: string;
  description: string;
  difficultyRating: string;
  region: string;
  state?: string;
  timezone?: string;
  riverType?: string;
}

function loadRiverMeta(slug: string): RiverMeta {
  const configPath = join(__dirname, 'config', 'nhd-rivers.json');
  const raw = JSON.parse(readFileSync(configPath, 'utf-8'));
  const meta = (raw.rivers as RiverMeta[]).find((r) => r.slug === slug);
  if (!meta) throw new Error(`No entry for slug '${slug}' in scripts/config/nhd-rivers.json`);
  return meta;
}

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

function getSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !key) {
    throw new Error('Set NEXT_PUBLIC_SUPABASE_URL (or SUPABASE_URL) and SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_KEY = service_role key).');
  }
  return createClient(url, key);
}

const FCODE_PERENNIAL = new Set([46006, 55800, 46000]);
const SIMPLIFY_TOLERANCE_DEG = 0.0005; // ~50 m at MO latitude
// After component-by-component chaining, bridge chains whose endpoints
// are within ~1.2 km of each other. NHD HR has small (~50–500 m)
// digitization gaps that split rivers like Eleven Point into 9
// components at exact-coordinate hashing. Without bridging, the longest
// single component gets exported, which for Eleven Point is the AR
// portion — dropping the entire MO main stem.
const CHAIN_BRIDGE_TOLERANCE_DEG = 0.012;
const TNM_BASE = 'https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/HU8/Shape';

function pointKey(c: number[]): string {
  return c[0].toFixed(7) + ',' + c[1].toFixed(7);
}

function distDeg(a: number[], b: number[]): number {
  const dx = a[0] - b[0], dy = a[1] - b[1];
  return Math.sqrt(dx * dx + dy * dy);
}

async function ensureZip(huc: string, cacheDir: string): Promise<string> {
  const path = join(cacheDir, `${huc}.zip`);
  if (existsSync(path)) return path;
  const url = `${TNM_BASE}/NHD_H_${huc}_HU8_Shape.zip`;
  console.log(`  ↓ Downloading HUC ${huc} from ${url}`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  if (!res.body) throw new Error('No body');
  // @ts-expect-error Node 18+ ReadableStream → web stream interop
  await pipeline(res.body, createWriteStream(path));
  return path;
}

interface SegFeature {
  geometry: { type: string; coordinates: number[][] };
  properties: { gnis_name?: string; fcode?: number };
}

/**
 * Build connected components by endpoint hash, walk each into a chain,
 * then greedily bridge chains whose endpoints are within
 * CHAIN_BRIDGE_TOLERANCE_DEG of each other (so NHD HR digitization gaps
 * don't split a river like Eleven Point into 9 disconnected components).
 *
 * Returns [] if input is empty or all degenerate.
 */
function dissolveLongest(segs: SegFeature[]): number[][] {
  const segCoords = segs
    .map((f) => f.geometry?.coordinates)
    .filter((c): c is number[][] => Array.isArray(c) && c.length >= 2)
    .map((c) => c.map((p) => [p[0], p[1]] as [number, number]));
  if (!segCoords.length) return [];

  // Union-find by exact-shared endpoints.
  const epIdx = new Map<string, number[]>();
  for (let i = 0; i < segCoords.length; i++) {
    const sk = pointKey(segCoords[i][0]);
    const ek = pointKey(segCoords[i][segCoords[i].length - 1]);
    (epIdx.get(sk) ?? epIdx.set(sk, []).get(sk)!).push(i);
    (epIdx.get(ek) ?? epIdx.set(ek, []).get(ek)!).push(i);
  }
  const parent = Array.from({ length: segCoords.length }, (_, i) => i);
  const find = (x: number): number => parent[x] === x ? x : (parent[x] = find(parent[x]));
  const union = (a: number, b: number) => { const ra = find(a), rb = find(b); if (ra !== rb) parent[ra] = rb; };
  epIdx.forEach((list) => {
    for (let i = 1; i < list.length; i++) union(list[0], list[i]);
  });
  const comps = new Map<number, number[]>();
  for (let i = 0; i < segCoords.length; i++) {
    const r = find(i);
    if (!comps.has(r)) comps.set(r, []);
    comps.get(r)!.push(i);
  }

  // Walk each component into a chain.
  type Chain = { coords: number[][]; lengthKm: number };
  const chains: Chain[] = [];
  comps.forEach((idxs) => {
    const sub = idxs.map((i: number) => segCoords[i]);
    const coords = chainComponent(sub);
    if (coords.length < 2) return;
    const lengthKm = turfLength(turfLine(coords), { units: 'kilometers' });
    chains.push({ coords, lengthKm });
  });
  if (!chains.length) return [];

  // Greedy bridge: starting from the longest chain, repeatedly absorb
  // any other chain whose endpoint is within CHAIN_BRIDGE_TOLERANCE_DEG
  // of one of our endpoints. Concatenate in the appropriate orientation.
  // We stop only when nothing else can be reached.
  chains.sort((a, b) => b.lengthKm - a.lengthKm);
  const main = chains[0];
  const used = new Set<number>([0]);
  let workCoords = main.coords.slice();
  // Repeatedly scan for chains whose start or end is near workCoords' head
  // or tail. tol is in WGS84 degrees, anisotropic at MO latitudes but the
  // tolerance is a generous bound (~1.2 km) so the approximation is fine.
  let progressed = true;
  while (progressed) {
    progressed = false;
    const head = workCoords[0];
    const tail = workCoords[workCoords.length - 1];
    type BridgeMode = 'prepend' | 'prepend-rev' | 'append' | 'append-rev';
    let bestIdx = -1;
    let bestDist = CHAIN_BRIDGE_TOLERANCE_DEG;
    let bestMode: BridgeMode = 'append';
    for (let i = 1; i < chains.length; i++) {
      if (used.has(i)) continue;
      const c = chains[i].coords;
      const cs = c[0], ce = c[c.length - 1];
      const candidates: Array<{ d: number; mode: BridgeMode }> = [
        { d: distDeg(tail, cs), mode: 'append' },
        { d: distDeg(tail, ce), mode: 'append-rev' },
        { d: distDeg(head, ce), mode: 'prepend' },
        { d: distDeg(head, cs), mode: 'prepend-rev' },
      ];
      for (const ca of candidates) {
        if (ca.d < bestDist) { bestDist = ca.d; bestIdx = i; bestMode = ca.mode; }
      }
    }
    if (bestIdx >= 0) {
      const c = chains[bestIdx].coords;
      switch (bestMode) {
        case 'append':      workCoords = workCoords.concat(c); break;
        case 'append-rev':  workCoords = workCoords.concat(c.slice().reverse()); break;
        case 'prepend':     workCoords = c.concat(workCoords); break;
        case 'prepend-rev': workCoords = c.slice().reverse().concat(workCoords); break;
      }
      used.add(bestIdx);
      progressed = true;
    }
  }
  return workCoords;
}

/**
 * Walk a single connected component upstream→downstream into a LineString.
 * Picks an endpoint of degree 1 as the head (the upstream-most leaf),
 * falls back to seg 0 if the component is a closed loop.
 */
function chainComponent(segs: number[][][]): number[][] {
  const startMap = new Map<string, number[]>();
  const degree = new Map<string, number>();
  for (let i = 0; i < segs.length; i++) {
    const sk = pointKey(segs[i][0]);
    const ek = pointKey(segs[i][segs[i].length - 1]);
    degree.set(sk, (degree.get(sk) ?? 0) + 1);
    degree.set(ek, (degree.get(ek) ?? 0) + 1);
    if (!startMap.has(sk)) startMap.set(sk, []);
    startMap.get(sk)!.push(i);
  }
  let head = -1;
  degree.forEach((deg, pt) => {
    if (head < 0 && deg === 1 && startMap.has(pt)) head = startMap.get(pt)![0];
  });
  if (head < 0) head = 0;

  const merged: number[][] = [];
  const visited = new Set<number>();
  let cur: number = head;
  while (cur >= 0 && !visited.has(cur)) {
    visited.add(cur);
    const seg = segs[cur];
    if (!merged.length) merged.push(...seg);
    else merged.push(...seg.slice(1));
    const ek = pointKey(seg[seg.length - 1]);
    const candidates = (startMap.get(ek) ?? []).filter((n) => !visited.has(n));
    cur = candidates[0] ?? -1;
  }
  // Append leftovers whose start matches our tail.
  for (let i = 0; i < segs.length; i++) {
    if (visited.has(i)) continue;
    const seg = segs[i];
    if (merged.length && pointKey(merged[merged.length - 1]) === pointKey(seg[0])) {
      merged.push(...seg.slice(1));
      visited.add(i);
    }
  }
  return merged;
}

async function main() {
  const args = process.argv.slice(2);
  const outIdx = args.indexOf('--out');
  const outPath = outIdx >= 0 ? args[outIdx + 1] : null;
  const apply = args.includes('--apply');
  const db = apply ? getSupabase() : null;
  const slugArgs = args.filter((a, i) => !a.startsWith('--') && (outIdx < 0 || i !== outIdx + 1));
  const rivers = slugArgs.length
    ? RIVERS.filter((r) => slugArgs.includes(r.slug))
    : RIVERS;
  const unknown = slugArgs.filter((s) => !RIVERS.some((r) => r.slug === s));
  if (unknown.length) throw new Error(`Unknown river slug(s): ${unknown.join(', ')}`);
  const cacheDir = join(process.cwd(), 'tmp', 'nhd');
  mkdirSync(cacheDir, { recursive: true });

  // Lazy-load shpjs after the `self` polyfill above is in place.
  const shpModule = (await import('shpjs')) as unknown as {
    default: (b: ArrayBuffer) => Promise<Array<{ fileName: string; features: SegFeature[] }>>;
  };
  const shp = shpModule.default;

  const sqlChunks: string[] = [
    '-- Generated by scripts/import-nhd-rivers-from-tnm.ts',
    '-- Source: USGS National Map NHD HR HUC8 shapefiles',
    '-- Apply via Supabase SQL editor or psql.',
    '',
  ];

  const log = (msg: string) => process.stderr.write(msg + '\n');
  log('NHD HR import');
  log('='.repeat(60));

  // Parse each needed HUC zip once, keeping only the flowlines any
  // requested river matches by gnis_name (an HU8 zip carries ~50k
  // flowlines; holding several whole HUCs would be wasteful).
  const wantedNames = new Set(rivers.flatMap((r) => r.gnisNames));
  const flowByHuc = new Map<string, SegFeature[]>();
  for (const huc of new Set(rivers.flatMap((r) => r.hucs))) {
    const zipPath = await ensureZip(huc, cacheDir);
    const buf = readFileSync(zipPath);
    const layers = await shp(buf.buffer);
    const flow = layers.find((l) => l.fileName === 'Shape/NHDFlowline');
    if (!flow) { log(`  HUC ${huc}: no NHDFlowline layer`); flowByHuc.set(huc, []); continue; }
    const kept = flow.features.filter((f) =>
      f.properties.gnis_name != null && wantedNames.has(f.properties.gnis_name) &&
      f.properties.fcode != null && FCODE_PERENNIAL.has(f.properties.fcode),
    );
    log(`HUC ${huc} · ${flow.features.length} flowlines · ${kept.length} kept`);
    flowByHuc.set(huc, kept);
  }

  for (const river of rivers) {
    const matches = river.hucs.flatMap((huc) =>
      (flowByHuc.get(huc) ?? []).filter((f) => river.gnisNames.includes(f.properties.gnis_name!)),
    );
    if (!matches.length) { log(`  ${river.slug}: no perennial matches in HUC(s) ${river.hucs.join('+')}`); continue; }
    const merged = dissolveLongest(matches);
    if (merged.length < 2) { log(`  ${river.slug}: dissolve produced no chain`); continue; }
    const ls: Feature<LineString> = turfLine(merged);
    const lengthMi = turfLength(ls, { units: 'miles' });
    const simplified = simplify(ls, {
      tolerance: SIMPLIFY_TOLERANCE_DEG,
      highQuality: true,
    }) as Feature<LineString>;
    const coords = simplified.geometry.coordinates.map((c) => [
      Number(c[0].toFixed(6)), Number(c[1].toFixed(6)),
    ]);
    log(`  ${river.slug.padEnd(22)} ${matches.length} segs → ${merged.length} pts ` +
        `(${lengthMi.toFixed(1)} mi) → ${coords.length} simplified [${river.mode}]`);

    // NHD flowlines are digitized downstream, and the chain walk starts
    // from a degree-1 segment start (the upstream-most leaf), so the
    // last coordinate is the downstream end.
    const [dLon, dLat] = coords[coords.length - 1];
    const lengthMiles = Math.round(lengthMi * 100) / 100;

    if (apply && db) {
      const { data: existing } = await db.from('rivers').select('id').eq('slug', river.slug).maybeSingle();
      if (existing) {
        if (river.mode === 'insert') { log(`    ⏭️  ${river.slug} already exists — not overwriting geometry`); continue; }
        const { error } = await db.from('rivers')
          .update({ geom: { type: 'LineString', coordinates: coords }, direction_verified: true })
          .eq('id', existing.id);
        if (error) throw new Error(`rivers geom update ${river.slug}: ${error.message}`);
        log(`    ✅ geometry updated`);
      } else {
        const meta = loadRiverMeta(river.slug);
        const { error } = await db.from('rivers').insert({
          name: meta.name, slug: river.slug,
          geom: { type: 'LineString', coordinates: coords },
          length_miles: lengthMiles,
          downstream_point: { type: 'Point', coordinates: [dLon, dLat] },
          direction_verified: true,
          description: meta.description, difficulty_rating: meta.difficultyRating,
          region: meta.region, state: meta.state ?? 'MO',
          timezone: meta.timezone ?? 'America/Chicago',
          river_type: meta.riverType ?? 'spring_fed_float',
          active: false,
        });
        if (error) throw new Error(`rivers insert ${river.slug}: ${error.message}`);
        log(`    ✅ row created (active=false)`);
      }
      continue;
    }

    const wkt = 'LINESTRING(' +
      coords.map((c) => c[0] + ' ' + c[1]).join(',') + ')';
    if (river.mode === 'update') {
      sqlChunks.push(
        `UPDATE rivers SET geom = ST_GeomFromText('${wkt}', 4326), direction_verified = true WHERE slug = '${river.slug}';`,
      );
    } else {
      const meta = loadRiverMeta(river.slug);
      sqlChunks.push(
        `INSERT INTO rivers (name, slug, geom, length_miles, downstream_point, direction_verified,`,
        `  description, difficulty_rating, region, state, timezone, river_type, active)`,
        `SELECT ${sqlQuote(meta.name)}, ${sqlQuote(river.slug)},`,
        `  ST_GeomFromText('${wkt}', 4326), ${lengthMiles},`,
        `  ST_SetSRID(ST_MakePoint(${dLon}, ${dLat}), 4326), true,`,
        `  ${sqlQuote(meta.description)}, ${sqlQuote(meta.difficultyRating)}, ${sqlQuote(meta.region)},`,
        `  ${sqlQuote(meta.state ?? 'MO')}, ${sqlQuote(meta.timezone ?? 'America/Chicago')}, ${sqlQuote(meta.riverType ?? 'spring_fed_float')}, false`,
        `WHERE NOT EXISTS (SELECT 1 FROM rivers WHERE slug = ${sqlQuote(river.slug)});`,
        '',
      );
    }
  }

  if (!apply) {
    const sql = sqlChunks.join('\n') + '\n';
    if (outPath) {
      writeFileSync(outPath, sql);
      log(`\nWrote ${sql.length} bytes to ${outPath}`);
    } else {
      process.stdout.write(sql);
    }
  }
  log('\nDone.');
}

main().catch((e) => { console.error('FATAL:', e); process.exit(1); });
