#!/usr/bin/env npx tsx
/**
 * Import real NHD HR river geometry from USGS National Map S3 into rivers.geom.
 *
 * The original `scripts/import-nhd-rivers.ts` queries USGS NHDPlus_HR ArcGIS
 * REST and silently falls back to hand-typed seed coordinates when the WFS
 * call fails. That's why `rivers.geom` was historically a near-straight
 * polyline of ~30 vertices for every floatable river. This script replaces
 * that pipeline with HUC8 shapefile downloads from USGS TNM S3, which is
 * publicly reachable and ships authoritative NHDFlowline data.
 *
 * Pipeline (per river):
 *  1. Download `NHD_H_<HUC8>_HU8_Shape.zip` from prd-tnm.s3.amazonaws.com
 *     (cached in `tmp/nhd/`).
 *  2. Parse `NHDFlowline.shp` with shpjs.
 *  3. Filter to features with the river's `gnis_name` and FCode in
 *     {46006 perennial, 55800 connector, 46000 stream/river-unspecified}.
 *     (46000 is required for rivers like War Eagle Creek whose middle reach is
 *     tagged 46000 — excluding it splits the main stem and drops the lower half.)
 *  4. Build connected components by endpoint adjacency, walk each into a
 *     single LineString, return the LONGEST component (= the main channel).
 *  5. Simplify with Douglas-Peucker tolerance 0.0005 deg (~50m at MO lat).
 *  6. UPDATE rivers SET geom = ST_GeomFromText(...).
 *
 * Run:  npx tsx scripts/import-nhd-rivers-from-tnm.ts                 # all rivers
 *       npx tsx scripts/import-nhd-rivers-from-tnm.ts bourbeuse black # only these slugs
 *       npx tsx scripts/import-nhd-rivers-from-tnm.ts --out tmp/update.sql
 *       npx tsx scripts/import-nhd-rivers-from-tnm.ts bourbeuse --apply  # write to DB
 *
 * The script emits SQL to stdout (or to a file with --out), or writes rows
 * directly with --apply. `--apply` goes through `getScriptClient` from
 * scripts/lib/db.ts, so it needs credentials AND `EXPECTED_SUPABASE_REF`
 * exported in the shell naming the project those credentials resolve to.
 * Without the pin it refuses to open a write connection and prints the exact
 * export line — this script rewrites `rivers.geom`, which every access-point
 * river mile is measured against, so "which project am I pointed at" is not a
 * question to answer by accident. Rivers already in prod get their
 * geometry refreshed (mode 'update'); rivers marked mode:'insert' are
 * created if absent, with metadata pulled from scripts/config/nhd-rivers.json
 * and active=false — activation stays a human call after
 * validate_river_data() (see ingestion/DEPLOYMENT-STATUS.md).
 * Emitted SQL can be applied via Supabase SQL editor or:
 *   psql "$DATABASE_URL" -f tmp/update.sql
 *
 * The committed migration `00116_import_real_nhd_river_geometry.sql`
 * already contains the geometry generated by this script for the original
 * seven rivers, so a fresh DB recreated via `npm run db:migrate` will get
 * the same data without needing to re-download HUC8 zips.
 *
 * Requires `tsx` + `shpjs` + `@turf/turf` (already in devDependencies).
 */

import { readFileSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { simplify, lineString as turfLine, length as turfLength } from '@turf/turf';
import type { Feature, LineString } from 'geojson';
// The flowline download and dissolve live in scripts/lib/nhd.ts so
// scripts/ingestion/build-tailwater-geometry.ts can share them rather than
// keep a second copy of a tuned bridging tolerance.
import {
  SIMPLIFY_TOLERANCE_DEG,
  dissolveLongest,
  loadFlowlines,
  type SegFeature,
} from './lib/nhd';
import { getScriptClient } from './lib/db';

// Per-river spec: which GNIS names to match (NHD sometimes carries name
// variants — list them all) and which HUC8 basins the main stem crosses
// (a river spanning two HUC8s, like the Gasconade, needs both zips merged
// before dissolving). Verify a river's HUC8 by querying USGS WBD or by
// trial: shpjs the HU8 zip and group features by gnis_name.
// mode:'update' = row exists in prod, refresh geometry only.
// mode:'insert' = create the rivers row if absent (metadata from
// scripts/config/nhd-rivers.json, active=false).
interface RiverSpec {
  slug: string;
  gnisNames: string[];
  hucs: string[];
  mode: 'update' | 'insert';
}

const RIVERS: RiverSpec[] = [
  // Original seven (geometry source for migration 00116)
  { slug: 'current',      gnisNames: ['Current River'],      hucs: ['11010008'], mode: 'update' },
  { slug: 'jacks-fork',   gnisNames: ['Jacks Fork'],         hucs: ['11010008'], mode: 'update' },
  { slug: 'eleven-point', gnisNames: ['Eleven Point River'], hucs: ['11010011'], mode: 'update' },
  { slug: 'meramec',      gnisNames: ['Meramec River'],      hucs: ['07140102'], mode: 'update' },
  { slug: 'huzzah',       gnisNames: ['Huzzah Creek'],       hucs: ['07140102'], mode: 'update' },
  { slug: 'courtois',     gnisNames: ['Courtois Creek'],     hucs: ['07140102'], mode: 'update' },
  { slug: 'niangua',      gnisNames: ['Niangua River'],      hucs: ['10290110'], mode: 'update' },
  { slug: 'big-piney',    gnisNames: ['Big Piney River'],    hucs: ['10290202'], mode: 'update' },
  // 2026-07 onboarding batch (see scripts/ingestion/DEPLOYMENT-STATUS.md)
  { slug: 'bourbeuse',  gnisNames: ['Bourbeuse River'],  hucs: ['07140103'], mode: 'insert' },
  { slug: 'gasconade',  gnisNames: ['Gasconade River'],  hucs: ['10290201', '10290203'], mode: 'insert' },
  { slug: 'black',      gnisNames: ['Black River'],      hucs: ['11010007'], mode: 'insert' },
  { slug: 'st-francis', gnisNames: ['St. Francis River', 'Saint Francis River'], hucs: ['08020202'], mode: 'insert' },
  { slug: 'buffalo',    gnisNames: ['Buffalo River'],    hucs: ['11010005'], mode: 'insert' },
  // 2026-07 second onboarding batch (dossiers AWAITING SIGNOFF; see DEPLOYMENT-STATUS.md)
  { slug: 'north-fork-white', gnisNames: ['North Fork River', 'North Fork White River'], hucs: ['11010006'], mode: 'insert' },
  { slug: 'elk',              gnisNames: ['Elk River'],    hucs: ['11070208'], mode: 'insert' },
  { slug: 'james',            gnisNames: ['James River'],  hucs: ['11010002'], mode: 'insert' },
  { slug: 'spring-river',     gnisNames: ['Spring River'], hucs: ['11010010'], mode: 'insert' },
  // 2026-07 third onboarding batch (HUC8s pulled from each river's USGS gauge huc_cd)
  { slug: 'mulberry',        gnisNames: ['Mulberry River'],   hucs: ['11110201'], mode: 'insert' },
  { slug: 'kings-river',     gnisNames: ['Kings River'],      hucs: ['11010001'], mode: 'insert' },
  { slug: 'crooked-creek',   gnisNames: ['Crooked Creek'],    hucs: ['11010003'], mode: 'insert' },
  { slug: 'bryant-creek',    gnisNames: ['Bryant Creek'],     hucs: ['11010006'], mode: 'insert' },
  { slug: 'caddo-river',     gnisNames: ['Caddo River'],      hucs: ['08040102'], mode: 'insert' },
  { slug: 'war-eagle-creek', gnisNames: ['War Eagle Creek'],  hucs: ['11010001'], mode: 'update' },
  { slug: 'big-river',       gnisNames: ['Big River'],        hucs: ['07140104'], mode: 'insert' },
  // 2026-07 — Missouri Spring River (distinct from the AR 'spring-river' above; different
  // HUC). Carthage→Kansas-line float; gnis 'Spring River' within HUC 11070207 is the mainstem.
  { slug: 'spring-river-mo',  gnisNames: ['Spring River'],     hucs: ['11070207'], mode: 'insert' },
];

interface RiverMeta {
  name: string;
  slug: string;
  description: string;
  difficultyRating: string;
  region: string;
  state?: string;
  timezone?: string;
  riverType?: string;
}

function loadRiverMeta(slug: string): RiverMeta {
  const configPath = join(__dirname, 'config', 'nhd-rivers.json');
  const raw = JSON.parse(readFileSync(configPath, 'utf-8'));
  const meta = (raw.rivers as RiverMeta[]).find((r) => r.slug === slug);
  if (!meta) throw new Error(`No entry for slug '${slug}' in scripts/config/nhd-rivers.json`);
  return meta;
}

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}



async function main() {
  const args = process.argv.slice(2);
  const outIdx = args.indexOf('--out');
  const outPath = outIdx >= 0 ? args[outIdx + 1] : null;
  const apply = args.includes('--apply');
  // --apply REWRITES rivers.geom, which is what every access-point river mile
  // is measured against. It goes through the guarded client so the write
  // cannot land on whichever project the ambient environment happens to name:
  // getScriptClient refuses a write connection unless EXPECTED_SUPABASE_REF is
  // exported in the shell AND matches the project the credentials resolve to.
  const db = apply
    ? getScriptClient({ script: 'import-nhd-rivers-from-tnm', write: true })
    : null;
  const slugArgs = args.filter((a, i) => !a.startsWith('--') && (outIdx < 0 || i !== outIdx + 1));
  const rivers = slugArgs.length
    ? RIVERS.filter((r) => slugArgs.includes(r.slug))
    : RIVERS;
  const unknown = slugArgs.filter((s) => !RIVERS.some((r) => r.slug === s));
  if (unknown.length) throw new Error(`Unknown river slug(s): ${unknown.join(', ')}`);
  const cacheDir = join(process.cwd(), 'tmp', 'nhd');
  mkdirSync(cacheDir, { recursive: true });

  const sqlChunks: string[] = [
    '-- Generated by scripts/import-nhd-rivers-from-tnm.ts',
    '-- Source: USGS National Map NHD HR HUC8 shapefiles',
    '-- Apply via Supabase SQL editor or psql.',
    '',
  ];

  const log = (msg: string) => process.stderr.write(msg + '\n');
  log('NHD HR import');
  log('='.repeat(60));

  // Parse each needed HUC zip once, keeping only the flowlines any
  // requested river matches by gnis_name (an HU8 zip carries ~50k
  // flowlines; holding several whole HUCs would be wasteful).
  const wantedNames = new Set(rivers.flatMap((r) => r.gnisNames));
  const flowByHuc = await loadFlowlines(
    rivers.flatMap((r) => r.hucs),
    wantedNames,
    cacheDir,
    log,
  );

  for (const river of rivers) {
    const matches = river.hucs.flatMap((huc) =>
      (flowByHuc.get(huc) ?? []).filter((f) => river.gnisNames.includes(f.properties.gnis_name!)),
    );
    if (!matches.length) { log(`  ${river.slug}: no perennial matches in HUC(s) ${river.hucs.join('+')}`); continue; }
    const merged = dissolveLongest(matches);
    if (merged.length < 2) { log(`  ${river.slug}: dissolve produced no chain`); continue; }
    const ls: Feature<LineString> = turfLine(merged);
    const lengthMi = turfLength(ls, { units: 'miles' });
    const simplified = simplify(ls, {
      tolerance: SIMPLIFY_TOLERANCE_DEG,
      highQuality: true,
    }) as Feature<LineString>;
    const coords = simplified.geometry.coordinates.map((c) => [
      Number(c[0].toFixed(6)), Number(c[1].toFixed(6)),
    ]);
    log(`  ${river.slug.padEnd(22)} ${matches.length} segs → ${merged.length} pts ` +
        `(${lengthMi.toFixed(1)} mi) → ${coords.length} simplified [${river.mode}]`);

    // NHD flowlines are digitized downstream, and the chain walk starts
    // from a degree-1 segment start (the upstream-most leaf), so the
    // last coordinate is the downstream end.
    const [dLon, dLat] = coords[coords.length - 1];
    const lengthMiles = Math.round(lengthMi * 100) / 100;

    if (apply && db) {
      const { data: existing } = await db.from('rivers').select('id').eq('slug', river.slug).maybeSingle();
      if (existing) {
        if (river.mode === 'insert') { log(`    ⏭️  ${river.slug} already exists — not overwriting geometry`); continue; }
        const { error } = await db.from('rivers')
          .update({ geom: { type: 'LineString', coordinates: coords }, direction_verified: true })
          .eq('id', existing.id);
        if (error) throw new Error(`rivers geom update ${river.slug}: ${error.message}`);
        log(`    ✅ geometry updated`);
      } else {
        const meta = loadRiverMeta(river.slug);
        const { error } = await db.from('rivers').insert({
          name: meta.name, slug: river.slug,
          geom: { type: 'LineString', coordinates: coords },
          length_miles: lengthMiles,
          downstream_point: { type: 'Point', coordinates: [dLon, dLat] },
          direction_verified: true,
          description: meta.description, difficulty_rating: meta.difficultyRating,
          region: meta.region, state: meta.state ?? 'MO',
          timezone: meta.timezone ?? 'America/Chicago',
          river_type: meta.riverType ?? 'spring_fed_float',
          active: false,
        });
        if (error) throw new Error(`rivers insert ${river.slug}: ${error.message}`);
        log(`    ✅ row created (active=false)`);
      }
      continue;
    }

    const wkt = 'LINESTRING(' +
      coords.map((c) => c[0] + ' ' + c[1]).join(',') + ')';
    if (river.mode === 'update') {
      sqlChunks.push(
        `UPDATE rivers SET geom = ST_GeomFromText('${wkt}', 4326), direction_verified = true WHERE slug = '${river.slug}';`,
      );
    } else {
      const meta = loadRiverMeta(river.slug);
      sqlChunks.push(
        `INSERT INTO rivers (name, slug, geom, length_miles, downstream_point, direction_verified,`,
        `  description, difficulty_rating, region, state, timezone, river_type, active)`,
        `SELECT ${sqlQuote(meta.name)}, ${sqlQuote(river.slug)},`,
        `  ST_GeomFromText('${wkt}', 4326), ${lengthMiles},`,
        `  ST_SetSRID(ST_MakePoint(${dLon}, ${dLat}), 4326), true,`,
        `  ${sqlQuote(meta.description)}, ${sqlQuote(meta.difficultyRating)}, ${sqlQuote(meta.region)},`,
        `  ${sqlQuote(meta.state ?? 'MO')}, ${sqlQuote(meta.timezone ?? 'America/Chicago')}, ${sqlQuote(meta.riverType ?? 'spring_fed_float')}, false`,
        `WHERE NOT EXISTS (SELECT 1 FROM rivers WHERE slug = ${sqlQuote(river.slug)});`,
        '',
      );
    }
  }

  if (!apply) {
    const sql = sqlChunks.join('\n') + '\n';
    if (outPath) {
      writeFileSync(outPath, sql);
      log(`\nWrote ${sql.length} bytes to ${outPath}`);
    } else {
      process.stdout.write(sql);
    }
  }
  log('\nDone.');
}

main().catch((e) => { console.error('FATAL:', e); process.exit(1); });
