import Link from 'next/link';
import {
  MapPin,
  Image as ImageIcon,
  Navigation,
  Flag,
  FileText,
  Activity,
  RefreshCw,
  Share2,
  Layers,
  ShieldAlert,
  MessageSquare,
  History,
  Compass,
  Film,
  ShieldCheck,
  Bot,
} from 'lucide-react';

const ADMIN_SECTIONS = [
  {
    title: 'Trust',
    description: 'Data-quality findings from the scheduled checks',
    href: '/admin/trust',
    icon: ShieldCheck,
    color: 'bg-red-500',
    statKey: 'openCriticalFindings' as const,
    statLabel: 'critical',
  },
  {
    title: 'Feedback',
    description: 'Review user-submitted feedback and data reports',
    href: '/admin/feedback',
    icon: Flag,
    color: 'bg-accent-500',
    statKey: 'pendingFeedback' as const,
    statLabel: 'pending',
  },
  {
    title: 'Access Points',
    description: 'Manage access point images and details',
    href: '/admin/access-points',
    icon: Navigation,
    color: 'bg-teal-500',
    statKey: 'unapprovedAccessPoints' as const,
    statLabel: 'unapproved',
  },
  {
    title: 'Geography Editor',
    description: 'Edit access point locations and river line geometries',
    href: '/admin/geography',
    icon: MapPin,
    color: 'bg-blue-500',
  },
  {
    title: 'Blog Posts',
    description: 'Create and manage blog posts and river guides',
    href: '/admin/blog',
    icon: FileText,
    color: 'bg-orange-500',
  },
  {
    title: 'Gauge Thresholds',
    description: 'Configure water level thresholds and floating descriptions',
    href: '/admin/gauges',
    icon: Activity,
    color: 'bg-green-500',
  },
  {
    title: 'Data Sync',
    description: 'Sync USFS campgrounds as pending POIs from Recreation.gov (RIDB)',
    href: '/admin/data-sync',
    icon: RefreshCw,
    color: 'bg-emerald-500',
  },
  {
    title: 'Image Library',
    description: 'Upload and manage images for rivers, access points, and more',
    href: '/admin/images',
    icon: ImageIcon,
    color: 'bg-purple-500',
  },
  {
    title: 'Points of Interest',
    description: 'Manage springs, caves, campgrounds, and other points of interest',
    href: '/admin/pois',
    icon: Compass,
    color: 'bg-cyan-500',
  },
  {
    title: 'Hazards',
    description: 'Manage river hazards, portages, and safety warnings',
    href: '/admin/hazards',
    icon: ShieldAlert,
    color: 'bg-red-500',
  },
  {
    title: 'Community Reports',
    description: 'Review and moderate user-submitted hazard and condition reports',
    href: '/admin/reports',
    icon: MessageSquare,
    color: 'bg-indigo-500',
  },
  {
    title: 'Social Media',
    description: 'Manage Instagram and Facebook auto-posting settings and history',
    href: '/admin/social',
    icon: Share2,
    color: 'bg-pink-500',
  },
  {
    title: 'Clip Library',
    description: 'YouTube clip extraction, brand checks, montage compilation, and content decisions',
    href: '/admin/clips',
    icon: Film,
    color: 'bg-violet-500',
  },
  {
    title: 'AI Models',
    description: 'Choose which Claude model writes river updates, gauge updates, the statewide summary, and captions',
    href: '/admin/ai-models',
    icon: Bot,
    color: 'bg-sky-500',
  },
  {
    title: 'Activity Log',
    description: 'View admin action history and audit trail',
    href: '/admin/activity',
    icon: History,
    color: 'bg-neutral-500',
  },
];
export default function DashboardLinks() {
 return <nav aria-label="Manage Eddy" className="flex flex-wrap gap-2">{ADMIN_SECTIONS.map(s=><Link key={s.href} href={s.href} className="rounded-lg border border-neutral-700 px-3 py-2 text-sm text-neutral-200 hover:bg-neutral-800">{s.title}</Link>)}</nav>;
}
