// src/components/map/layer-anchors.ts
// Deterministic layer-insertion slots for the interactive map.
//
// The curated basemap (public/map-styles/eddy-natural.json, generated by
// scripts/build-map-style.ts) bakes two zero-opacity `background` layers
// into its stack as insertion anchors. Runtime layers pass an anchor to
// addLayerAt() instead of guessing a position (the old radar code scanned
// the style for "the first line layer"; RouteLayer appended topmost and
// covered town labels).
//
//   overlays — above water/land fills, below roads and every label.
//              Rasters live here: hillshade, weather radar.
//   lines    — above all physical geometry, below every label.
//              Data lines live here: river reaches, routes.
//
// Multiple layers added at the same anchor stack in call order (each
// inserts immediately before the anchor, i.e. above the previous one).
//
// On styles without baked anchors (Positron, satellite) we fall back to
// the first symbol layer — same "data below labels" guarantee — or to
// appending on styles with no symbols at all (satellite).

import type maplibregl from 'maplibre-gl';

export const ANCHORS = {
  overlays: 'eddy-anchor-overlays',
  lines: 'eddy-anchor-lines',
} as const;

export type AnchorName = (typeof ANCHORS)[keyof typeof ANCHORS];

/** Resolve the beforeId an anchor maps to on the current style. */
export function anchorBeforeId(
  map: maplibregl.Map,
  anchor: AnchorName,
): string | undefined {
  try {
    if (map.getLayer(anchor)) return anchor;
    const layers = map.getStyle()?.layers ?? [];
    return layers.find((l) => l.type === 'symbol')?.id;
  } catch {
    return undefined;
  }
}

/** map.addLayer with a deterministic position instead of a guess. */
export function addLayerAt(
  map: maplibregl.Map,
  layer: maplibregl.LayerSpecification,
  anchor: AnchorName,
): void {
  map.addLayer(layer, anchorBeforeId(map, anchor));
}
