'use client';

// src/components/map/MapContainer.tsx
// Main map wrapper component using MapLibre GL JS
// Includes optional RainViewer weather radar overlay

import { useEffect, useRef, useState, useCallback } from 'react';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import { Layers, Maximize2, Minimize2 } from 'lucide-react';
import { conditionColor, CONDITION_ORDER } from '@shared/condition-system';
import { CONDITION_SHORT_LABELS } from '@/constants';
import { ANCHORS, addLayerAt } from './layer-anchors';

// Available map styles (all free, no API key required)
// Immersive is first and default: satellite imagery with luminous water
// veins, haloed labels, and the baked layer anchors — so condition-colored
// rivers render over the imagery just like on Natural. It reads as the
// PaddleWays-class experience out of the box while staying flat 2D (the 3D
// tilt is an opt-in toggle). Generated by scripts/build-map-style.ts.
const MAP_STYLES = {
  immersive: {
    name: 'Immersive',
    url: '/map-styles/eddy-immersive.json',
    dark: true,
  },
  liberty: {
    // Eddy's curated fork of OpenFreeMap Liberty: water-first palette,
    // decluttered, baked layer anchors, hillshade relief.
    name: 'Natural',
    url: '/map-styles/eddy-natural.json',
    dark: false,
  },
  positron: {
    name: 'Light',
    url: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    dark: false,
  },
  satellite: {
    name: 'Satellite',
    url: '', // Custom style object used instead
    dark: true,
  },
} as const;

// Custom satellite style using ESRI World Imagery (free, no API key)
const SATELLITE_STYLE: maplibregl.StyleSpecification = {
  version: 8,
  sources: {
    'esri-satellite': {
      type: 'raster',
      tiles: [
        'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
      ],
      tileSize: 256,
      attribution: '&copy; Esri, DigitalGlobe, GeoEye, Earthstar Geographics, CNES/Airbus DS, USDA, USGS, AeroGRID, IGN',
      maxzoom: 19,
    },
  },
  layers: [
    {
      id: 'esri-satellite-layer',
      type: 'raster',
      source: 'esri-satellite',
      minzoom: 0,
      maxzoom: 22,
    },
  ],
};

type MapStyleKey = keyof typeof MAP_STYLES;

// ── Terrain relief ──────────────────────────────────────────────────────
// Subtle hillshade from free AWS Terrain Tiles (Mapzen terrarium encoding,
// same public-domain source the Observatory's baked relief uses — see
// scripts/build-mo-hillshade.ts). Rendered live by MapLibre's hillshade
// layer at the curated style's overlay anchor: above land fills, below
// water lines, roads, and labels. Lakes stay clean because flat DEM cells
// produce no shade. maxzoom 12 caps tile fetches; overzoom upsampling is
// invisible for shaded relief.
const TERRAIN_DEM_SOURCE_ID = 'eddy-terrain-dem';
const HILLSHADE_LAYER_ID = 'eddy-hillshade';

// Add the terrain DEM source if missing. Shared by the hillshade layer
// (Natural style) and the 3D terrain toggle (any style).
function ensureTerrainDem(map: maplibregl.Map) {
  if (!map.getSource(TERRAIN_DEM_SOURCE_ID)) {
    map.addSource(TERRAIN_DEM_SOURCE_ID, {
      type: 'raster-dem',
      tiles: [
        'https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png',
      ],
      encoding: 'terrarium',
      tileSize: 256,
      maxzoom: 12,
      attribution:
        'Terrain: <a href="https://registry.opendata.aws/terrain-tiles/" target="_blank">AWS Terrain Tiles</a>',
    });
  }
}

function ensureHillshade(map: maplibregl.Map) {
  // Anchors are the capability signal, but the shaded-relief layer only
  // belongs on the curated Natural style — imagery carries its own light
  // and shadow, so callers additionally gate on the style key.
  if (!map.getLayer(ANCHORS.overlays)) return;
  ensureTerrainDem(map);
  if (!map.getLayer(HILLSHADE_LAYER_ID)) {
    addLayerAt(
      map,
      {
        id: HILLSHADE_LAYER_ID,
        type: 'hillshade',
        source: TERRAIN_DEM_SOURCE_ID,
        paint: {
          // Gentle: the Ozarks should read as texture, not topography.
          'hillshade-exaggeration': 0.3,
          'hillshade-shadow-color': 'rgba(74, 66, 52, 0.5)',
          'hillshade-highlight-color': 'rgba(255, 255, 255, 0.4)',
        },
      },
      ANCHORS.overlays,
    );
  }
}

// Camera state parsed from ?lat&lng&z (PaddleWays-style shareable views).
interface UrlCamera {
  lat: number;
  lng: number;
  z: number;
}

function readCameraFromUrl(): UrlCamera | null {
  if (typeof window === 'undefined') return null;
  const p = new URLSearchParams(window.location.search);
  const lat = parseFloat(p.get('lat') ?? '');
  const lng = parseFloat(p.get('lng') ?? '');
  const z = parseFloat(p.get('z') ?? '');
  if (!Number.isFinite(lat) || !Number.isFinite(lng) || !Number.isFinite(z)) return null;
  if (lat < -90 || lat > 90 || lng < -180 || lng > 180 || z < 0 || z > 22) return null;
  return { lat, lng, z };
}

interface MapContainerProps {
  initialBounds?: [number, number, number, number]; // [minLng, minLat, maxLng, maxLat]
  children?: React.ReactNode;
  showWeatherOverlay?: boolean;
  onWeatherToggle?: (enabled: boolean) => void;
  showLegend?: boolean;
  /**
   * Show the route-direction legend rows (downstream/upstream greens).
   * Pages that render ConditionRiverLayer instead of RouteLayer pass
   * false so green only ever means one thing per surface.
   */
  legendRoute?: boolean;
  /**
   * Mirror the camera to ?lat&lng&z via history.replaceState so the
   * current view is shareable/deep-linkable. On load, a valid camera in
   * the URL wins over initialBounds ONCE (the deep link IS the intent);
   * later bounds changes (e.g. picking a different river) fit as usual.
   */
  syncCameraToUrl?: boolean;
  cooperativeGestures?: boolean;
}

// RainViewer API types
interface RainViewerResponse {
  version: string;
  generated: number;
  host: string;
  radar: {
    past: Array<{ time: number; path: string }>;
    nowcast: Array<{ time: number; path: string }>;
  };
}

export default function MapContainer({
  initialBounds,
  children,
  showWeatherOverlay = false,
  onWeatherToggle,
  showLegend = false,
  legendRoute = true,
  syncCameraToUrl = false,
  cooperativeGestures = false,
}: MapContainerProps) {
  const mapContainer = useRef<HTMLDivElement>(null);
  const map = useRef<maplibregl.Map | null>(null);
  const [mapLoaded, setMapLoaded] = useState(false);
  const [weatherEnabled, setWeatherEnabled] = useState(showWeatherOverlay);
  const [radarTimestamp, setRadarTimestamp] = useState<string | null>(null);
  const [mapStyle, setMapStyle] = useState<MapStyleKey>('immersive');
  const [showStylePicker, setShowStylePicker] = useState(false);
  const stylePickerRef = useRef<HTMLDivElement>(null);
  // Current style key, readable from the persistent style.load handler
  // (state would be a stale closure there).
  const styleKeyRef = useRef<MapStyleKey>('liberty');
  // Bumped after every style.load. setStyle() wipes all custom sources/
  // layers, but child layer components (RouteLayer, markers, …) key their
  // effects on data, not style — so before this existed, switching the
  // base style silently dropped the route line and overlays until the
  // next data change. Children remount via key={styleEpoch} instead.
  const [styleEpoch, setStyleEpoch] = useState(0);
  // 3D terrain toggle (any style — the DEM source is added on demand).
  // Ref mirrors state so the persistent style.load handler can re-apply
  // terrain after setStyle() wipes the DEM source.
  const [is3D, setIs3D] = useState(false);
  const is3DRef = useRef(false);
  // URL camera (deep link) handling. The URL is read ONCE per page load
  // and consumed at map creation — afterwards the ?lat&lng&z in the URL is
  // our own moveend echo, and bounds changes must win over it.
  const pendingUrlCamRef = useRef<UrlCamera | null | undefined>(undefined);
  // True when the constructor already framed the camera (deep link or
  // initial bounds) — lets the fitBounds effect skip its redundant first run.
  const cameraSetAtCreateRef = useRef(false);
  const firstBoundsFitRef = useRef(true);

  // Close the style picker on outside click or Escape
  useEffect(() => {
    if (!showStylePicker) return;
    const onMouseDown = (e: MouseEvent) => {
      if (stylePickerRef.current && !stylePickerRef.current.contains(e.target as Node)) {
        setShowStylePicker(false);
      }
    };
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setShowStylePicker(false);
    };
    document.addEventListener('mousedown', onMouseDown);
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('mousedown', onMouseDown);
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [showStylePicker]);
  const [legendExpanded, setLegendExpanded] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const radarSourceId = 'rainviewer-radar';
  const radarLayerId = 'rainviewer-radar-layer';

  // Note: Style preference is loaded synchronously in the map initialization effect
  // to avoid a flash of wrong style on first render

  // Change map style. Per-style treatment (dark background, hillshade,
  // radar re-add, child remount) happens in the persistent style.load
  // handler registered at map init — one code path for initial load and
  // every switch, reading styleKeyRef so it can never close over a stale
  // key.
  const changeMapStyle = useCallback((styleKey: MapStyleKey) => {
    if (!map.current) return;

    setMapStyle(styleKey);
    styleKeyRef.current = styleKey;
    localStorage.setItem('mapStyle', styleKey);
    setShowStylePicker(false);

    // Use custom style object for satellite, URL for others
    const style = styleKey === 'satellite' ? SATELLITE_STYLE : MAP_STYLES[styleKey].url;
    map.current.setStyle(style);
  }, []);

  // Fetch latest radar timestamp from RainViewer API
  const fetchRadarTimestamp = useCallback(async () => {
    try {
      const response = await fetch('https://api.rainviewer.com/public/weather-maps.json');
      const data: RainViewerResponse = await response.json();
      
      // Get the most recent radar frame
      const latestRadar = data.radar.past[data.radar.past.length - 1];
      if (latestRadar) {
        setRadarTimestamp(latestRadar.path);
      }
    } catch (error) {
      console.warn('Failed to fetch RainViewer data:', error);
    }
  }, []);

  // Add or remove radar layer
  const updateRadarLayer = useCallback(() => {
    if (!map.current || !mapLoaded) return;

    const hasSource = map.current.getSource(radarSourceId) !== undefined;
    const hasLayer = map.current.getLayer(radarLayerId) !== undefined;

    if (weatherEnabled && radarTimestamp) {
      // RainViewer tile URL format
      const tileUrl = `https://tilecache.rainviewer.com${radarTimestamp}/256/{z}/{x}/{y}/2/1_1.png`;

      if (hasSource) {
        // Update existing source
        try {
          (map.current.getSource(radarSourceId) as maplibregl.RasterTileSource).setTiles([tileUrl]);
        } catch {
          // If update fails, remove and re-add
          if (hasLayer) map.current.removeLayer(radarLayerId);
          map.current.removeSource(radarSourceId);
        }
      }

      if (!hasSource) {
        // Add new source
        map.current.addSource(radarSourceId, {
          type: 'raster',
          tiles: [tileUrl],
          tileSize: 256,
          attribution: '<a href="https://www.rainviewer.com/" target="_blank">RainViewer</a>',
        });
      }

      if (!hasLayer) {
        // Overlay slot: above water/land fills (rain is visible over
        // lakes), below roads and every label. Added after the hillshade
        // (style.load), so radar stacks above the relief.
        addLayerAt(
          map.current,
          {
            id: radarLayerId,
            type: 'raster',
            source: radarSourceId,
            paint: {
              'raster-opacity': 0.6,
            },
          },
          ANCHORS.overlays
        );
      }
    } else {
      // Remove radar layer if disabled
      if (hasLayer) {
        map.current.removeLayer(radarLayerId);
      }
      if (hasSource) {
        map.current.removeSource(radarSourceId);
      }
    }
  }, [weatherEnabled, radarTimestamp, mapLoaded]);

  // Toggle weather overlay
  const toggleWeather = useCallback(() => {
    const newValue = !weatherEnabled;
    setWeatherEnabled(newValue);
    onWeatherToggle?.(newValue);
  }, [weatherEnabled, onWeatherToggle]);

  // (Gauge visibility is page state, not map state: the planner's Filters
  // panel owns it and simply doesn't render GaugeStationMarkers when off.)

  // 2D ⇄ 3D terrain. Works on every style: the DEM source is added on
  // demand and terrain survives style switches via the style.load handler.
  const toggle3D = useCallback(() => {
    const m = map.current;
    if (!m) return;
    const next = !is3DRef.current;
    is3DRef.current = next;
    setIs3D(next);
    const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (next) {
      ensureTerrainDem(m);
      m.setTerrain({ source: TERRAIN_DEM_SOURCE_ID, exaggeration: 1.3 });
      if (reducedMotion) m.jumpTo({ pitch: 55 });
      else m.easeTo({ pitch: 55, duration: 700 });
    } else {
      m.setTerrain(null);
      if (reducedMotion) m.jumpTo({ pitch: 0, bearing: 0 });
      else m.easeTo({ pitch: 0, bearing: 0, duration: 700 });
    }
  }, []);

  // Toggle expanded map (CSS-based, stays within browser window)
  const toggleExpanded = useCallback(() => {
    setIsExpanded(prev => {
      const next = !prev;
      // Resize map after layout change
      setTimeout(() => map.current?.resize(), 50);
      return next;
    });
  }, []);

  // Lock body scroll while the map is expanded fullscreen. Doing this in an
  // effect (not the click handler) guarantees the previous overflow is always
  // restored on collapse OR unmount — otherwise navigating away while expanded
  // would leave the whole app unscrollable.
  useEffect(() => {
    if (!isExpanded) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = prev; };
  }, [isExpanded]);

  // Close expanded map on Escape key
  useEffect(() => {
    if (!isExpanded) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') toggleExpanded();
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [isExpanded, toggleExpanded]);

  // Fetch radar data when weather is enabled
  useEffect(() => {
    if (weatherEnabled) {
      fetchRadarTimestamp();
      // Refresh every 5 minutes
      const interval = setInterval(fetchRadarTimestamp, 5 * 60 * 1000);
      return () => clearInterval(interval);
    }
  }, [weatherEnabled, fetchRadarTimestamp]);

  // Update radar layer when state changes — and after every style switch,
  // since setStyle() wipes the radar source/layer without touching the
  // React state this effect otherwise keys on.
  useEffect(() => {
    updateRadarLayer();
  }, [updateRadarLayer, styleEpoch]);

  useEffect(() => {
    if (!mapContainer.current || map.current) return;

    // Get saved style or use Immersive (2D) as default.
    // V4 migration forces the new Immersive default for everyone once (the
    // same one-time reset the V3 key did for Natural); afterwards we respect
    // whatever the user picks.
    const savedStyle = localStorage.getItem('mapStyle') as MapStyleKey | null;
    const migratedV4 = localStorage.getItem('mapStyleMigratedV4');
    let initialStyle: MapStyleKey = 'immersive';

    if (!migratedV4) {
      localStorage.setItem('mapStyleMigratedV4', '1');
      localStorage.setItem('mapStyle', 'immersive');
    } else if (savedStyle && MAP_STYLES[savedStyle]) {
      initialStyle = savedStyle;
    }

    setMapStyle(initialStyle);
    styleKeyRef.current = initialStyle;
    // Use custom style object for satellite, URL for others
    const mapStyleUrl = initialStyle === 'satellite' ? SATELLITE_STYLE : MAP_STYLES[initialStyle].url;

    // Reset mapLoaded when creating a new map instance (important for bounds changes)
    setMapLoaded(false);

    // A valid ?lat&lng&z camera wins over initialBounds on first creation
    // only (see pendingUrlCamRef above).
    if (pendingUrlCamRef.current === undefined) {
      pendingUrlCamRef.current = syncCameraToUrl ? readCameraFromUrl() : null;
    }
    const urlCam = pendingUrlCamRef.current;

    // Initialize map
    map.current = new maplibregl.Map({
      container: mapContainer.current,
      style: mapStyleUrl,
      cooperativeGestures: cooperativeGestures,
      attributionControl: false,
      center: urlCam
        ? [urlCam.lng, urlCam.lat]
        : initialBounds
        ? [
            (initialBounds[0] + initialBounds[2]) / 2,
            (initialBounds[1] + initialBounds[3]) / 2,
          ]
        : [-91.5, 37.8], // Center of Missouri
      zoom: urlCam ? urlCam.z : initialBounds ? 8 : 7,
      bounds: !urlCam && initialBounds
        ? new maplibregl.LngLatBounds(
            [initialBounds[0], initialBounds[1]],
            [initialBounds[2], initialBounds[3]]
          )
        : undefined,
      fitBoundsOptions: {
        padding: 50,
      },
    });
    cameraSetAtCreateRef.current = Boolean(urlCam || initialBounds);
    if (urlCam) {
      pendingUrlCamRef.current = null; // consumed
    }

    // Mirror the camera into the URL after every settled movement (pan,
    // zoom, fitBounds), replaceState so history doesn't stack per pan.
    if (syncCameraToUrl) {
      map.current.on('moveend', () => {
        if (!map.current) return;
        const c = map.current.getCenter();
        const url = new URL(window.location.href);
        url.searchParams.set('lat', c.lat.toFixed(5));
        url.searchParams.set('lng', c.lng.toFixed(5));
        url.searchParams.set('z', map.current.getZoom().toFixed(2));
        window.history.replaceState(window.history.state, '', url);
      });
    }
    
    // Persistent per-style treatment — fires on the initial load AND every
    // setStyle() switch (styleKeyRef, not a captured key, so it never goes
    // stale). Dark background for dark styles; shaded relief on the curated
    // Natural style only (imagery styles carry their own light/shadow);
    // 3D terrain re-applied if toggled on (setStyle wiped its DEM source);
    // epoch bump remounts child layers that setStyle just wiped.
    map.current.on('style.load', () => {
      if (!map.current) return;
      if (MAP_STYLES[styleKeyRef.current].dark && styleKeyRef.current !== 'immersive') {
        try {
          map.current.setPaintProperty('background', 'background-color', '#0f132f');
        } catch (error) {
          // Background layer might not exist in all styles
          console.warn('Could not set background color:', error);
        }
      }
      if (styleKeyRef.current === 'liberty') {
        ensureHillshade(map.current);
      }
      if (is3DRef.current) {
        ensureTerrainDem(map.current);
        map.current.setTerrain({ source: TERRAIN_DEM_SOURCE_ID, exaggeration: 1.3 });
      }
      setStyleEpoch((e) => e + 1);
    });

    // Handle missing images (suppress warnings for style images)
    map.current.on('styleimagemissing', (e: maplibregl.MapStyleImageMissingEvent) => {
      // Suppress warnings for missing style images (like us-interstate_6)
      // These are typically from the map style and don't affect functionality
      console.debug('Map style image missing:', e.id);
    });

    // Add navigation controls — desktop only. On touch screens pinch/rotate
    // covers zoom, and the three-button stack eats scarce map height.
    if (window.matchMedia('(min-width: 768px)').matches) {
      map.current.addControl(new maplibregl.NavigationControl(), 'top-right');
    }

    // Move attribution to bottom-left so it doesn't cover access points
    map.current.addControl(new maplibregl.AttributionControl({ compact: true }), 'bottom-left');

    map.current.on('load', () => {
      setMapLoaded(true);

      // MapLibre auto-expands the compact attribution the first time it populates
      // (on style load), and only re-collapses on a drag. Force it minimized here
      // so it starts as just the (i); the toggle button still expands it on click.
      const attribEl = mapContainer.current?.querySelector('.maplibregl-ctrl-attrib');
      if (attribEl) {
        attribEl.classList.remove('maplibregl-compact-show');
        attribEl.removeAttribute('open');
      }
    });

    // Cleanup
    return () => {
      if (map.current) {
        map.current.remove();
        map.current = null;
      }
    };
    // Create the map ONCE per component mount. This effect was previously
    // keyed on initialBounds, so switching rivers in the planner tore down
    // and rebuilt the entire MapLibre instance — style re-fetch/re-parse
    // and every tile re-requested on each switch. Bounds changes are eased
    // by the fitBounds effect below instead; cooperativeGestures and
    // syncCameraToUrl are create-time constants on every surface that
    // renders this component.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!map.current || !initialBounds) return;

    // Skip the one fit the constructor already performed: at mount the map
    // is created framed to these same bounds (or to a deep-linked ?lat&lng&z
    // camera, which must win over the bounds). Every later bounds change
    // (picking a different river) eases to the new framing.
    if (firstBoundsFitRef.current) {
      firstBoundsFitRef.current = false;
      if (cameraSetAtCreateRef.current) return;
    }

    const bounds = new maplibregl.LngLatBounds(
      [initialBounds[0], initialBounds[1]],
      [initialBounds[2], initialBounds[3]]
    );

    if (!map.current.loaded()) {
      const handleLoad = () => {
        map.current?.fitBounds(bounds, { padding: 50, duration: 800 });
      };
      map.current.once('load', handleLoad);
      return () => {
        map.current?.off('load', handleLoad);
      };
    }

    map.current.fitBounds(bounds, { padding: 50, duration: 800 });
  }, [initialBounds]);

  return (
    // `isolate` gives the map its own stacking context so its internal DOM
    // markers (inline z-index up to 10) and popups can't escape upward to
    // paint over sibling chrome — notably the AccessPointStrip cards, which
    // otherwise sat *behind* the markers because a bare `relative` parent is
    // not a stacking context.
    <div className={`isolate ${isExpanded ? 'fixed inset-0 z-50 bg-black' : 'relative w-full h-full min-h-[400px]'}`} role="region" aria-label="Interactive river map">
      <div
        ref={mapContainer}
        className="w-full h-full"
        style={{ pointerEvents: 'auto', minHeight: isExpanded ? undefined : '400px' }}
      />
      {mapLoaded && map.current && (
        // Keyed by styleEpoch: setStyle() destroys all custom layers, so a
        // style switch remounts the children and they re-add themselves.
        <MapProvider key={styleEpoch} map={map.current}>{children}</MapProvider>
      )}
      {!mapLoaded && (
        <div className="absolute inset-0 flex items-center justify-center bg-neutral-100/60 pointer-events-none" role="status" aria-label="Loading map">
          <div className="w-10 h-10 border-3 border-primary-200 border-t-primary-600 rounded-full animate-spin" />
        </div>
      )}

      {/* Map Controls - right side. On mobile there is no NavigationControl,
          so the column starts near the top; on desktop it sits below the
          MapLibre zoom/compass stack. */}
      {/* z-10 normally, but lifted above the z-20 hint/stats overlays while
          the layers menu is open — the column is a stacking context, so an
          inner z-50 alone can never escape it. */}
      <div className={`absolute top-2.5 md:top-[120px] right-2.5 flex flex-col gap-3 md:gap-2 ${showStylePicker ? 'z-30' : 'z-10'}`}>
        {/* Layers menu: map style everywhere; on mobile it also carries the
            weather-radar and gauge toggles so the map edge shows ONE button
            instead of three. */}
        <div ref={stylePickerRef} className={`relative ${showStylePicker ? 'z-50' : ''}`}>
          <button
            onClick={() => setShowStylePicker(!showStylePicker)}
            className={`p-2.5 md:p-2 rounded-lg shadow-lg transition-all ${
              showStylePicker
                ? 'bg-primary-500 text-white'
                : 'bg-white/90 text-gray-700 hover:bg-white'
            }`}
            title="Map layers"
            aria-label="Map layers"
            aria-expanded={showStylePicker}
          >
            <Layers className="w-5 h-5" />
          </button>

          {showStylePicker && (
            <div className="absolute top-full right-0 mt-2 bg-white/95 backdrop-blur-md rounded-lg shadow-lg border border-gray-200 overflow-hidden min-w-[150px] z-50">
              {(Object.keys(MAP_STYLES) as MapStyleKey[]).map((key) => (
                <button
                  key={key}
                  onClick={() => changeMapStyle(key)}
                  className={`w-full px-4 py-2.5 md:py-2 text-left text-sm hover:bg-gray-100 transition-colors ${
                    mapStyle === key ? 'bg-primary-50 text-primary-600 font-medium' : 'text-gray-700'
                  }`}
                >
                  {MAP_STYLES[key].name}
                </button>
              ))}

              {/* Mobile-only overlay toggles (desktop keeps dedicated buttons).
                  Deliberately does NOT close the menu, so both can be toggled
                  in one visit. */}
              <div className="md:hidden border-t border-gray-200">
                <button
                  onClick={toggleWeather}
                  className="w-full px-4 py-2.5 text-left text-sm hover:bg-gray-100 transition-colors flex items-center justify-between gap-3 text-gray-700"
                  aria-pressed={weatherEnabled}
                >
                  <span>Weather radar</span>
                  <span className={`w-2 h-2 rounded-full ${weatherEnabled ? 'bg-primary-500' : 'bg-gray-300'}`} aria-hidden="true" />
                </button>
                <button
                  onClick={toggle3D}
                  className="w-full px-4 py-2.5 text-left text-sm hover:bg-gray-100 transition-colors flex items-center justify-between gap-3 text-gray-700"
                  aria-pressed={is3D}
                >
                  <span>3D terrain</span>
                  <span className={`w-2 h-2 rounded-full ${is3D ? 'bg-primary-500' : 'bg-gray-300'}`} aria-hidden="true" />
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Weather Overlay Toggle - desktop only (mobile: inside Layers menu) */}
        <button
          onClick={toggleWeather}
          className={`hidden md:block p-2.5 md:p-2 rounded-lg shadow-lg transition-all ${
            weatherEnabled
              ? 'bg-primary-500 text-white'
              : 'bg-white/90 text-gray-700 hover:bg-white'
          }`}
          title={weatherEnabled ? 'Hide weather radar' : 'Show weather radar'}
          aria-label={weatherEnabled ? 'Hide weather radar' : 'Show weather radar'}
        >
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z"
            />
          </svg>
        </button>

        {/* 2D/3D terrain toggle - desktop only (mobile: inside Layers menu) */}
        <button
          onClick={toggle3D}
          className={`hidden md:block p-2.5 md:p-2 rounded-lg shadow-lg transition-all text-sm font-bold leading-5 ${
            is3D
              ? 'bg-primary-500 text-white'
              : 'bg-white/90 text-gray-700 hover:bg-white'
          }`}
          title={is3D ? 'Back to flat map' : 'Tilt into 3D terrain'}
          aria-label={is3D ? 'Switch to 2D map' : 'Switch to 3D terrain'}
          aria-pressed={is3D}
        >
          <span className="block w-5 h-5 text-center">{is3D ? '2D' : '3D'}</span>
        </button>

        {/* Expand/Collapse Toggle — lives in the column on all breakpoints so
            the bottom-right corner stays free for the legend/attribution and
            the access-point strip. */}
        <button
          onClick={toggleExpanded}
          className="p-2.5 md:p-2 rounded-lg shadow-lg transition-all bg-white/90 text-gray-700 hover:bg-white"
          title={isExpanded ? 'Collapse map' : 'Expand map'}
          aria-label={isExpanded ? 'Collapse map' : 'Expand map'}
        >
          {isExpanded ? <Minimize2 className="w-5 h-5" /> : <Maximize2 className="w-5 h-5" />}
        </button>
      </div>

      {/* Weather Attribution */}
      {weatherEnabled && (
        <div className="absolute bottom-1 left-1 z-10 text-xs text-white/60 bg-black/30 px-1 rounded">
          Radar: <a href="https://www.rainviewer.com/" target="_blank" rel="noopener noreferrer" className="underline">RainViewer</a>
        </div>
      )}

      {/* Collapsible Map Legend - default minimized */}
      {showLegend && (
        <div className="absolute bottom-2 right-2 z-10 rounded-xl border-2 border-neutral-700 bg-neutral-900/95 text-xs text-white shadow-xl">
          <button
            onClick={() => setLegendExpanded(!legendExpanded)}
            className="flex items-center gap-2 px-3 py-2 w-full hover:bg-white/10 transition-colors rounded-xl"
          >
            <svg
              className={`w-3 h-3 transition-transform ${legendExpanded ? 'rotate-180' : ''}`}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
            </svg>
            <span className="text-[11px] font-semibold text-white">Legend</span>
          </button>
          {legendExpanded && (
            <div className="flex flex-col gap-1.5 px-3 pb-2.5 pt-1 border-t border-neutral-700">
              <LegendItem color="#478559" label="Put-in" />
              <LegendItem color="#f95d9b" label="Take-out" />
              <LegendItem color="#c7b8a6" label="Access point" />
              {legendRoute && (
                <>
                  <LegendItem color="#22c55e" label="Route (downstream)" />
                  <LegendItem color="#ef4444" label="Route (upstream)" />
                </>
              )}
              <div className="mt-1 pt-1.5 border-t border-neutral-700">
                <span className="text-[10px] font-semibold uppercase tracking-wider text-neutral-400">
                  Conditions
                </span>
                <div className="flex flex-col gap-1.5 mt-1.5">
                  {CONDITION_ORDER.map((code) => (
                    <LegendItem
                      key={code}
                      color={conditionColor(code)}
                      label={CONDITION_SHORT_LABELS[code]}
                    />
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function LegendItem({ color, label }: { color: string; label: string }) {
  return (
    <div className="flex items-center gap-2">
      <span
        className="inline-flex h-3 w-3 rounded-full border border-white/20"
        style={{ backgroundColor: color }}
        aria-hidden="true"
      />
      <span className="text-[11px] text-white">{label}</span>
    </div>
  );
}

// Context to share map instance with child components
import { createContext, useContext } from 'react';

const MapContext = createContext<maplibregl.Map | null>(null);

export function useMap() {
  const map = useContext(MapContext);
  if (!map) {
    throw new Error('useMap must be used within MapContainer');
  }
  return map;
}

// Wrapper component that provides map context
export function MapProvider({
  map,
  children,
}: {
  map: maplibregl.Map | null;
  children: React.ReactNode;
}) {
  return (
    <MapContext.Provider value={map}>{children}</MapContext.Provider>
  );
}
