// src/app/rivers/[slug]/layout.tsx
// Layout for river detail pages
// Exports generateMetadata for dynamic social media preview tags
// OG images are auto-generated by opengraph-image.tsx in this directory

import type { Metadata } from 'next';
import { createClient } from '@/lib/supabase/server';

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://eddy.guide';

// Force dynamic rendering - this page fetches live data from Supabase
export const dynamic = 'force-dynamic';

interface RiverLayoutProps {
  children: React.ReactNode;
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: RiverLayoutProps): Promise<Metadata> {
  try {
    const resolvedParams = await params;
    const slug = resolvedParams?.slug;

    if (!slug) {
      return {
        title: 'River',
        description: 'Plan your float trip on Missouri rivers.',
      };
    }

    const supabase = await createClient();

    // Fetch river basic info
    const { data: river, error: riverError } = await supabase
      .from('rivers')
      .select('id, name, slug, length_miles, description, difficulty_rating, region')
      .eq('slug', slug)
      .single();

    if (riverError || !river) {
      return {
        title: 'River Not Found',
      };
    }

    // Fetch current conditions for the river (non-critical - gracefully degrade)
    let conditionCode = 'unknown';

    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: conditionData } = await (supabase.rpc as any)('get_river_condition', {
        p_river_id: river.id,
      });

      if (conditionData && conditionData.length > 0) {
        conditionCode = conditionData[0].condition_code || 'unknown';
      }
    } catch (condError) {
      console.warn('Failed to fetch conditions for river metadata:', condError);
    }

    const conditionLabels: Record<string, string> = {
      optimal: 'Optimal',
      okay: 'Low - Floatable',
      low: 'Very Low',
      high: 'High Water',
      too_low: 'Too Low',
      dangerous: 'Dangerous',
      unknown: '',
    };

    const conditionText = conditionLabels[conditionCode] || '';
    const lengthMiles = river.length_miles ? parseFloat(river.length_miles).toFixed(1) : '';

    // Page title — includes condition for SEO / browser tab
    const title = conditionText
      ? `${river.name} — ${conditionText}`
      : river.name;

    // OG title — concise, under 60 chars for Facebook
    const ogTitle = `${river.name} | Live Conditions & Float Guide`;

    // Build a compelling description under ~155 chars for Facebook
    const descParts: string[] = [];
    if (conditionText) descParts.push(`Currently ${conditionText.toLowerCase()}.`);
    if (lengthMiles) descParts.push(`${lengthMiles} mi`);
    if (river.difficulty_rating) descParts.push(river.difficulty_rating);
    if (river.region) descParts.push(river.region);
    const descMeta = descParts.length > 1
      ? descParts.slice(0, 1).join('') + ' ' + descParts.slice(1).join(', ') + '.'
      : descParts.join(', ') + '.';
    const description = `${descMeta} Access points, float times, gauge data & weather for ${river.name}.`;

    const pageUrl = `${BASE_URL}/rivers/${slug}`;

    return {
      title,
      description,
      openGraph: {
        type: 'website',
        title: ogTitle,
        description,
        url: pageUrl,
        siteName: 'Eddy',
        // OG image is auto-discovered from opengraph-image.tsx
      },
      twitter: {
        card: 'summary_large_image',
        title: ogTitle,
        description,
        // Twitter image is auto-discovered from twitter-image.tsx
      },
    };
  } catch (error) {
    console.error('Error generating river metadata:', error);
    return {
      title: 'River',
      description: 'Plan your float trip on Missouri rivers.',
      openGraph: {
        type: 'website',
        title: 'River | Eddy',
        description: 'Plan your float trip on Missouri rivers.',
        siteName: 'Eddy',
      },
      twitter: {
        card: 'summary_large_image',
        title: 'River | Eddy',
        description: 'Plan your float trip on Missouri rivers.',
      },
    };
  }
}

export default function RiverLayout({ children }: RiverLayoutProps) {
  return children;
}
