// src/app/rivers/[slug]/layout.tsx
// Layout for river detail pages
// Exports generateMetadata for dynamic social media preview tags
// OG images are auto-generated by opengraph-image.tsx in this directory

import type { Metadata } from 'next';
import { createClient } from '@/lib/supabase/server';

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://eddy.guide';

// Force dynamic rendering - this page fetches live data from Supabase
export const dynamic = 'force-dynamic';

interface RiverLayoutProps {
  children: React.ReactNode;
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: RiverLayoutProps): Promise<Metadata> {
  try {
    const resolvedParams = await params;
    const slug = resolvedParams?.slug;

    if (!slug) {
      return {
        title: 'River',
        description: 'Plan your float trip on Missouri rivers.',
      };
    }

    const supabase = await createClient();

    // Fetch river basic info
    const { data: river, error: riverError } = await supabase
      .from('rivers')
      .select('id, name, slug, length_miles, description, difficulty_rating, region')
      .eq('slug', slug)
      .single();

    if (riverError || !river) {
      return {
        title: 'River Not Found',
      };
    }

    // Fetch current conditions for the river (non-critical - gracefully degrade)
    let conditionCode = 'unknown';

    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: conditionData } = await (supabase.rpc as any)('get_river_condition', {
        p_river_id: river.id,
      });

      if (conditionData && conditionData.length > 0) {
        conditionCode = conditionData[0].condition_code || 'unknown';
      }
    } catch (condError) {
      console.warn('Failed to fetch conditions for river metadata:', condError);
    }

    const conditionLabels: Record<string, string> = {
      optimal: 'Optimal',
      okay: 'Low - Floatable',
      low: 'Very Low',
      high: 'High Water',
      too_low: 'Too Low',
      dangerous: 'Dangerous',
      unknown: '',
    };

    const conditionText = conditionLabels[conditionCode] || '';
    const conditionSuffix = conditionText ? ` - ${conditionText}` : '';
    const lengthMiles = river.length_miles ? parseFloat(river.length_miles).toFixed(1) : '';

    const title = `${river.name}${conditionSuffix}`;
    const description = `${river.name} float trip info${conditionText ? `: Currently ${conditionText.toLowerCase()}` : ''}. ${lengthMiles ? `${lengthMiles} miles` : ''}${river.difficulty_rating ? `, ${river.difficulty_rating}` : ''}${river.region ? ` in ${river.region}` : ''}. Real-time water conditions, access points, float times, and weather.`;
    const pageUrl = `${BASE_URL}/rivers/${slug}`;

    return {
      title,
      description,
      openGraph: {
        type: 'website',
        title: `${river.name} - Float Trip Conditions & Info`,
        description,
        url: pageUrl,
        siteName: 'Eddy',
        // OG image is auto-discovered from opengraph-image.tsx
      },
      twitter: {
        card: 'summary_large_image',
        title: `${river.name}${conditionSuffix}`,
        description,
        // Twitter image is auto-discovered from twitter-image.tsx
      },
    };
  } catch (error) {
    console.error('Error generating river metadata:', error);
    return {
      title: 'River',
      description: 'Plan your float trip on Missouri rivers.',
      openGraph: {
        type: 'website',
        title: 'River | Eddy',
        description: 'Plan your float trip on Missouri rivers.',
        siteName: 'Eddy',
      },
      twitter: {
        card: 'summary_large_image',
        title: 'River | Eddy',
        description: 'Plan your float trip on Missouri rivers.',
      },
    };
  }
}

export default function RiverLayout({ children }: RiverLayoutProps) {
  return children;
}
