'use client';

// Pure SVG implementation of the Missouri Surface Water map.
//
// We deliberately do NOT use MapLibre / vector tiles / glyph PBFs / sprites
// here. Real Supabase geometry is projected from WGS84 into a 1600x1000 SVG
// viewBox via a simple Albers-like equal-area projection centered on
// Missouri. This sidesteps the entire CSP/glyph/style-validation surface
// MapLibre brings, and matches the Claude Design reference visually.
//
// Particles ride along the rendered <path> elements using
// getTotalLength() + getPointAtLength(), the same trick the design uses.

import { useRef, useMemo, useState, useCallback, useEffect } from 'react';
import {
  STAGE_VERDICTS,
  condKey,
  type MORiver,
  type MOCampground,
  type StageVerdict,
} from '@/lib/usgs/mo-statewide-data';
import type { MoStatewideGauge } from '@/app/api/usgs/mo-statewide/route';
import type { MoContextSite } from '@/lib/usgs/mo-sites';
import { getEddyImageForCondition } from '@/constants';
import moOutline from '@/data/mo-outline.json';
import moBasemap from '@/data/mo-rivers-basemap.json';
import {
  W,
  H,
  buildProjector,
  lineToPath,
  polygonToPath,
  bboxOf,
} from './projection';
import { usePrefersReducedMotion } from './fx';
import FlowLayer, { type FlowRiver } from './FlowLayer';
import Stars from './Stars';

type BasemapRiver = {
  type: 'Feature';
  properties: { name: string; length_mi: number };
  geometry: { type: 'LineString'; coordinates: number[][] };
};
type BasemapLake = {
  type: 'Feature';
  properties: { name: string; area_sqkm: number };
  geometry: { type: 'Polygon' | 'MultiPolygon'; coordinates: number[][][] | number[][][][] };
};
const BASEMAP_RIVERS = (moBasemap.rivers?.features ?? []) as BasemapRiver[];
const BASEMAP_LAKES = (moBasemap.lakes?.features ?? []) as BasemapLake[];

// ─── Projection ─────────────────────────────────────────────────────────
//
// Shared with the hero backdrop via ./projection — the viewBox is fixed at
// 1600×1000 and the projection window locks to the state outline below.

// ─── Static geometry ────────────────────────────────────────────────────

// Real TIGER/Line state boundary, simplified to ~150 vertices via Douglas-
// Peucker. Generated by `scripts/build-mo-outline.ts` from the topojson/
// us-atlas states-10m artifact (Census Cartographic Boundary cb_2023).
const MO_OUTLINE: Array<[number, number]> = (moOutline.coordinates[0] as Array<
  [number, number]
>);

const CITIES: Array<{ name: string; lon: number; lat: number; type: 'metro' | 'city' }> = [
  { name: 'Kansas City',   lon: -94.578, lat: 39.099, type: 'metro' },
  { name: 'St. Louis',     lon: -90.199, lat: 38.627, type: 'metro' },
  { name: 'Springfield',   lon: -93.298, lat: 37.209, type: 'metro' },
  { name: 'Columbia',      lon: -92.334, lat: 38.952, type: 'metro' },
  { name: 'Jefferson City',lon: -92.173, lat: 38.577, type: 'city'  },
  { name: 'Cape Girardeau',lon: -89.518, lat: 37.306, type: 'city'  },
  { name: 'Joplin',        lon: -94.513, lat: 37.084, type: 'city'  },
];

// ─── Component ──────────────────────────────────────────────────────────

interface MOMapProps {
  rivers: MORiver[];
  campgrounds: MOCampground[];
  gauges: MoStatewideGauge[];
  verdictByRiver: Record<string, StageVerdict>;
  /** Condition code keyed by `${river_id}::${site_id}` (condKey) — drives
   *  per-segment coloring. Keyed per river, not per site, so a gauge shared
   *  by two rivers classifies independently against each river's thresholds. */
  conditionByGauge: Record<string, StageVerdict>;
  percentileByGauge: Record<string, number | null>;
  hoveredRiverId: string | null;
  focusedRiverId: string | null;
  hoveredGaugeId: string | null;
  focusedGaugeId: string | null;
  showCampgrounds: boolean;
  showAccessPoints: boolean;
  showPOIs: boolean;
  showGauges: boolean;
  /** Baked hillshade relief layer. Defaults on; toggled from the HUD. */
  showTerrain?: boolean;
  /** Animated particle flow layer along the curated rivers. */
  showFlow?: boolean;
  /** Statewide context sites (neutral, no condition rating). */
  contextSites?: MoContextSite[];
  showSites?: boolean;
  selectedContextSiteId?: string | null;
  onClickContextSite?: (site: MoContextSite | null) => void;
  /** True when the right rail is pinned open — the zoom cluster slides
   *  left so it never hides underneath the rail. */
  railOpen?: boolean;
  onHoverRiver: (id: string | null) => void;
  onFocusRiver: (id: string | null) => void;
  onHoverGauge: (id: string | null, screenPos?: { x: number; y: number } | null) => void;
  onFocusGauge: (id: string | null) => void;
  onClickCampground: (id: string | null) => void;
  onClickAccessPoint: (id: string | null) => void;
  onClickPoi: (id: string | null) => void;
}

const POI_TONES: Record<string, string> = {
  spring: '#1D525F',
  cave: '#3D3425',
  historical_site: '#7A684B',
  scenic_viewpoint: '#347A47',
  waterfall: '#256574',
  geological: '#5C4E38',
  other: '#524D43',
};

function strokeWidthForRiver(
  lengthMiles: number | null | undefined,
  hovered: boolean,
  focused: boolean,
): number {
  // Curated rivers sit on top of the basemap network; keep them visible but
  // not so heavy they read as the only rivers in the state.
  const m = lengthMiles ?? 60;
  const base = Math.max(2.6, Math.min(4.8, 2.2 + m / 60));
  if (focused) return base + 2.4;
  if (hovered) return base + 1.4;
  return base;
}

// Discharge → node radius (viewBox units). Sqrt scale so area tracks
// flow magnitude; clamped so the Mississippi doesn't eat the map.
function magnitudeR(cfs: number | null | undefined, base: number, span: number): number {
  if (cfs == null || cfs <= 0) return base;
  return base + Math.min(1, Math.sqrt(cfs) / Math.sqrt(60000)) * span;
}

// Ray-cast point-in-polygon against the state outline — context sites
// arrive bbox-filtered (includes slivers of neighboring states); only
// in-state sites render on a Missouri map.
function insideMissouri(lon: number, lat: number): boolean {
  let inside = false;
  const n = MO_OUTLINE.length;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const [xi, yi] = MO_OUTLINE[i];
    const [xj, yj] = MO_OUTLINE[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

// Round a raw distance down to a tidy 1/2/5 × 10ⁿ value for the scale bar.
function niceDistance(km: number): number {
  if (km <= 0) return 1;
  const pow = Math.pow(10, Math.floor(Math.log10(km)));
  const f = km / pow;
  const nice = f >= 5 ? 5 : f >= 2 ? 2 : 1;
  return nice * pow;
}

function strokeWidthForBasemapRiver(lengthMi: number): number {
  // Length-weighted strokes for the NHD basemap network. The previous
  // ramp made small named tributaries (e.g. Jacks Fork at 46 mi) render
  // at 0.7 viewBox-units, which is sub-pixel at full state framing and
  // visually disappears. Bumped across the board so the basemap reads
  // as a real river map at all zoom levels.
  if (lengthMi >= 200) return 2.4;
  if (lengthMi >= 100) return 1.8;
  if (lengthMi >= 50) return 1.4;
  return 1.0;
}

export default function MOMap(props: MOMapProps) {
  const reducedMotion = usePrefersReducedMotion();
  // Lock the projection window to the full Missouri state outline so the
  // map always reads as "Missouri", no matter what data subset is loaded.
  // Earlier we framed to the data bbox, which caused the southern half of
  // the state to fill the canvas and the visual to drift as data changed.
  // Tight padding — the state outline already has visual breathing room.
  const bbox = useMemo(() => bboxOf(MO_OUTLINE, 0.02), []);

  const project = useMemo(() => buildProjector(bbox), [bbox]);

  const stateOutlinePath = useMemo(
    () => polygonToPath(MO_OUTLINE, project),
    [project],
  );
  // Projected anchor for the Ozark highland tint (southern plateau).
  // Kilometres represented by one viewBox unit — drives the scale bar.
  const kmPerUnit = useMemo(() => {
    const [x0] = project(-92, 38);
    const [x1] = project(-91, 38);
    const dxUnits = Math.abs(x1 - x0) || 1;
    return (111.32 * Math.cos((38 * Math.PI) / 180)) / dxUnits;
  }, [project]);
  const riverPaths = useMemo(() => {
    const out: Record<string, string> = {};
    for (const r of props.rivers) {
      out[r.id] = lineToPath(r.geometry.coordinates as Array<[number, number]>, project);
    }
    return out;
  }, [props.rivers, project]);

  // Per-river gradient stops along each curated river. Replaces the
  // hard-edged per-segment palette with a single SVG <linearGradient>
  // whose stops sit at each gauge's projected position along the line —
  // so adjacent gauges' colors fade smoothly into each other instead of
  // flipping at midpoints.
  //
  // Output: { [riverId]: { x1,y1,x2,y2, stops: Array<{ offset, color, condition, siteId }> } }
  // The gradient direction is the straight line from the river's first
  // projected vertex to its last. For mostly-N-S or mostly-E-W rivers
  // (which is most of MO) this tracks the flow direction. Hard-curving
  // rivers will paint with some color drift relative to local flow, but
  // the smooth fade reads cleanly regardless.
  const riverGradients = useMemo(() => {
    const out: Record<
      string,
      {
        x1: number; y1: number; x2: number; y2: number;
        stops: Array<{ offset: number; color: string; condition: StageVerdict; siteId: string }>;
      }
    > = {};
    for (const r of props.rivers) {
      const coords = r.geometry.coordinates as Array<[number, number]>;
      if (coords.length < 2) continue;
      const first = project(coords[0][0], coords[0][1]);
      const last = project(coords[coords.length - 1][0], coords[coords.length - 1][1]);
      const dx = last[0] - first[0];
      const dy = last[1] - first[1];
      const lenSq = dx * dx + dy * dy;
      if (lenSq < 1) continue; // degenerate

      const gs = (r.gauges ?? [])
        .filter((g) => props.conditionByGauge[condKey(r.id, g.site_id)])
        .map((g) => {
          const [gx, gy] = project(g.lon, g.lat);
          // Project (gx,gy) onto the (first,last) gradient line; t in [0,1].
          const t = ((gx - first[0]) * dx + (gy - first[1]) * dy) / lenSq;
          return {
            siteId: g.site_id,
            condition: props.conditionByGauge[condKey(r.id, g.site_id)],
            offset: Math.max(0, Math.min(1, t)),
          };
        })
        .sort((a, b) => a.offset - b.offset);
      if (!gs.length) continue;

      // Build stops. SVG interpolates linearly between stops, so
      // adjacent gauges fade smoothly. We extend the first/last stops
      // to offsets 0 and 1 so the river ends paint in their nearest
      // gauge's color rather than gradient-default.
      const stops: Array<{ offset: number; color: string; condition: StageVerdict; siteId: string }> = [];
      const firstColor = STAGE_VERDICTS[gs[0].condition].color;
      const lastColor = STAGE_VERDICTS[gs[gs.length - 1].condition].color;
      if (gs[0].offset > 0.001) {
        stops.push({ offset: 0, color: firstColor, condition: gs[0].condition, siteId: gs[0].siteId });
      }
      for (const g of gs) {
        stops.push({ offset: g.offset, color: STAGE_VERDICTS[g.condition].color, condition: g.condition, siteId: g.siteId });
      }
      if (gs[gs.length - 1].offset < 0.999) {
        stops.push({ offset: 1, color: lastColor, condition: gs[gs.length - 1].condition, siteId: gs[gs.length - 1].siteId });
      }

      out[r.id] = { x1: first[0], y1: first[1], x2: last[0], y2: last[1], stops };
    }
    return out;
  }, [props.rivers, props.conditionByGauge, project]);

  // Basemap rivers — pre-projected once per `project` change, sorted by
  // length so longer rivers paint underneath shorter ones (so the smaller
  // tributaries don't get covered up).
  const basemapRiverPaths = useMemo(() => {
    return BASEMAP_RIVERS
      .map((f) => ({
        name: f.properties.name,
        lengthMi: f.properties.length_mi,
        d: lineToPath(f.geometry.coordinates as Array<[number, number]>, project),
      }))
      .filter((r) => r.d.length > 0)
      .sort((a, b) => b.lengthMi - a.lengthMi);
  }, [project]);

  // Basemap lakes — flatten Polygon and MultiPolygon outer rings into
  // individual SVG path strings. Holes (inner rings) are ignored at this
  // simplification level; reservoir holes don't render meaningfully here.
  const basemapLakePaths = useMemo(() => {
    const out: Array<{ name: string; d: string }> = [];
    for (const f of BASEMAP_LAKES) {
      const rings: Array<Array<[number, number]>> = [];
      if (f.geometry.type === 'Polygon') {
        const outer = (f.geometry.coordinates as number[][][])[0];
        if (outer) rings.push(outer as Array<[number, number]>);
      } else {
        for (const poly of f.geometry.coordinates as number[][][][]) {
          if (poly[0]) rings.push(poly[0] as Array<[number, number]>);
        }
      }
      const d = rings.map((r) => polygonToPath(r, project)).join(' ');
      if (d) out.push({ name: f.properties.name, d });
    }
    return out;
  }, [project]);

  // Context sites — projected once, filtered to in-state points. These
  // are NEUTRAL: location, magnitude (size), and freshness (opacity)
  // only. No condition color — they carry no curated thresholds.
  const contextNodes = useMemo(() => {
    const sites = props.contextSites ?? [];
    const out: Array<{
      site: MoContextSite;
      x: number;
      y: number;
      r: number;
      fresh: boolean;
    }> = [];
    const staleCutoff = Date.now() - 2 * 3600e3;
    for (const s of sites) {
      if (!insideMissouri(s.lon, s.lat)) continue;
      const [x, y] = project(s.lon, s.lat);
      out.push({
        site: s,
        x,
        y,
        // Smaller than any curated gauge chip so the two classes read
        // apart in a static screenshot, not just on hover.
        r: magnitudeR(s.dischargeCfs, 1.4, 4.2),
        fresh: s.readingTimestamp != null && Date.parse(s.readingTimestamp) > staleCutoff,
      });
    }
    return out;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.contextSites, project]);

  // Cities visible in the framed area (plus a small buffer outside, so the
  // nearest metro still anchors the user's orientation).
  const visibleCities = useMemo(() => {
    const lonBuf = (bbox.maxLon - bbox.minLon) * 0.18;
    const latBuf = (bbox.maxLat - bbox.minLat) * 0.18;
    return CITIES.filter(
      (c) =>
        c.lon >= bbox.minLon - lonBuf &&
        c.lon <= bbox.maxLon + lonBuf &&
        c.lat >= bbox.minLat - latBuf &&
        c.lat <= bbox.maxLat + latBuf,
    );
  }, [bbox]);

  // ─── Zoom + pan ────────────────────────────────────────────────────────
  // The SVG viewBox is state. Wheel zooms around the cursor; primary-button
  // drag pans; double-click resets to the full-state framing. Children
  // never re-project (paths are memoized on `project`); only the viewBox
  // attribute changes per frame, so the browser handles zoom natively.
  const HOME_VIEW = useMemo(() => ({ x: 0, y: 0, w: W, h: H }), []);
  // High-altitude framing for the cinematic entry — the widest the clamp
  // allows, biased slightly up so the state "rises" into place.
  const ENTRY_VIEW = useMemo(() => {
    const w = W * 1.4;
    const h = w * (H / W);
    return { x: (W - w) / 2, y: (H - h) / 2 - H * 0.06, w, h };
  }, []);
  const entryEligible =
    !reducedMotion &&
    typeof window !== 'undefined' &&
    window.sessionStorage?.getItem('mosw-entry-played') !== '1';
  const [view, setView] = useState(entryEligible ? ENTRY_VIEW : HOME_VIEW);
  // 'flying' → camera en route (interaction blocked, layers fading up);
  // 'done' → composed end state. Reduced motion starts at 'done'.
  const [entryPhase, setEntryPhase] = useState<'flying' | 'done'>(
    entryEligible ? 'flying' : 'done',
  );
  const dragRef = useRef<
    | {
        pointerId: number;
        startClientX: number;
        startClientY: number;
        startViewX: number;
        startViewY: number;
        moved: boolean;
        captured: boolean;
      }
    | null
  >(null);

  const clampView = useCallback(
    (v: { x: number; y: number; w: number; h: number }) => {
      // Cap zoom: 12x in (so individual rivers are readable) and 1.4x out
      // (so the user can't drift into open ocean).
      const minW = W / 12;
      const maxW = W * 1.4;
      const nw = Math.max(minW, Math.min(maxW, v.w));
      const nh = nw * (H / W);
      // Pan limits: keep the center inside [-W/4, 5W/4] x [-H/4, 5H/4]
      const cx = v.x + v.w / 2;
      const cy = v.y + v.h / 2;
      const ccx = Math.max(-W / 4, Math.min((5 * W) / 4, cx));
      const ccy = Math.max(-H / 4, Math.min((5 * H) / 4, cy));
      return { x: ccx - nw / 2, y: ccy - nh / 2, w: nw, h: nh };
    },
    [],
  );

  // ─── Cinematic entry ───────────────────────────────────────────────────
  // One-shot fly-down from high altitude to the home framing. Pure
  // viewBox interpolation (no layout work per frame). Skippable via any
  // pointer/key/wheel input; never replays within a session; reduced
  // motion never enters 'flying' at all (static composed state instead).
  useEffect(() => {
    if (entryPhase !== 'flying') return;
    let raf = 0;
    let finished = false;
    const D = 2100;
    const t0 = performance.now();
    const ease = (t: number) =>
      t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
    const finish = () => {
      if (finished) return;
      finished = true;
      cancelAnimationFrame(raf);
      setView({ x: 0, y: 0, w: W, h: H });
      setEntryPhase('done');
      try { window.sessionStorage.setItem('mosw-entry-played', '1'); } catch { /* private mode */ }
    };
    const tick = (t: number) => {
      const p = Math.min(1, (t - t0) / D);
      const e = ease(p);
      setView({
        x: ENTRY_VIEW.x * (1 - e),
        y: ENTRY_VIEW.y * (1 - e),
        w: ENTRY_VIEW.w + (W - ENTRY_VIEW.w) * e,
        h: ENTRY_VIEW.h + (H - ENTRY_VIEW.h) * e,
      });
      if (p >= 1) finish();
      else raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    window.addEventListener('pointerdown', finish);
    window.addEventListener('keydown', finish);
    window.addEventListener('wheel', finish);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener('pointerdown', finish);
      window.removeEventListener('keydown', finish);
      window.removeEventListener('wheel', finish);
    };
  }, [entryPhase, ENTRY_VIEW]);

  // Layer reveal during the flight: flips one frame after mount so CSS
  // transitions (with per-layer delays) carry terrain → basemap → rivers
  // → markers up in sequence while the camera descends.
  const [lit, setLit] = useState(!entryEligible);
  useEffect(() => {
    const id = requestAnimationFrame(() => requestAnimationFrame(() => setLit(true)));
    return () => cancelAnimationFrame(id);
  }, []);
  const fadeIn = useCallback(
    (delayMs: number, durMs = 1100): React.CSSProperties =>
      reducedMotion
        ? {}
        : {
            opacity: lit ? 1 : 0,
            transition: `opacity ${durMs}ms cubic-bezier(0.4,0,0.2,1) ${delayMs}ms`,
          },
    [lit, reducedMotion],
  );

  // Wheel zoom is attached natively (not via React's `onWheel` prop)
  // because React registers wheel listeners as passive by default, which
  // makes `e.preventDefault()` a no-op and triggers the
  // "Unable to preventDefault inside passive event listener" warning.
  // Native `addEventListener` with `{ passive: false }` lets the page
  // suppress browser scroll while we zoom the SVG.
  const svgRef = useRef<SVGSVGElement | null>(null);
  // The stage div hosts the native wheel listener so zoom works over the
  // base SVG, the flow canvas, and the marker SVG alike (events from
  // marker groups bubble up to it).
  const stageRef = useRef<HTMLDivElement | null>(null);
  // The wheel handler reads `view` and writes to it. We stash the latest
  // view in a ref so the native listener (registered once) sees fresh
  // state without needing to re-bind on every view change.
  const viewRef = useRef(view);
  useEffect(() => { viewRef.current = view; }, [view]);

  useEffect(() => {
    const svg = stageRef.current;
    if (!svg) return;
    const handler = (e: WheelEvent) => {
      e.preventDefault();
      const v = viewRef.current;
      const rect = svg.getBoundingClientRect();
      const px = v.x + ((e.clientX - rect.left) / rect.width) * v.w;
      const py = v.y + ((e.clientY - rect.top) / rect.height) * v.h;
      const dy = e.deltaMode === 1 ? e.deltaY * 16 : e.deltaY;
      const factor = Math.exp(dy / 600);
      const nw = v.w * factor;
      const nh = nw * (H / W);
      const nx = px - ((e.clientX - rect.left) / rect.width) * nw;
      const ny = py - ((e.clientY - rect.top) / rect.height) * nh;
      setView(clampView({ x: nx, y: ny, w: nw, h: nh }));
    };
    svg.addEventListener('wheel', handler, { passive: false });
    return () => svg.removeEventListener('wheel', handler);
  }, [clampView]);

  // Drag threshold (pixels of pointer movement before we treat the gesture
  // as a pan). Below this we leave the click path untouched so feature
  // markers receive their click events normally.
  const DRAG_THRESHOLD_PX = 5;

  const onPointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.button !== 0) return;
    // Track potential drag, but DO NOT capture the pointer yet. If we
    // capture here, all subsequent pointer events (including the click
    // that follows pointerup) get retargeted to the SVG, and clicks on
    // markers, the zoom buttons, etc. never reach their original target
    // — diagnosed via /tmp/click-debug.mjs which showed the click event
    // landing on `<svg>` with no marker target. We capture lazily in
    // onPointerMove, only once the user has actually moved past the
    // drag threshold.
    dragRef.current = {
      pointerId: e.pointerId,
      startClientX: e.clientX,
      startClientY: e.clientY,
      startViewX: view.x,
      startViewY: view.y,
      moved: false,
      captured: false,
    };
  }, [view.x, view.y]);

  const [dragging, setDragging] = useState(false);
  const { onHoverGauge } = props;

  const onPointerMove = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    if (!drag) return;
    const dx = e.clientX - drag.startClientX;
    const dy = e.clientY - drag.startClientY;
    if (!drag.moved &&
        (Math.abs(dx) > DRAG_THRESHOLD_PX || Math.abs(dy) > DRAG_THRESHOLD_PX)) {
      drag.moved = true;
      setDragging(true);
      // A pan invalidates the hover overlay's captured screen position;
      // drop the hover so it doesn't float detached from its marker.
      onHoverGauge(null, null);
      // Once we know this is a real drag, capture the pointer so events
      // keep flowing even if the cursor leaves the SVG bounds mid-pan.
      try {
        e.currentTarget.setPointerCapture(drag.pointerId);
        drag.captured = true;
      } catch { /* nothing useful we can do */ }
    }
    if (!drag.moved) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const sx = view.w / rect.width;
    const sy = view.h / rect.height;
    setView((v) => clampView({
      ...v,
      x: drag.startViewX - dx * sx,
      y: drag.startViewY - dy * sy,
    }));
  }, [view.w, view.h, clampView, onHoverGauge]);

  const onPointerUp = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    if (drag?.captured) {
      try { e.currentTarget.releasePointerCapture(drag.pointerId); } catch { /* ignore */ }
    }
    setDragging(false);
    // Don't null `dragRef` synchronously — onClick reads `moved` to know
    // whether this was a real click or the tail of a drag. Cleared next
    // tick.
    setTimeout(() => { dragRef.current = null; }, 0);
  }, []);

  const resetView = useCallback(() => setView(HOME_VIEW), [HOME_VIEW]);

  // Scale factor for "non-scaling" SVG content. Multiply any radius or
  // stroke-width that should stay screen-pixel-stable as the user zooms
  // in by `kStable`. Without this, a 4px gauge dot at 1× zoom becomes a
  // 24px blob at 6× zoom because viewBox-units shrink relative to screen
  // pixels.
  const kStable = view.w / W;

  const zoomBy = useCallback((factor: number) => {
    setView((v) => clampView({
      x: v.x + (v.w * (1 - factor)) / 2,
      y: v.y + (v.h * (1 - factor)) / 2,
      w: v.w * factor,
      h: v.h * factor,
    }));
  }, [clampView]);
  const zoomedIn = view.w < W * 0.99;

  // Click handlers on individual features need to ignore the tail of a
  // drag-pan; otherwise dragging across a river or gauge focuses it on
  // mouseup. Wrap each feature click with this guard.
  const guardClick = useCallback(
    <E extends { stopPropagation: () => void }>(fn: (e: E) => void) => (e: E) => {
      if (dragRef.current?.moved) return;
      e.stopPropagation();
      fn(e);
    },
    [],
  );

  // Curated polylines + gradient recipes for the particle flow layer.
  const flowRivers = useMemo<FlowRiver[]>(() => {
    return props.rivers.map((r) => {
      const grad = riverGradients[r.id];
      // Primary-gauge percentile modulates particle speed within the
      // verdict's band (scrub-aware — the app swaps in the scrubbed day's
      // percentile, so replaying the month visibly changes the current).
      const primarySite = (r.gauges ?? []).find((g) => g.is_primary)?.site_id;
      return {
        id: r.id,
        pts: (r.geometry.coordinates as Array<[number, number]>).map(([lo, la]) =>
          project(lo, la),
        ),
        verdict: props.verdictByRiver[r.slug] ?? 'unknown',
        percentile: primarySite != null ? props.percentileByGauge[primarySite] ?? null : null,
        axis: grad ? { x1: grad.x1, y1: grad.y1, x2: grad.x2, y2: grad.y2 } : null,
        stops: grad ? grad.stops.map((st) => ({ offset: st.offset, color: st.color })) : [],
      };
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.rivers, props.verdictByRiver, props.percentileByGauge, riverGradients, project]);

  // Terrain raster: AVIF first, PNG on decode failure (older Safari).
  const [hillshadeHref, setHillshadeHref] = useState('/mo-hillshade.avif');

  // Particle budget: 700 desktop / 300 small screens or low-end hardware
  // (docs/mo-surface-water-observatory.md). Sampled once per mount.
  const [maxParticles] = useState(() => {
    if (typeof window === 'undefined') return 700;
    const nav = navigator as Navigator & { deviceMemory?: number };
    const small = window.matchMedia('(max-width: 768px)').matches;
    const lowEnd = (navigator.hardwareConcurrency ?? 8) < 4 || (nav.deviceMemory ?? 8) < 4;
    return small || lowEnd ? 300 : 700;
  });

  // Sort rivers so lower-order paint underneath higher-order, and the
  // hovered/focused one always renders last (on top).
  const orderedRivers = useMemo(() => {
    return [...props.rivers].sort((a, b) => {
      const aTop = a.id === props.hoveredRiverId || a.id === props.focusedRiverId;
      const bTop = b.id === props.hoveredRiverId || b.id === props.focusedRiverId;
      if (aTop && !bTop) return 1;
      if (bTop && !aTop) return -1;
      return (a.length_miles ?? 0) - (b.length_miles ?? 0);
    });
  }, [props.rivers, props.hoveredRiverId, props.focusedRiverId]);

  const viewBoxAttr = `${view.x} ${view.y} ${view.w} ${view.h}`;

  return (
    <>
    {/* Stage — owns pan/zoom/hover so events work identically across the
        base SVG, the flow canvas, and the marker SVG stacked inside it. */}
    <div
      ref={stageRef}
      className="absolute inset-0"
      style={{
        cursor: dragging ? 'grabbing' : 'grab',
        touchAction: 'none',
        // Deep-space canvas behind the landmass. CSS background is
        // viewport-fixed, so it correctly does NOT zoom with the map —
        // distant sky shouldn't parallax with a camera move.
        background:
          'radial-gradient(120% 105% at 62% 18%, #0C2833 0%, #071A22 44%, #030A0F 100%)',
        // Interactions wait for the fly-in; skip is on window, so a tap
        // still fast-forwards.
        pointerEvents: entryPhase === 'flying' ? 'none' : undefined,
      }}
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      onPointerCancel={onPointerUp}
      onDoubleClick={resetView}
      onMouseLeave={() => {
        // Per-river/per-gauge onMouseLeave doesn't always fire when the
        // cursor exits the viewport (off-screen, into browser chrome),
        // leaving hoveredRiverId/hoveredGaugeId stuck. Clear them here so
        // the hover-opened rail closes when the pointer leaves the map.
        props.onHoverRiver(null);
        props.onHoverGauge(null, null);
      }}
      onClick={(e) => {
        // Empty-area click clears focus — but only if we didn't just pan.
        if (dragRef.current?.moved) return;
        if (e.target === svgRef.current || e.target === e.currentTarget) {
          props.onFocusRiver(null);
          props.onFocusGauge(null);
          props.onClickCampground(null);
          props.onClickAccessPoint(null);
          props.onClickPoi(null);
        }
      }}
    >
    {/* Distant sky — static, screen-fixed, behind the landmass. */}
    <Stars />
    <svg
      ref={svgRef}
      viewBox={viewBoxAttr}
      preserveAspectRatio="xMidYMid meet"
      className="absolute inset-0 h-full w-full"
    >
      <defs>
        <radialGradient id="mo-bg" cx="50%" cy="50%" r="85%">
          <stop offset="0%" stopColor="#F4ECDB" />
          <stop offset="60%" stopColor="#EADFC2" />
          <stop offset="100%" stopColor="#D4C394" />
        </radialGradient>
        {/* Soft drop shadow so the parchment silhouette lifts off the dark
            teal backdrop. Cast by a dark copy of the state path drawn just
            behind the parchment fill. */}
        <filter id="mo-shadow" x="-30%" y="-30%" width="160%" height="160%">
          <feDropShadow dx="0" dy="10" stdDeviation="16" floodColor="#04141A" floodOpacity="0.6" />
        </filter>
        <pattern id="mo-grain" width="180" height="180" patternUnits="userSpaceOnUse">
          {Array.from({ length: 70 }).map((_, i) => {
            const seed = (i * 9301 + 49297) % 233280;
            const x = seed % 180;
            const y = ((seed / 180) | 0) % 180;
            const r = ((seed % 7) / 10) + 0.3;
            return <circle key={i} cx={x} cy={y} r={r} fill="rgba(105,80,40,0.07)" />;
          })}
        </pattern>
        {/* Clip path so the parchment fill respects MO's borders even when
            the silhouette overflows the viewBox. */}
        <clipPath id="mo-clip">
          <path d={stateOutlinePath} />
        </clipPath>
      </defs>

      {/* Shadow caster — a dark copy of the state, blurred via the filter.
          The parchment group paints over its fill, leaving only the soft
          halo around MO's edges. */}
      <path d={stateOutlinePath} fill="#0B2027" filter="url(#mo-shadow)" />

      {/* State silhouette — parchment fill, clipped to state, plus a stroked
          border for definition. The state path may extend off-canvas; SVG
          clips it naturally. */}
      <g clipPath="url(#mo-clip)">
        <rect width={W} height={H} fill="url(#mo-bg)" />
        <rect width={W} height={H} fill="url(#mo-grain)" />

        {/* Real terrain relief — hillshade baked at build time from SRTM
            (AWS terrarium tiles) in this exact projection, so the Ozark
            plateau, river valleys, and the Bootheel drop-off read as
            actual landforms. Relief lives in the alpha channel (shadow
            ink + sun highlights over transparent flats), so it composites
            plainly on the parchment. One static raster, zero runtime tile
            fetches: AVIF (~200 KB — alpha-heavy content that WebP/PNG
            can't compress well) with the original PNG (~560 KB) as an
            onError fallback for browsers without AVIF.
            See scripts/build-mo-hillshade.ts. */}
        {props.showTerrain !== false && (
          <g style={fadeIn(350, 1400)} pointerEvents="none">
            <image
              href={hillshadeHref}
              x={0}
              y={0}
              width={W}
              height={H}
              preserveAspectRatio="none"
              opacity={0.75}
              onError={() => setHillshadeHref('/mo-hillshade.png')}
            />
          </g>
        )}

        {/* NHD basemap — lakes (filled polygons) under named perennial
            rivers (thin uniform blue). Renders inside the state clip so it
            never bleeds across MO's borders. Curated rivers, gauges, etc.
            paint OUTSIDE this group on top of the basemap. Kept low-contrast
            so the colored curated reaches read as the foreground. */}
        <g pointerEvents="none" style={fadeIn(650, 1200)}>
          {basemapLakePaths.map((l) => (
            <path
              key={`lake-${l.name}`}
              d={l.d}
              fill="#7FB2C2"
              stroke="#3F8499"
              strokeWidth={0.6}
              opacity={0.5}
            />
          ))}
          {basemapRiverPaths.map((r) => (
            <path
              key={`bm-${r.name}`}
              d={r.d}
              stroke="#4E8DA1"
              strokeWidth={strokeWidthForBasemapRiver(r.lengthMi)}
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
              opacity={0.42}
            />
          ))}
        </g>
      </g>
      <path
        d={stateOutlinePath}
        fill="none"
        stroke="rgba(80,60,30,0.65)"
        strokeWidth={2.2}
        strokeLinejoin="round"
      />

      {/* Title — sits on the dark backdrop above the state, so parchment ink */}
      <text
        x={W / 2}
        y={48}
        textAnchor="middle"
        fontFamily="var(--font-mono), ui-monospace, monospace"
        fontSize={13}
        letterSpacing="0.45em"
        fill="rgba(242,234,216,0.4)"
        fontWeight={500}
      >
        STATE OF MISSOURI · LIVE RIVER NETWORK
      </text>

      {/* Cities */}
      <g style={fadeIn(1300, 900)}>
        {visibleCities.map((c) => {
          const [cx, cy] = project(c.lon, c.lat);
          const cityR = (c.type === 'metro' ? 4 : 2.8) * kStable;
          const labelOff = (c.type === 'metro' ? 8 : 6) * kStable;
          const labelSize = (c.type === 'metro' ? 13 : 11) * kStable;
          return (
            <g key={c.name} transform={`translate(${cx} ${cy})`}>
              <circle
                r={cityR}
                fill="rgba(45,42,36,0.78)"
                stroke="rgba(247,246,243,0.9)"
                strokeWidth={1.2 * kStable}
              />
              <text
                x={labelOff}
                y={4 * kStable}
                fontFamily="var(--font-mono), ui-monospace, monospace"
                fontSize={labelSize}
                fontWeight={c.type === 'metro' ? 700 : 500}
                fill="rgba(45,42,36,0.85)"
                paintOrder="stroke"
                stroke="rgba(242,234,216,0.92)"
                strokeWidth={2.5 * kStable}
                strokeLinejoin="round"
              >
                {c.name}
              </text>
            </g>
          );
        })}
      </g>

      {/* Statewide context sites — every active MO stream gauge with a
          current discharge reading. Neutral teal glow nodes: size encodes
          flow (sqrt), dimmed when the reading is older than 2 h. They sit
          UNDER the curated layer so the product's rivers stay foreground. */}
      {props.showSites !== false && contextNodes.length > 0 && (
        <g style={fadeIn(850, 1200)}>
          {contextNodes.map((n) => {
            const selected = props.selectedContextSiteId === n.site.site_no;
            const rr = n.r * kStable;
            return (
              <g
                key={n.site.site_no}
                transform={`translate(${n.x} ${n.y})`}
                className="mosw-ctx"
                style={{ cursor: 'pointer', opacity: selected ? 1 : n.fresh ? 0.8 : 0.4 }}
                onClick={guardClick(() => props.onClickContextSite?.(n.site))}
              >
                <title>
                  {`${n.site.name ?? `USGS ${n.site.site_no}`} · ${Math.round(n.site.dischargeCfs)} cfs — context site, no float rating`}
                </title>
                <circle r={Math.max(9 * kStable, rr * 2)} fill="transparent" pointerEvents="all" />
                {/* Ink beads on parchment (the light base kills soft glows);
                    the curated layer keeps the color + glow treatment. */}
                <circle r={rr * 1.9} fill="#1D525F" opacity={0.14} pointerEvents="none" />
                {/* Dark hairline, not the cream ring — that ring is the
                    curated gauges' signature, and sharing it made the two
                    classes indistinguishable at a glance. */}
                <circle
                  r={rr}
                  fill={n.fresh ? '#1D525F' : '#6B7E85'}
                  stroke={selected ? '#F07052' : 'rgba(15,45,53,0.35)'}
                  strokeWidth={(selected ? 1.8 : 0.7) * kStable}
                  pointerEvents="none"
                />
              </g>
            );
          })}
        </g>
      )}

      {/* Rivers — outer "casing" + per-gauge segmented main stroke. Each
          river is split at midpoints between its gauges and painted in
          bands so the river color "flows into" each gauge instead of
          showing one mean color across the whole reach.

          Wrapped in `clipPath="url(#mo-clip)"` so the curated lines stay
          inside MO's borders — Eleven Point's lower NHD reach legitimately
          continues into Arkansas, but on a Missouri-focused map we clip
          it the same way the basemap is clipped. */}
      <g clipPath="url(#mo-clip)" style={fadeIn(950, 1100)}>
      {orderedRivers.map((r) => {
        const d = riverPaths[r.id];
        if (!d) return null;
        const slug = r.slug;
        const verdict = props.verdictByRiver[slug] ?? 'unknown';
        const fallbackColor = STAGE_VERDICTS[verdict].color;
        const isHovered = props.hoveredRiverId === r.id;
        const isFocused = props.focusedRiverId === r.id;
        const sw = strokeWidthForRiver(r.length_miles, isHovered, isFocused);
        const dim =
          (props.focusedRiverId && !isFocused) ||
          (props.hoveredRiverId && !isHovered && !isFocused);
        const grad = riverGradients[r.id];
        const gradId = `mo-river-grad-${r.id}`;
        const gradStrokeRef = grad ? `url(#${gradId})` : fallbackColor;
        // Highlight the dangerous portion with a brief dashed inner
        // overlay if any gauge is at flood — limited to the segment
        // around that gauge so neighbors aren't visually contaminated.
        const floodGauges = grad?.stops.filter((s) => s.condition === 'dangerous') ?? [];

        return (
          <g
            key={r.id}
            style={{ opacity: dim ? 0.32 : 1, transition: 'opacity 200ms', cursor: 'pointer' }}
            onMouseEnter={() => props.onHoverRiver(r.id)}
            onMouseLeave={() => props.onHoverRiver(null)}
            onClick={guardClick(() => props.onFocusRiver(r.id))}
          >
            {grad && (
              <defs>
                <linearGradient
                  id={gradId}
                  gradientUnits="userSpaceOnUse"
                  x1={grad.x1}
                  y1={grad.y1}
                  x2={grad.x2}
                  y2={grad.y2}
                >
                  {grad.stops.map((s, i) => (
                    <stop key={`${gradId}-stop-${i}`} offset={s.offset} stopColor={s.color} />
                  ))}
                </linearGradient>
              </defs>
            )}
            {/* Hit target */}
            <path d={d} stroke="transparent" strokeWidth={Math.max(18, sw * 3)} fill="none" strokeLinecap="round" />
            {/* Permanent dark casing — frames the colored reach so it reads
                cleanly over both the parchment and the muted basemap. */}
            <path
              d={d}
              stroke="rgba(15,45,53,0.55)"
              strokeWidth={sw + 2.6}
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            {/* Glow on hover/focus */}
            {(isHovered || isFocused) && (
              <path
                d={d}
                stroke={fallbackColor}
                strokeWidth={sw + 7}
                fill="none"
                strokeLinecap="round"
                opacity={0.35}
                style={{ filter: `drop-shadow(0 0 6px ${fallbackColor})` }}
              />
            )}
            {/* Solid gradient base — colors fade smoothly between adjacent
                gauges via the linearGradient stops above. One path per
                river instead of N segments. */}
            <path
              d={d}
              stroke={gradStrokeRef}
              strokeWidth={sw}
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            {/* Flood emphasis — when ANY gauge is at flood, draw a brief
                dashed overlay so the hazard reads even through the fade. */}
            {floodGauges.length > 0 && (
              <path
                d={d}
                stroke={STAGE_VERDICTS.dangerous.inner}
                strokeWidth={Math.max(1.2, sw * 0.42)}
                fill="none"
                strokeLinecap="round"
                strokeDasharray="4 3"
                opacity={0.7}
              />
            )}
          </g>
        );
      })}
      </g>

      {/* Flow animation keyframes — applied per-segment via inline style.
          One dash period = 22 viewBox units (14 dash + 8 gap). */}
      <style>{`
        .mosw-ctx:hover { opacity: 1 !important; }
        @keyframes mosw-breathe { 0%, 100% { opacity: 0.82; } 50% { opacity: 1; } }
      `}</style>

      {/* Access points */}
      {props.showAccessPoints && (
        <g>
          {props.rivers.flatMap((r) =>
            (r.access_points ?? []).map((a) => {
              const [x, y] = project(a.lon, a.lat);
              return (
                <g
                  key={a.id}
                  transform={`translate(${x} ${y})`}
                  style={{ cursor: 'pointer' }}
                  onClick={guardClick(() => props.onClickAccessPoint(a.id))}
                >
                  <circle r={14 * kStable} fill="transparent" pointerEvents="all" />
                  <circle r={3.6 * kStable} fill="#4EB86B" stroke="#1A3D23" strokeWidth={1.1 * kStable} pointerEvents="none" />
                </g>
              );
            }),
          )}
        </g>
      )}

      {/* Campgrounds */}
      {props.showCampgrounds && (
        <g>
          {props.campgrounds.map((c) => {
            const [x, y] = project(c.lon, c.lat);
            const screenR = c.total_sites != null
              ? Math.min(7, 3.5 + c.total_sites / 50)
              : 3.5;
            return (
              <g
                key={c.id}
                transform={`translate(${x} ${y})`}
                style={{ cursor: 'pointer' }}
                onClick={guardClick(() => props.onClickCampground(c.id))}
              >
                <circle r={Math.max(14, screenR + 8) * kStable} fill="transparent" pointerEvents="all" />
                <circle r={screenR * kStable} fill="#7A684B" stroke="#F2EAD8" strokeWidth={1.4 * kStable} opacity={0.95} pointerEvents="none" />
              </g>
            );
          })}
        </g>
      )}

      {/* POIs */}
      {props.showPOIs && (
        <g>
          {props.rivers.flatMap((r) =>
            (r.pois ?? []).map((p) => {
              const [x, y] = project(p.lon, p.lat);
              const tone = POI_TONES[p.type] ?? '#524D43';
              return (
                <g
                  key={p.id}
                  transform={`translate(${x} ${y})`}
                  style={{ cursor: 'pointer' }}
                  onClick={guardClick(() => props.onClickPoi(p.id))}
                >
                  <circle r={14 * kStable} fill="transparent" pointerEvents="all" />
                  <circle r={4.5 * kStable} fill={tone} stroke="#FAF8F4" strokeWidth={1.4 * kStable} pointerEvents="none" />
                </g>
              );
            }),
          )}
        </g>
      )}

      {/* Period of record footer note — dark backdrop corners need light ink */}
      <text
        x={W - 14}
        y={H - 14}
        textAnchor="end"
        fontFamily="var(--font-mono), ui-monospace, monospace"
        fontSize={10}
        fill="rgba(242,234,216,0.42)"
      >
        Geometry: USGS NHD via Supabase · Live data: USGS NWIS
      </text>

      {/* Reference key for percentile coloring */}
      <text
        x={14}
        y={H - 14}
        fontFamily="var(--font-mono), ui-monospace, monospace"
        fontSize={9}
        letterSpacing="0.1em"
        fill="rgba(242,234,216,0.42)"
      >
        Stream colour: float condition at the nearest gauge · small ink dots: statewide USGS sites, no float rating
      </text>

      {/* Scale bar + north arrow — anchored to the viewport (screen-fixed) in
          the empty left-centre band so they never collide with the corner
          cards. Bar length tracks a tidy ground distance for the zoom. */}
      {(() => {
        const m = kStable;
        const km = niceDistance(view.w * 0.16 * kmPerUnit);
        const barUnits = km / kmPerUnit;
        const ox = view.x + view.w * 0.04;
        const oy = view.y + view.h * 0.5;
        const tick = 4.5 * m;
        // The bar floats over the dark canvas left of the state at the
        // default framing — parchment ink, not map-ink, or it vanishes.
        const ink = 'rgba(242,234,216,0.6)';
        return (
          <g pointerEvents="none" fontFamily="var(--font-mono), ui-monospace, monospace">
            <g transform={`translate(${ox + barUnits / 2} ${oy - 26 * m})`}>
              <path d={`M0 ${-9 * m} L${5 * m} ${5 * m} L${-5 * m} ${5 * m} Z`} fill={ink} />
              <text x={0} y={-12 * m} textAnchor="middle" fontSize={9 * m} fontWeight={700} fill={ink}>N</text>
            </g>
            <line x1={ox} y1={oy} x2={ox + barUnits} y2={oy} stroke={ink} strokeWidth={1.6 * m} strokeLinecap="round" />
            <line x1={ox} y1={oy - tick} x2={ox} y2={oy + tick} stroke={ink} strokeWidth={1.6 * m} />
            <line x1={ox + barUnits} y1={oy - tick} x2={ox + barUnits} y2={oy + tick} stroke={ink} strokeWidth={1.6 * m} />
            <text x={ox + barUnits / 2} y={oy - 5 * m} textAnchor="middle" fontSize={9 * m} fill={ink}>
              {km} km · {Math.round(km * 0.621371)} mi
            </text>
          </g>
        );
      })()}
    </svg>

    {/* Animated flow — comet particles on the curated rivers, above the
        river strokes but below the gauge markers (next SVG). Pointer
        events pass straight through. Mounted during the entry flight too:
        the canvas re-derives its viewBox transform from viewRef every
        frame, so particles ride the descending camera — the rivers are
        already breathing when the state settles into place. The fade
        matches the curated river strokes' reveal. */}
    {props.showFlow !== false && !reducedMotion && (
      <FlowLayer
        rivers={flowRivers}
        viewRef={viewRef}
        enabled
        maxParticles={maxParticles}
        style={fadeIn(950)}
      />
    )}

    {/* Marker overlay — gauges stay crisp above the particle stream.
        The SVG itself is transparent to the pointer; each marker opts
        back in, and its events bubble to the stage div for pan/zoom. */}
    <svg
      viewBox={viewBoxAttr}
      preserveAspectRatio="xMidYMid meet"
      className="absolute inset-0 h-full w-full"
      style={{ pointerEvents: 'none' }}
    >
      {/* Gauges. Radii multiplied by kStable so the dot stays the same
          *screen* size at any zoom — at the state-wide view it doesn't
          dwarf the rivers, and zoomed in it doesn't balloon.
          Each marker has an invisible 14px screen hit-target as the
          first child so clicks register reliably even when the visible
          dot is only a few pixels across. */}
      {props.showGauges && (
      <g style={fadeIn(1450, 800)}>
        {props.gauges.map((g) => {
          const r = props.rivers.find((x) => x.id === g.river_id);
          const gauge = r?.gauges?.find((x) => x.site_id === g.site_no);
          if (!gauge) return null;
          const [x, y] = project(gauge.lon, gauge.lat);
          const p = props.percentileByGauge[g.site_no] ?? g.percentile;
          const isHovered = props.hoveredGaugeId === g.site_no;
          const isFocused = props.focusedGaugeId === g.site_no;
          const verdict = props.conditionByGauge[condKey(g.river_id, g.site_no)] ?? 'unknown';
          const verdictColor = STAGE_VERDICTS[verdict]?.color ?? '#A49C8E';
          // Pulse the marker when the river is running high — by discharge
          // percentile when USGS publishes it, otherwise by the editorial
          // condition so stage-only gauges still flag rising water.
          const elevated = (p != null && p >= 75) || verdict === 'high' || verdict === 'dangerous';
          const iconHref = getEddyImageForCondition(verdict);
          // Condition chip: a crisp colored disc with a cream halo reads at
          // any zoom. The Eddy avatar is the personality layer — shown only
          // on hover/focus or once zoomed in (view < 0.5x), where it floats
          // just above the chip like a labeled pin so the anchor stays put.
          const showOtter = isHovered || isFocused || view.w < W * 0.5;
          // Size encodes current discharge on the same sqrt scale as the
          // statewide context sites, so magnitude reads consistently.
          const baseR = magnitudeR(g.dischargeCfs, g.is_primary ? 3.4 : 2.6, 5.6);
          const chipR = (baseR + (isFocused ? 2.4 : isHovered ? 1.2 : 0)) * kStable;
          const otterSize = (isFocused ? 32 : 27) * kStable;
          const iconYOffset = -(chipR + otterSize * 0.58);
          const hitR = Math.max(14, (g.is_primary ? 17 : 13)) * kStable;
          return (
            <g
              // Keyed per river+site: one physical gauge can serve two
              // rivers (07017200 → Courtois + Huzzah) and site_no alone
              // produced duplicate React keys.
              key={condKey(g.river_id, g.site_no)}
              transform={`translate(${x} ${y})`}
              style={{ cursor: 'pointer' }}
              // Keyboard path: ten curated gauges are tabbable; Enter or
              // Space pins the detail rail, same as a click. The label
              // carries condition + reading so the color is never the
              // only channel.
              tabIndex={0}
              role="button"
              aria-label={`${g.river_name} gauge ${g.site_no} — ${STAGE_VERDICTS[verdict]?.label ?? 'no rating'}${g.gaugeHeightFt != null ? `, ${g.gaugeHeightFt.toFixed(2)} feet` : ''}${g.dischargeCfs != null ? `, ${Math.round(g.dischargeCfs)} cfs` : ''}. Open details`}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  props.onFocusGauge(g.site_no);
                }
              }}
              onMouseEnter={(e) => {
                const rect = (e.currentTarget as SVGGElement).getBoundingClientRect();
                props.onHoverGauge(g.site_no, {
                  x: rect.left + rect.width / 2,
                  y: rect.top + rect.height / 2,
                });
              }}
              onMouseLeave={() => props.onHoverGauge(null, null)}
              onClick={guardClick(() => props.onFocusGauge(g.site_no))}
            >
              <circle r={hitR} fill="transparent" pointerEvents="all" />
              {/* soft glow halo — live data reads as lit */}
              <circle r={chipR * 2.3} fill={verdictColor} opacity={0.17} pointerEvents="none" />
              {elevated && !reducedMotion && (
                <circle r={chipR * 1.1} fill="none" stroke={verdictColor} strokeWidth={1.2 * kStable} opacity={0.7} pointerEvents="none">
                  <animate attributeName="r" from={chipR * 1.1} to={chipR * 3.4} dur="2.2s" repeatCount="indefinite" />
                  <animate attributeName="opacity" from="0.7" to="0" dur="2.2s" repeatCount="indefinite" />
                </circle>
              )}
              {showOtter && (
                <image
                  href={iconHref}
                  x={-otterSize / 2}
                  y={iconYOffset - otterSize / 2}
                  width={otterSize}
                  height={otterSize}
                  pointerEvents="none"
                  // Blob-store avatar can be blocked (offline, strict
                  // networks) — hide instead of a broken-image glyph.
                  onError={(e) => { (e.currentTarget as SVGImageElement).style.display = 'none'; }}
                  style={{
                    filter: isFocused
                      ? 'drop-shadow(0 1px 2px rgba(15,45,53,0.55))'
                      : 'drop-shadow(0 1px 1.5px rgba(15,45,53,0.35))',
                  }}
                />
              )}
              <circle
                r={chipR}
                fill={verdictColor}
                stroke="#FAF8F4"
                strokeWidth={1.5 * kStable}
                pointerEvents="none"
                style={{ filter: 'drop-shadow(0 1px 1px rgba(15,45,53,0.35))' }}
              />
            </g>
          );
        })}
      </g>
      )}
    </svg>
    </div>

    {/* Zoom controls — overlay, not inside the SVG, so they stay fixed in
        screen coordinates regardless of the current view. Slides out of
        the way when the right rail is pinned (it used to hide beneath it). */}
    <div
      className="absolute top-1/2 -translate-y-1/2 flex flex-col gap-1 z-10 transition-[right] duration-300"
      style={{
        fontFamily: 'var(--font-mono), ui-monospace, monospace',
        right: props.railOpen ? 'min(384px, calc(100vw - 52px))' : 16,
      }}
    >
      <button
        type="button"
        aria-label="Zoom in"
        onClick={() => zoomBy(0.65)}
        className="w-9 h-9 grid place-items-center rounded-md border-2 select-none"
        style={{
          background: '#FAF8F4', color: '#2D2A24', borderColor: '#3F3B33',
          fontSize: 18, fontWeight: 700, lineHeight: 1,
          boxShadow: '2px 2px 0 #1A1814',
        }}
      >+</button>
      <button
        type="button"
        aria-label="Zoom out"
        onClick={() => zoomBy(1 / 0.65)}
        className="w-9 h-9 grid place-items-center rounded-md border-2 select-none"
        style={{
          background: '#FAF8F4', color: '#2D2A24', borderColor: '#3F3B33',
          fontSize: 22, fontWeight: 700, lineHeight: 1,
          boxShadow: '2px 2px 0 #1A1814',
        }}
      >−</button>
      <button
        type="button"
        aria-label="Reset view"
        onClick={resetView}
        disabled={!zoomedIn}
        className="w-9 h-9 grid place-items-center rounded-md border-2 select-none"
        style={{
          background: zoomedIn ? '#FAF8F4' : '#E8E2D5',
          color: zoomedIn ? '#2D2A24' : '#857D70',
          borderColor: '#3F3B33',
          fontSize: 9.5, fontWeight: 700, letterSpacing: '0', lineHeight: 1,
          boxShadow: zoomedIn ? '2px 2px 0 #1A1814' : 'none',
          cursor: zoomedIn ? 'pointer' : 'default',
        }}
        title="Reset view (or double-click the map)"
      >RESET</button>
    </div>
  </>
  );
}
