'use client';

// Pure SVG implementation of the Missouri Surface Water map.
//
// We deliberately do NOT use MapLibre / vector tiles / glyph PBFs / sprites
// here. Real Supabase geometry is projected from WGS84 into a 1600x1000 SVG
// viewBox via a simple Albers-like equal-area projection centered on
// Missouri. This sidesteps the entire CSP/glyph/style-validation surface
// MapLibre brings, and matches the Claude Design reference visually.
//
// Particles ride along the rendered <path> elements using
// getTotalLength() + getPointAtLength(), the same trick the design uses.

import { useRef, useMemo, useState, useCallback, useEffect, useLayoutEffect } from 'react';
import {
  STAGE_VERDICTS,
  condKey,
  type MORiver,
  type MOCampground,
  type StageVerdict,
} from '@/lib/usgs/mo-statewide-data';
import type { MoStatewideGauge } from '@/app/api/usgs/mo-statewide/route';
import type { MoContextSite } from '@/lib/usgs/mo-sites';
import { getEddyImageForCondition } from '@/constants';
import moOutline from '@/data/mo-outline.json';
import moBasemap from '@/data/mo-rivers-basemap.json';
import {
  W,
  H,
  buildProjector,
  lineToPath,
  polygonToPath,
  bboxOf,
} from './projection';
import { usePrefersReducedMotion } from './fx';
import FlowLayer, { type FlowRiver } from './FlowLayer';
import Stars from './Stars';
import { SHEET_PEEK_FRACTION } from './Chrome';

type BasemapRiver = {
  type: 'Feature';
  properties: { name: string; length_mi: number };
  geometry: { type: 'LineString'; coordinates: number[][] };
};
type BasemapLake = {
  type: 'Feature';
  properties: { name: string; area_sqkm: number };
  geometry: { type: 'Polygon' | 'MultiPolygon'; coordinates: number[][][] | number[][][][] };
};
const BASEMAP_RIVERS = (moBasemap.rivers?.features ?? []) as BasemapRiver[];
const BASEMAP_LAKES = (moBasemap.lakes?.features ?? []) as BasemapLake[];

// ─── Projection ─────────────────────────────────────────────────────────
//
// Shared with the hero backdrop via ./projection — the viewBox is fixed at
// 1600×1000 and the projection window locks to the state outline below.

// ─── Static geometry ────────────────────────────────────────────────────

// Real TIGER/Line state boundaries (Missouri + Arkansas), each simplified to
// ~150 vertices via Douglas-Peucker. Generated by `scripts/build-mo-outline.ts`
// from the topojson/us-atlas states-10m artifact (Census Cartographic Boundary
// cb_2023). The file is a MultiPolygon (one polygon per state); we keep the
// outer ring of each. The region is Missouri + Arkansas so cross-border rivers
// (Eleven Point, Current) and Arkansas rivers (the Buffalo) have land to sit on.
const REGION_RINGS: Array<Array<[number, number]>> = (
  moOutline.coordinates as unknown as number[][][][]
).map((poly) => poly[0] as Array<[number, number]>);
// Flattened vertices, used only to compute the projection window.
const ALL_REGION_COORDS: Array<[number, number]> = REGION_RINGS.flat();

const CITIES: Array<{ name: string; lon: number; lat: number; type: 'metro' | 'city' }> = [
  // Missouri
  { name: 'Kansas City',   lon: -94.578, lat: 39.099, type: 'metro' },
  { name: 'St. Louis',     lon: -90.199, lat: 38.627, type: 'metro' },
  { name: 'Springfield',   lon: -93.298, lat: 37.209, type: 'metro' },
  { name: 'Columbia',      lon: -92.334, lat: 38.952, type: 'city'  },
  { name: 'Jefferson City',lon: -92.173, lat: 38.577, type: 'city'  },
  { name: 'Cape Girardeau',lon: -89.518, lat: 37.306, type: 'city'  },
  { name: 'Joplin',        lon: -94.513, lat: 37.084, type: 'city'  },
  // Arkansas
  { name: 'Little Rock',   lon: -92.289, lat: 34.746, type: 'metro' },
  { name: 'Fayetteville',  lon: -94.157, lat: 36.062, type: 'city'  },
  { name: 'Fort Smith',    lon: -94.398, lat: 35.386, type: 'city'  },
  { name: 'Jonesboro',     lon: -90.704, lat: 35.842, type: 'city'  },
  { name: 'Harrison',      lon: -93.108, lat: 36.230, type: 'city'  }, // Buffalo River gateway
];

// ─── Component ──────────────────────────────────────────────────────────

interface MOMapProps {
  rivers: MORiver[];
  campgrounds: MOCampground[];
  gauges: MoStatewideGauge[];
  verdictByRiver: Record<string, StageVerdict>;
  /** Condition code keyed by `${river_id}::${site_id}` (condKey) — drives
   *  per-segment coloring. Keyed per river, not per site, so a gauge shared
   *  by two rivers classifies independently against each river's thresholds. */
  conditionByGauge: Record<string, StageVerdict>;
  percentileByGauge: Record<string, number | null>;
  hoveredRiverId: string | null;
  focusedRiverId: string | null;
  /** Active condition filter from the dock. Empty/undefined = no filter;
   *  otherwise reaches whose verdict isn't in the set dim back. */
  conditionFilter?: Set<StageVerdict>;
  hoveredGaugeId: string | null;
  focusedGaugeId: string | null;
  showCampgrounds: boolean;
  showAccessPoints: boolean;
  showPOIs: boolean;
  showGauges: boolean;
  /** Baked hillshade relief layer. Defaults on; toggled from the HUD. */
  showTerrain?: boolean;
  /** Animated particle flow layer along the curated rivers. */
  showFlow?: boolean;
  /** Temporarily stop the flow animation (expanded sheet / modal / dock
   *  covering the map) without unmounting the layer. */
  flowPaused?: boolean;
  /** Statewide context sites (neutral, no condition rating). */
  contextSites?: MoContextSite[];
  showSites?: boolean;
  selectedContextSiteId?: string | null;
  onClickContextSite?: (site: MoContextSite | null) => void;
  /** True when the right rail is pinned open — the zoom cluster slides
   *  left so it never hides underneath the rail. */
  railOpen?: boolean;
  onHoverRiver: (id: string | null) => void;
  onFocusRiver: (id: string | null) => void;
  onHoverGauge: (id: string | null, screenPos?: { x: number; y: number } | null) => void;
  onFocusGauge: (id: string | null) => void;
  onClickCampground: (id: string | null) => void;
  onClickAccessPoint: (id: string | null) => void;
  onClickPoi: (id: string | null) => void;
}

const POI_TONES: Record<string, string> = {
  spring: '#1D525F',
  cave: '#3D3425',
  historical_site: '#7A684B',
  scenic_viewpoint: '#347A47',
  waterfall: '#256574',
  geological: '#5C4E38',
  other: '#524D43',
};

function strokeWidthForRiver(
  lengthMiles: number | null | undefined,
  hovered: boolean,
  focused: boolean,
): number {
  // Curated rivers sit on top of the basemap network; keep them visible but
  // not so heavy they read as the only rivers in the state.
  const m = lengthMiles ?? 60;
  const base = Math.max(2.6, Math.min(4.8, 2.2 + m / 60));
  if (focused) return base + 2.4;
  if (hovered) return base + 1.4;
  return base;
}

// Discharge → node radius (viewBox units). Sqrt scale so area tracks
// flow magnitude; clamped so the Mississippi doesn't eat the map.
function magnitudeR(cfs: number | null | undefined, base: number, span: number): number {
  if (cfs == null || cfs <= 0) return base;
  return base + Math.min(1, Math.sqrt(cfs) / Math.sqrt(60000)) * span;
}

// Ray-cast point-in-polygon against a single ring.
function insideRing(lon: number, lat: number, ring: Array<[number, number]>): boolean {
  let inside = false;
  const n = ring.length;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

// Inside EITHER state — context sites arrive bbox-filtered (includes slivers
// of neighboring states); only in-region sites render on the map.
function insideRegion(lon: number, lat: number): boolean {
  return REGION_RINGS.some((ring) => insideRing(lon, lat, ring));
}

// Round a raw distance down to a tidy 1/2/5 × 10ⁿ value for the scale bar.
function niceDistance(km: number): number {
  if (km <= 0) return 1;
  const pow = Math.pow(10, Math.floor(Math.log10(km)));
  const f = km / pow;
  const nice = f >= 5 ? 5 : f >= 2 ? 2 : 1;
  return nice * pow;
}

function strokeWidthForBasemapRiver(lengthMi: number): number {
  // Length-weighted strokes for the NHD basemap network. The previous
  // ramp made small named tributaries (e.g. Jacks Fork at 46 mi) render
  // at 0.7 viewBox-units, which is sub-pixel at full state framing and
  // visually disappears. Bumped across the board so the basemap reads
  // as a real river map at all zoom levels.
  if (lengthMi >= 200) return 2.4;
  if (lengthMi >= 100) return 1.8;
  if (lengthMi >= 50) return 1.4;
  return 1.0;
}

// ── Hue-aware blend for the river condition gradient ────────────────────
// SVG <linearGradient> blends stop colors straight in sRGB, so a green gauge
// feeding into a red one paints a dull off-hue band across the middle of the
// reach — a third color that reads as "conflicting" and makes one section
// look like it's showing two colors at once. We instead sample each
// gauge-to-gauge span in HSL (below) and emit the in-between colors as their
// own stops, so the transition sweeps green → orange → red around the hue
// wheel and the reach colors visibly flow into each other.
function hexToHsl(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  const v = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
  const r = parseInt(v.slice(0, 2), 16) / 255;
  const g = parseInt(v.slice(2, 4), 16) / 255;
  const b = parseInt(v.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const d = max - min;
  let hue = 0;
  let s = 0;
  if (d > 1e-6) {
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) hue = (g - b) / d + (g < b ? 6 : 0);
    else if (max === g) hue = (b - r) / d + 2;
    else hue = (r - g) / d + 4;
    hue *= 60;
  }
  return [hue, s, l];
}

function hslToHex(h: number, s: number, l: number): string {
  const hh = ((h % 360) + 360) % 360;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((hh / 60) % 2) - 1));
  const m = l - c / 2;
  let r = 0;
  let g = 0;
  let b = 0;
  if (hh < 60) [r, g, b] = [c, x, 0];
  else if (hh < 120) [r, g, b] = [x, c, 0];
  else if (hh < 180) [r, g, b] = [0, c, x];
  else if (hh < 240) [r, g, b] = [0, x, c];
  else if (hh < 300) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];
  const to = (n: number) => Math.round((n + m) * 255).toString(16).padStart(2, '0');
  return `#${to(r)}${to(g)}${to(b)}`;
}

// Blend two hex colors in HSL, rotating hue the SHORT way. A near-gray
// endpoint (the "unknown"/too-low tones carry almost no saturation) borrows
// the other end's hue so it fades in cleanly instead of swinging through an
// arbitrary color.
function mixHsl(a: string, b: string, t: number): string {
  const A = hexToHsl(a);
  const B = hexToHsl(b);
  let ha = A[0];
  let hb = B[0];
  if (A[1] < 0.08) ha = hb;
  if (B[1] < 0.08) hb = ha;
  let dh = hb - ha;
  if (dh > 180) dh -= 360;
  if (dh < -180) dh += 360;
  return hslToHex(ha + dh * t, A[1] + (B[1] - A[1]) * t, A[2] + (B[2] - A[2]) * t);
}

// Compositor-camera tuning (see "Compositor-transform camera" below).
// The SVGs render a VIEW_BUFFER margin beyond the stage on every side, so
// gesture transforms can slide the stale raster around without exposing
// blank edges; the REBASE bounds cap how far a transform may stretch that
// raster before we pay for one fresh rasterization.
const VIEW_BUFFER = 0.25; // oversize fraction per side (stage × 1.5)
const REBASE_SCALE_UP = 1.25; // stale raster upscaled ≥25% → too blurry
const REBASE_SCALE_DOWN = 0.8; // downscaled past the buffer's reach

export default function MOMap(props: MOMapProps) {
  const reducedMotion = usePrefersReducedMotion();
  // Lock the projection window to the full region outline (Missouri +
  // Arkansas) so the map always frames both states, no matter what data
  // subset is loaded. Earlier we framed to the data bbox, which caused the
  // view to drift as data changed. Tight padding — the outline already has
  // visual breathing room.
  const bbox = useMemo(() => bboxOf(ALL_REGION_COORDS, 0.02), []);

  const project = useMemo(() => buildProjector(bbox), [bbox]);

  // One compound path covering every state ring — used for the parchment
  // silhouette fill, the border stroke, the drop-shadow caster, and the clip.
  const stateOutlinePath = useMemo(
    () => REGION_RINGS.map((ring) => polygonToPath(ring, project)).join(' '),
    [project],
  );
  // Projected anchor for the Ozark highland tint (southern plateau).
  // Kilometres represented by one viewBox unit — drives the scale bar.
  const kmPerUnit = useMemo(() => {
    const [x0] = project(-92, 38);
    const [x1] = project(-91, 38);
    const dxUnits = Math.abs(x1 - x0) || 1;
    return (111.32 * Math.cos((38 * Math.PI) / 180)) / dxUnits;
  }, [project]);
  const riverPaths = useMemo(() => {
    const out: Record<string, string> = {};
    for (const r of props.rivers) {
      out[r.id] = lineToPath(r.geometry.coordinates as Array<[number, number]>, project);
    }
    return out;
  }, [props.rivers, project]);

  // Per-river gradient stops along each curated river. Replaces the
  // hard-edged per-segment palette with a single SVG <linearGradient>
  // whose stops sit at each gauge's projected position along the line —
  // so adjacent gauges' colors fade smoothly into each other instead of
  // flipping at midpoints.
  //
  // Output: { [riverId]: { x1,y1,x2,y2, stops: Array<{ offset, color, condition, siteId }> } }
  // The gradient direction is the straight line from the river's first
  // projected vertex to its last. For mostly-N-S or mostly-E-W rivers
  // (which is most of MO) this tracks the flow direction. Hard-curving
  // rivers will paint with some color drift relative to local flow, but
  // the smooth fade reads cleanly regardless.
  const riverGradients = useMemo(() => {
    const out: Record<
      string,
      {
        x1: number; y1: number; x2: number; y2: number;
        stops: Array<{ offset: number; color: string; condition: StageVerdict; siteId: string }>;
      }
    > = {};
    for (const r of props.rivers) {
      const coords = r.geometry.coordinates as Array<[number, number]>;
      if (coords.length < 2) continue;
      const first = project(coords[0][0], coords[0][1]);
      const last = project(coords[coords.length - 1][0], coords[coords.length - 1][1]);
      const dx = last[0] - first[0];
      const dy = last[1] - first[1];
      const lenSq = dx * dx + dy * dy;
      if (lenSq < 1) continue; // degenerate

      const gs = (r.gauges ?? [])
        .filter((g) => props.conditionByGauge[condKey(r.id, g.site_id)])
        .map((g) => {
          const [gx, gy] = project(g.lon, g.lat);
          // Project (gx,gy) onto the (first,last) gradient line; t in [0,1].
          const t = ((gx - first[0]) * dx + (gy - first[1]) * dy) / lenSq;
          return {
            siteId: g.site_id,
            condition: props.conditionByGauge[condKey(r.id, g.site_id)],
            offset: Math.max(0, Math.min(1, t)),
          };
        })
        .sort((a, b) => a.offset - b.offset);
      if (!gs.length) continue;

      // Build stops. SVG interpolates linearly between stops, so
      // adjacent gauges fade smoothly. We extend the first/last stops
      // to offsets 0 and 1 so the river ends paint in their nearest
      // gauge's color rather than gradient-default.
      const anchors: Array<{ offset: number; color: string; condition: StageVerdict; siteId: string }> = [];
      const firstColor = STAGE_VERDICTS[gs[0].condition].color;
      const lastColor = STAGE_VERDICTS[gs[gs.length - 1].condition].color;
      if (gs[0].offset > 0.001) {
        anchors.push({ offset: 0, color: firstColor, condition: gs[0].condition, siteId: gs[0].siteId });
      }
      for (const g of gs) {
        anchors.push({ offset: g.offset, color: STAGE_VERDICTS[g.condition].color, condition: g.condition, siteId: g.siteId });
      }
      if (gs[gs.length - 1].offset < 0.999) {
        anchors.push({ offset: 1, color: lastColor, condition: gs[gs.length - 1].condition, siteId: gs[gs.length - 1].siteId });
      }

      // Hold each gauge's color across most of its reach and confine the
      // crossfade to a short band (BLEND_FRAC of the gap) around the midpoint.
      // Colors still flow into each other — no hard divider — but the
      // intermediate hue (a green→red span passes through amber) shrinks from a
      // wide band to a sliver, and a hot gauge's color no longer bleeds far
      // down a calmer reach. The band samples HSL so it sweeps through hue, not
      // a dull off-hue mid-tone; the long solid spans on either side are immune
      // to the straight gradient axis, so most of each river reads true even
      // where it meanders. (Flow is a separate neutral-white layer now and does
      // NOT read these stops; anchors are still preserved so a flood gauge
      // keeps a 'dangerous' stop for the dash overlay's filter.)
      const BLEND_FRAC = 0.3; // share of each gauge-to-gauge gap spent blending
      const STEPS = 6;
      const stops: typeof anchors = [anchors[0]];
      for (let i = 1; i < anchors.length; i++) {
        const prev = anchors[i - 1];
        const cur = anchors[i];
        if (prev.color === cur.color) {
          stops.push(cur);
          continue;
        }
        const mid = (prev.offset + cur.offset) / 2;
        const halfW = (BLEND_FRAC * (cur.offset - prev.offset)) / 2;
        // Hold prev's color solid up to the blend band…
        stops.push({ offset: mid - halfW, color: prev.color, condition: prev.condition, siteId: prev.siteId });
        // …cross-fade through hue across the short band…
        for (let k = 1; k <= STEPS; k++) {
          const t = k / STEPS;
          stops.push({
            offset: mid - halfW + 2 * halfW * t,
            color: mixHsl(prev.color, cur.color, t),
            condition: t < 0.5 ? prev.condition : cur.condition,
            siteId: t < 0.5 ? prev.siteId : cur.siteId,
          });
        }
        // …then hold cur's color solid to its offset.
        stops.push(cur);
      }

      out[r.id] = { x1: first[0], y1: first[1], x2: last[0], y2: last[1], stops };
    }
    return out;
  }, [props.rivers, props.conditionByGauge, project]);

  // Basemap rivers — pre-projected once per `project` change, sorted by
  // length so longer rivers paint underneath shorter ones (so the smaller
  // tributaries don't get covered up).
  const basemapRiverPaths = useMemo(() => {
    return BASEMAP_RIVERS
      .map((f) => ({
        name: f.properties.name,
        lengthMi: f.properties.length_mi,
        d: lineToPath(f.geometry.coordinates as Array<[number, number]>, project),
      }))
      .filter((r) => r.d.length > 0)
      .sort((a, b) => b.lengthMi - a.lengthMi);
  }, [project]);

  // Basemap lakes — flatten Polygon and MultiPolygon outer rings into
  // individual SVG path strings. Holes (inner rings) are ignored at this
  // simplification level; reservoir holes don't render meaningfully here.
  const basemapLakePaths = useMemo(() => {
    const out: Array<{ name: string; d: string }> = [];
    for (const f of BASEMAP_LAKES) {
      const rings: Array<Array<[number, number]>> = [];
      if (f.geometry.type === 'Polygon') {
        const outer = (f.geometry.coordinates as number[][][])[0];
        if (outer) rings.push(outer as Array<[number, number]>);
      } else {
        for (const poly of f.geometry.coordinates as number[][][][]) {
          if (poly[0]) rings.push(poly[0] as Array<[number, number]>);
        }
      }
      const d = rings.map((r) => polygonToPath(r, project)).join(' ');
      if (d) out.push({ name: f.properties.name, d });
    }
    return out;
  }, [project]);

  // Small-screen flag (sampled once) — phones render far fewer context
  // nodes so the SVG tree stays light (up to 900 groups × 3 circles is the
  // single biggest reconciliation + per-zoom DOM-write cost on the map).
  const [isSmallScreen] = useState(
    () => typeof window !== 'undefined' && window.matchMedia('(max-width: 768px)').matches,
  );

  // Context sites — projected once, filtered to in-state points. These
  // are NEUTRAL: location, magnitude (size), and freshness (opacity)
  // only. No condition color — they carry no curated thresholds. Capped to
  // the highest-flow ~180 on phones (biggest first) for performance.
  const contextNodes = useMemo(() => {
    const sites = props.contextSites ?? [];
    const out: Array<{
      site: MoContextSite;
      x: number;
      y: number;
      r: number;
      fresh: boolean;
    }> = [];
    const staleCutoff = Date.now() - 2 * 3600e3;
    for (const s of sites) {
      if (!insideRegion(s.lon, s.lat)) continue;
      const [x, y] = project(s.lon, s.lat);
      out.push({
        site: s,
        x,
        y,
        // Smaller than any curated gauge chip so the two classes read
        // apart in a static screenshot, not just on hover.
        r: magnitudeR(s.dischargeCfs, 1.4, 4.2),
        fresh: s.readingTimestamp != null && Date.parse(s.readingTimestamp) > staleCutoff,
      });
    }
    const CONTEXT_CAP_MOBILE = 180;
    if (isSmallScreen && out.length > CONTEXT_CAP_MOBILE) {
      out.sort((a, b) => (b.site.dischargeCfs ?? 0) - (a.site.dischargeCfs ?? 0));
      return out.slice(0, CONTEXT_CAP_MOBILE);
    }
    return out;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.contextSites, project, isSmallScreen]);

  // Cities visible in the framed area (plus a small buffer outside, so the
  // nearest metro still anchors the user's orientation).
  const visibleCities = useMemo(() => {
    const lonBuf = (bbox.maxLon - bbox.minLon) * 0.18;
    const latBuf = (bbox.maxLat - bbox.minLat) * 0.18;
    return CITIES.filter(
      (c) =>
        c.lon >= bbox.minLon - lonBuf &&
        c.lon <= bbox.maxLon + lonBuf &&
        c.lat >= bbox.minLat - latBuf &&
        c.lat <= bbox.maxLat + latBuf,
    );
  }, [bbox]);

  // ─── Zoom + pan ────────────────────────────────────────────────────────
  // The committed camera is React state; per-frame camera motion is a CSS
  // transform on the pre-rasterized SVGs (see "Compositor-transform camera"
  // below). Wheel zooms around the cursor; primary-button drag pans;
  // double-click resets to the full-state framing. Children never
  // re-project (paths are memoized on `project`).
  // Projected bounding box of the region (Missouri + Arkansas) in viewBox
  // units — the frame the camera fits to.
  const regionBounds = useMemo(() => {
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const [lon, lat] of ALL_REGION_COORDS) {
      const [x, y] = project(lon, lat);
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
    return { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
  }, [project]);

  // Live pixel aspect (w/h) of the map stage. The view rect is kept at this
  // aspect so the SVG's xMidYMid-meet fit FILLS the stage instead of
  // letterboxing: the two-state region is portrait and phones are portrait,
  // so a fixed landscape viewBox shrank the map to a tiny centred island.
  // Measured synchronously below; W/H is the SSR fallback.
  const [stageAspect, setStageAspect] = useState(W / H);
  const stageAspectRef = useRef(W / H);

  // Fit the region into a view rect of the given aspect, with breathing room.
  const fitView = useCallback(
    (aspect: number) => {
      const { x: rx, y: ry, w: rw, h: rh } = regionBounds;
      const PAD = 1.08;
      let w: number, h: number;
      if (aspect >= rw / rh) { h = rh * PAD; w = h * aspect; }
      else { w = rw * PAD; h = w / aspect; }
      return { x: rx + rw / 2 - w / 2, y: ry + rh / 2 - h / 2, w, h };
    },
    [regionBounds],
  );

  const HOME_VIEW = useMemo(() => fitView(stageAspect), [fitView, stageAspect]);
  // High-altitude framing for the cinematic entry — 1.4× wider than home,
  // biased slightly up so the region "rises" into place.
  const ENTRY_VIEW = useMemo(() => {
    const w = HOME_VIEW.w * 1.4, h = HOME_VIEW.h * 1.4;
    const cx = HOME_VIEW.x + HOME_VIEW.w / 2, cy = HOME_VIEW.y + HOME_VIEW.h / 2;
    return { x: cx - w / 2, y: cy - h / 2 - h * 0.06, w, h };
  }, [HOME_VIEW]);
  const entryEligible =
    !reducedMotion &&
    typeof window !== 'undefined' &&
    window.sessionStorage?.getItem('mosw-entry-played') !== '1';
  const [view, setView] = useState(entryEligible ? ENTRY_VIEW : HOME_VIEW);
  // 'flying' → camera en route (interaction blocked, layers fading up);
  // 'done' → composed end state. Reduced motion starts at 'done'.
  const [entryPhase, setEntryPhase] = useState<'flying' | 'done'>(
    entryEligible ? 'flying' : 'done',
  );
  const dragRef = useRef<
    | {
        pointerId: number;
        pointerType: string;
        startClientX: number;
        startClientY: number;
        startViewX: number;
        startViewY: number;
        moved: boolean;
        captured: boolean;
        /** Recent pointer positions — flick velocity is read off the tail. */
        samples: Array<{ t: number; x: number; y: number }>;
      }
    | null
  >(null);

  const clampView = useCallback(
    (v: { x: number; y: number; w: number; h: number }) => {
      // Zoom range is relative to the home framing: ~9× in (rivers readable),
      // and barely past home out (home already shows the whole region, so
      // there's nothing to gain by drifting into open space). Height is
      // derived from the live stage aspect so the view never letterboxes.
      const minW = HOME_VIEW.w / 9;
      const maxW = HOME_VIEW.w * 1.06;
      const nw = Math.max(minW, Math.min(maxW, v.w));
      const nh = nw / stageAspect;
      // Pan limits: keep the view centre within the region (+ slack) so the
      // states can't be dragged off-screen.
      const rcx = regionBounds.x + regionBounds.w / 2;
      const rcy = regionBounds.y + regionBounds.h / 2;
      const mX = regionBounds.w * 0.55, mY = regionBounds.h * 0.55;
      const ccx = Math.max(rcx - mX, Math.min(rcx + mX, v.x + v.w / 2));
      const ccy = Math.max(rcy - mY, Math.min(rcy + mY, v.y + v.h / 2));
      return { x: ccx - nw / 2, y: ccy - nh / 2, w: nw, h: nh };
    },
    [HOME_VIEW, stageAspect, regionBounds],
  );

  const svgRef = useRef<SVGSVGElement | null>(null);
  const markerSvgRef = useRef<SVGSVGElement | null>(null);
  // The stage div hosts the native wheel listener so zoom works over the
  // base SVG, the flow canvas, and the marker SVG alike (events from
  // marker groups bubble up to it).
  const stageRef = useRef<HTMLDivElement | null>(null);
  // The wheel handler reads `view` and writes to it. We stash the latest
  // view in a ref so the native listener (registered once) sees fresh
  // state without needing to re-bind on every view change.
  const viewRef = useRef(view);
  useEffect(() => { viewRef.current = view; }, [view]);

  // ── Compositor-transform camera during gestures + entry (perf) ──
  // Mutating the viewBox per frame forces the browser to re-rasterize the
  // whole SVG scene — ~1,700 nodes PLUS the feDropShadow state silhouette
  // and the grain pattern — every frame, at devicePixelRatio. On a mid-tier
  // phone that runs a pan at ~10fps. Instead we do what real map engines do:
  //
  //   * The two SVGs are rendered OVERSIZED (a VIEW_BUFFER margin on every
  //     side) at a "base" view, whose expanded viewBox is written once.
  //   * Per gesture/animation frame, applyView positions that already-
  //     rasterized layer with a CSS translate+scale — compositor-only work,
  //     no re-raster, no layout, no React.
  //   * When the transform would blur too far (zoom drift) or slide the
  //     buffer out from under the stage (long pan), we "rebase": write the
  //     viewBox at the current view and reset the transform — ONE re-raster
  //     instead of sixty per second.
  //   * Gesture end / animation end commits via setView; a layout effect
  //     below re-bases at the committed view so React state, viewBox, and
  //     transform can never disagree at paint time.
  //
  // The math is exact (not approximate) because clampView locks the view
  // aspect to the stage aspect, so viewBox→screen scale is uniform: the
  // transformed stale raster shows the SAME geometry as a fresh raster,
  // only resampled — which is why the flow canvas (drawn per-frame from
  // viewRef) stays perfectly registered on top of it.
  const baseViewRef = useRef(view);          // view the viewBox was last written at
  const stageSizeRef = useRef({ w: 0, h: 0 }); // stage CSS px (kept by measure())

  // Write the (expanded) viewBox for `v` on both SVGs and zero the transform.
  const writeViewBox = useCallback((v: { x: number; y: number; w: number; h: number }) => {
    baseViewRef.current = v;
    const vb = `${v.x - v.w * VIEW_BUFFER} ${v.y - v.h * VIEW_BUFFER} ${v.w * (1 + 2 * VIEW_BUFFER)} ${v.h * (1 + 2 * VIEW_BUFFER)}`;
    const a = svgRef.current;
    const b = markerSvgRef.current;
    if (a) { a.setAttribute('viewBox', vb); a.style.transform = ''; }
    if (b) { b.setAttribute('viewBox', vb); b.style.transform = ''; }
  }, []);

  const applyView = useCallback((v: { x: number; y: number; w: number; h: number }) => {
    viewRef.current = v;
    const base = baseViewRef.current;
    const { w: SW, h: SH } = stageSizeRef.current;
    if (!SW || !SH) { writeViewBox(v); return; }
    // Scale/offset that repositions the base raster to show view `v`.
    // (transform-origin is the SVG's own top-left, at −BUFFER·stage.)
    const k = base.w / v.w;
    const s = SW / v.w; // CSS px per viewBox unit at the target view
    const tx = (base.x - v.x) * s + VIEW_BUFFER * SW * (1 - k);
    const ty = (base.y - v.y) * s + VIEW_BUFFER * SH * (1 - k);
    // Rebase when blur or buffer exhaustion would show: edges of the
    // transformed layer in stage coordinates must still cover the stage.
    const exL = -VIEW_BUFFER * SW + tx;
    const exT = -VIEW_BUFFER * SH + ty;
    const exR = exL + k * (1 + 2 * VIEW_BUFFER) * SW;
    const exB = exT + k * (1 + 2 * VIEW_BUFFER) * SH;
    if (
      k > REBASE_SCALE_UP || k < REBASE_SCALE_DOWN ||
      exL > 0 || exT > 0 || exR < SW || exB < SH
    ) {
      writeViewBox(v);
      return;
    }
    const t = `translate3d(${tx}px, ${ty}px, 0) scale(${k})`;
    if (svgRef.current) svgRef.current.style.transform = t;
    if (markerSvgRef.current) markerSvgRef.current.style.transform = t;
  }, [writeViewBox]);

  // Flick-glide state (startMomentum lives with the pointer handlers below).
  const momentumRafRef = useRef(0);
  const stopMomentum = useCallback(() => {
    if (momentumRafRef.current) {
      cancelAnimationFrame(momentumRafRef.current);
      momentumRafRef.current = 0;
    }
  }, []);
  useEffect(() => stopMomentum, [stopMomentum]); // no glide past unmount

  // Every committed view (gesture end, zoom buttons, wheel settle, aspect
  // remap, entry/fit checkpoints) re-bases before paint. The SVGs carry no
  // viewBox in JSX — this effect is the single writer, so a mid-gesture
  // React render can never stomp the imperative camera with stale state.
  // It also kills any in-flight glide: a commit from elsewhere (zoom button,
  // aspect remap) must not fight a momentum animation for the camera.
  useLayoutEffect(() => {
    stopMomentum();
    viewRef.current = view; // pre-paint, so the flow canvas can't skew a frame
    writeViewBox(view);
  }, [view, writeViewBox, stopMomentum]);

  // ─── Cinematic entry ───────────────────────────────────────────────────
  // One-shot fly-down from high altitude to the home framing. Pure
  // viewBox interpolation (no layout work per frame). Skippable via any
  // pointer/key/wheel input; never replays within a session; reduced
  // motion never enters 'flying' at all (static composed state instead).
  useEffect(() => {
    if (entryPhase !== 'flying') return;
    let raf = 0;
    let finished = false;
    const D = 2100;
    const t0 = performance.now();
    const ease = (t: number) =>
      t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
    const finish = () => {
      if (finished) return;
      finished = true;
      cancelAnimationFrame(raf);
      setView(HOME_VIEW);
      setEntryPhase('done');
      try { window.sessionStorage.setItem('mosw-entry-played', '1'); } catch { /* private mode */ }
    };
    // Imperative viewBox per frame (like pan/pinch) — a setView per frame
    // re-rendered the marker/river layers ~126 times over the flight.
    // Coarse checkpoint commits keep the kStable marker scale stepping down
    // gently instead of snapping 1.4→1.0 at the end, and keep React state
    // close enough that a mid-flight data render can't hold a stale camera
    // for more than a frame.
    let lastCommit = t0;
    const tick = (t: number) => {
      const p = Math.min(1, (t - t0) / D);
      const e = ease(p);
      applyView({
        x: ENTRY_VIEW.x + (HOME_VIEW.x - ENTRY_VIEW.x) * e,
        y: ENTRY_VIEW.y + (HOME_VIEW.y - ENTRY_VIEW.y) * e,
        w: ENTRY_VIEW.w + (HOME_VIEW.w - ENTRY_VIEW.w) * e,
        h: ENTRY_VIEW.h + (HOME_VIEW.h - ENTRY_VIEW.h) * e,
      });
      if (t - lastCommit > 450) { lastCommit = t; setView(viewRef.current); }
      if (p >= 1) finish();
      else raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    window.addEventListener('pointerdown', finish);
    window.addEventListener('keydown', finish);
    window.addEventListener('wheel', finish);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener('pointerdown', finish);
      window.removeEventListener('keydown', finish);
      window.removeEventListener('wheel', finish);
    };
  }, [entryPhase, ENTRY_VIEW, HOME_VIEW, applyView]);

  // Layer reveal during the flight: flips one frame after mount so CSS
  // transitions (with per-layer delays) carry terrain → basemap → rivers
  // → markers up in sequence while the camera descends.
  const [lit, setLit] = useState(!entryEligible);
  useEffect(() => {
    const id = requestAnimationFrame(() => requestAnimationFrame(() => setLit(true)));
    return () => cancelAnimationFrame(id);
  }, []);
  const fadeIn = useCallback(
    (delayMs: number, durMs = 1100): React.CSSProperties =>
      reducedMotion
        ? {}
        : {
            opacity: lit ? 1 : 0,
            transition: `opacity ${durMs}ms cubic-bezier(0.4,0,0.2,1) ${delayMs}ms`,
          },
    [lit, reducedMotion],
  );

  // Wheel zoom is attached natively (not via React's `onWheel` prop)
  // because React registers wheel listeners as passive by default, which
  // makes `e.preventDefault()` a no-op and triggers the
  // "Unable to preventDefault inside passive event listener" warning.
  // Native `addEventListener` with `{ passive: false }` lets the page
  // suppress browser scroll while we zoom the SVG.
  // Measure the stage's pixel aspect and keep the view rect matched to it, so
  // the region fills the stage on both portrait phones and wide desktops.
  useLayoutEffect(() => {
    const el = stageRef.current;
    if (!el) return;
    const measure = () => {
      const r = el.getBoundingClientRect();
      if (r.width < 1 || r.height < 1) return;
      // Size feeds the compositor-camera transform math even when the
      // aspect (checked below) hasn't meaningfully changed.
      stageSizeRef.current = { w: r.width, h: r.height };
      const a = r.width / r.height;
      if (Math.abs(a - stageAspectRef.current) < 0.002) return;
      stageAspectRef.current = a;
      setStageAspect(a);
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // React to stage-aspect changes. First real measurement: snap the initial
  // (non-fly-in) view to the correctly-framed home. Later changes (rotate,
  // iOS URL bar, the timeline collapsing) remap the CURRENT view to the new
  // aspect — preserving the user's zoom/pan — instead of snapping home.
  // The remap is CENTER-anchored: growing/shrinking h from the top-left
  // corner kept the top edge pinned, so expanding the mobile timeline shoved
  // the whole region toward the top of the stage with dead space below.
  const framedRef = useRef(false);
  useEffect(() => {
    if (!framedRef.current) {
      framedRef.current = true;
      if (entryPhase === 'done') setView(HOME_VIEW);
      return;
    }
    if (entryPhase !== 'done') return;
    setView((v) => {
      const h = v.w / stageAspect;
      return clampView({ ...v, y: v.y + (v.h - h) / 2, h });
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stageAspect]);

  useEffect(() => {
    const svg = stageRef.current;
    if (!svg) return;
    // Wheel frames ride the compositor camera (applyView) like a pinch;
    // React state commits once the wheel goes quiet so a fast scroll-zoom
    // doesn't re-render + re-rasterize the scene on every tick.
    let commitTimer: ReturnType<typeof setTimeout> | null = null;
    const handler = (e: WheelEvent) => {
      e.preventDefault();
      const v = viewRef.current;
      const rect = svg.getBoundingClientRect();
      const px = v.x + ((e.clientX - rect.left) / rect.width) * v.w;
      const py = v.y + ((e.clientY - rect.top) / rect.height) * v.h;
      const dy = e.deltaMode === 1 ? e.deltaY * 16 : e.deltaY;
      const factor = Math.exp(dy / 600);
      const nw = v.w * factor;
      const nh = nw / stageAspectRef.current;
      const nx = px - ((e.clientX - rect.left) / rect.width) * nw;
      const ny = py - ((e.clientY - rect.top) / rect.height) * nh;
      applyView(clampView({ x: nx, y: ny, w: nw, h: nh }));
      if (commitTimer) clearTimeout(commitTimer);
      commitTimer = setTimeout(() => {
        commitTimer = null;
        setView(viewRef.current);
      }, 140);
    };
    svg.addEventListener('wheel', handler, { passive: false });
    return () => {
      svg.removeEventListener('wheel', handler);
      if (commitTimer) {
        clearTimeout(commitTimer);
        setView(viewRef.current); // don't strand an uncommitted camera
      }
    };
  }, [clampView, applyView]);

  // Drag threshold (pixels of pointer movement before we treat the gesture
  // as a pan). Below this we leave the click path untouched so feature
  // markers receive their click events normally. Fingers wobble more than
  // mice — a 5px threshold swallowed imperfect taps as tiny pans, so touch
  // gets a wider dead zone.
  const DRAG_THRESHOLD_PX = 5;
  const TOUCH_DRAG_THRESHOLD_PX = 10;

  // Multi-touch: every active pointer, plus the frozen state of an in-flight
  // two-finger pinch. `hadMultiTouch` suppresses the click that trails a
  // pinch so it doesn't clear the user's selection.
  const pointersRef = useRef<Map<number, { x: number; y: number }>>(new Map());
  const pinchRef = useRef<
    | { startDist: number; startView: { x: number; y: number; w: number; h: number }; startMidX: number; startMidY: number }
    | null
  >(null);
  const hadMultiTouchRef = useRef(false);
  // True while a pan/pinch is actively moving the camera. FlowLayer reads it
  // per frame and skips its particle redraw so the animation doesn't compete
  // with the imperative viewBox mutation for the frame budget (mobile jank).
  const gestureRef = useRef(false);

  const [dragging, setDragging] = useState(false);
  const { onHoverGauge } = props;

  const onPointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    pointersRef.current.set(e.pointerId, { x: e.clientX, y: e.clientY });
    if (pointersRef.current.size === 1) hadMultiTouchRef.current = false;
    if (pointersRef.current.size === 2) {
      // Begin a pinch: freeze the current view + the finger spread/midpoint.
      const pts = [...pointersRef.current.values()];
      pinchRef.current = {
        startDist: Math.hypot(pts[0].x - pts[1].x, pts[0].y - pts[1].y) || 1,
        startView: { ...viewRef.current },
        startMidX: (pts[0].x + pts[1].x) / 2,
        startMidY: (pts[0].y + pts[1].y) / 2,
      };
      hadMultiTouchRef.current = true;
      dragRef.current = null; // cancel any single-finger pan in progress
      setDragging(false);
      onHoverGauge(null, null);
      return;
    }
    if (e.button !== 0) return;
    // A touch-down grabs a gliding map exactly where it is.
    stopMomentum();
    // Track a potential single-finger drag, but DO NOT capture the pointer
    // yet — capturing here retargets the trailing click to the SVG and
    // markers/buttons never receive it. We capture lazily past the threshold.
    dragRef.current = {
      pointerId: e.pointerId,
      pointerType: e.pointerType,
      startClientX: e.clientX,
      startClientY: e.clientY,
      startViewX: viewRef.current.x,
      startViewY: viewRef.current.y,
      moved: false,
      captured: false,
      samples: [{ t: e.timeStamp, x: e.clientX, y: e.clientY }],
    };
  }, [onHoverGauge, stopMomentum]);

  const onPointerMove = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (pointersRef.current.has(e.pointerId)) {
      pointersRef.current.set(e.pointerId, { x: e.clientX, y: e.clientY });
    }
    // Two-finger pinch: zoom by the change in finger spread, and keep the
    // viewBox point under the start-midpoint pinned under the current
    // midpoint (so pinch pans as well as zooms).
    const pinch = pinchRef.current;
    if (pinch && pointersRef.current.size >= 2) {
      gestureRef.current = true; // pause the flow canvas while zooming
      const pts = [...pointersRef.current.values()];
      const dist = Math.hypot(pts[0].x - pts[1].x, pts[0].y - pts[1].y) || 1;
      const curMidX = (pts[0].x + pts[1].x) / 2;
      const curMidY = (pts[0].y + pts[1].y) / 2;
      const rect = e.currentTarget.getBoundingClientRect();
      const sv = pinch.startView;
      const ax = sv.x + ((pinch.startMidX - rect.left) / rect.width) * sv.w;
      const ay = sv.y + ((pinch.startMidY - rect.top) / rect.height) * sv.h;
      const nw = sv.w * (pinch.startDist / dist);
      const nh = nw / stageAspectRef.current;
      const nx = ax - ((curMidX - rect.left) / rect.width) * nw;
      const ny = ay - ((curMidY - rect.top) / rect.height) * nh;
      applyView(clampView({ x: nx, y: ny, w: nw, h: nh }));
      return;
    }
    const drag = dragRef.current;
    if (!drag) return;
    const dx = e.clientX - drag.startClientX;
    const dy = e.clientY - drag.startClientY;
    const threshold = drag.pointerType === 'touch' ? TOUCH_DRAG_THRESHOLD_PX : DRAG_THRESHOLD_PX;
    if (!drag.moved &&
        (Math.abs(dx) > threshold || Math.abs(dy) > threshold)) {
      drag.moved = true;
      // `dragging` only drives the grab cursor — pointless on touch, and
      // the state flip re-renders the whole map tree right at drag start,
      // which is exactly when the frame budget is tightest on phones.
      if (drag.pointerType !== 'touch') setDragging(true);
      gestureRef.current = true; // pause the flow canvas while panning
      // A pan invalidates the hover overlay's captured screen position;
      // drop the hover so it doesn't float detached from its marker.
      onHoverGauge(null, null);
      // Once we know this is a real drag, capture the pointer so events
      // keep flowing even if the cursor leaves the SVG bounds mid-pan.
      try {
        e.currentTarget.setPointerCapture(drag.pointerId);
        drag.captured = true;
      } catch { /* nothing useful we can do */ }
    }
    if (!drag.moved) return;
    drag.samples.push({ t: e.timeStamp, x: e.clientX, y: e.clientY });
    if (drag.samples.length > 8) drag.samples.shift();
    const rect = e.currentTarget.getBoundingClientRect();
    const v = viewRef.current;
    const sx = v.w / rect.width;
    const sy = v.h / rect.height;
    applyView(clampView({
      x: drag.startViewX - dx * sx,
      y: drag.startViewY - dy * sy,
      w: v.w,
      h: v.h,
    }));
  }, [clampView, onHoverGauge, applyView]);

  // Flick glide — the inertia carry after a fast pan lifts. Velocity is the
  // screen-space slope across the drag's last ~90ms of samples; slower
  // releases are positioned drops (no glide). Exponential decay (τ≈325ms,
  // the iOS feel). Each glide frame is a compositor transform via applyView,
  // so the animation costs ~nothing; React commits once, when it stops.
  const startMomentum = useCallback((
    samples: Array<{ t: number; x: number; y: number }>,
    rect: DOMRect,
    tUp: number,
  ): boolean => {
    if (samples.length < 2 || rect.width < 1 || rect.height < 1) return false;
    const newest = samples[samples.length - 1];
    if (tUp - newest.t > 90) return false; // finger paused before lifting
    let oldest = samples[0];
    for (const s of samples) {
      if (newest.t - s.t <= 90) { oldest = s; break; }
    }
    const span = newest.t - oldest.t;
    if (span < 20) return false;
    const vxPx = (newest.x - oldest.x) / span; // screen px / ms
    const vyPx = (newest.y - oldest.y) / span;
    if (Math.hypot(vxPx, vyPx) < 0.25) return false;
    // Drag right slides the view left — camera velocity opposes the finger.
    let vx = -vxPx * (viewRef.current.w / rect.width);
    let vy = -vyPx * (viewRef.current.h / rect.height);
    gestureRef.current = true;
    let last = performance.now();
    const step = (t: number) => {
      const dt = Math.min(50, t - last);
      last = t;
      const cur = viewRef.current;
      const next = clampView({ x: cur.x + vx * dt, y: cur.y + vy * dt, w: cur.w, h: cur.h });
      const moved = Math.abs(next.x - cur.x) > 1e-9 || Math.abs(next.y - cur.y) > 1e-9;
      applyView(next);
      const decay = Math.exp(-dt / 325);
      vx *= decay;
      vy *= decay;
      const pxPerMs = (Math.hypot(vx, vy) * rect.width) / next.w;
      if (!moved || pxPerMs < 0.02) { // hit the pan clamp, or slowed to a stop
        momentumRafRef.current = 0;
        gestureRef.current = false;
        setView(viewRef.current);
        return;
      }
      momentumRafRef.current = requestAnimationFrame(step);
    };
    momentumRafRef.current = requestAnimationFrame(step);
    return true;
  }, [clampView, applyView]);

  const onPointerUp = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    pointersRef.current.delete(e.pointerId);
    if (pointersRef.current.size < 2) pinchRef.current = null;
    // Reset the pinch-click guard only after the trailing click has fired.
    if (pointersRef.current.size === 0) {
      setTimeout(() => { hadMultiTouchRef.current = false; }, 0);
      // Resume the flow animation a beat after the gesture settles — the
      // pointer-up also commits `setView`, which re-renders the marker/river
      // layers; resuming on that same frame would stack the particle redraw
      // onto the commit. A glide keeps drawing through this (the canvas
      // isn't transformed, so per-frame redraws stay registered mid-glide).
      setTimeout(() => {
        if (pointersRef.current.size === 0 && !momentumRafRef.current) {
          gestureRef.current = false;
        }
      }, 160);
    }
    const drag = dragRef.current;
    if (drag?.captured) {
      try { e.currentTarget.releasePointerCapture(drag.pointerId); } catch { /* ignore */ }
    }
    setDragging(false);
    // A fast release glides; the glide commits state when it stops. Anything
    // else commits the imperatively-applied view now so the markers re-scale
    // to the final zoom and the scale bar updates. A no-op (same ref) when
    // nothing moved — React bails, so taps don't re-render.
    const gliding =
      drag?.moved && pointersRef.current.size === 0
        ? startMomentum(drag.samples, e.currentTarget.getBoundingClientRect(), e.timeStamp)
        : false;
    if (!gliding) setView(viewRef.current);
    // Don't null `dragRef` synchronously — onClick reads `moved` to know
    // whether this was a real click or the tail of a drag. Cleared next
    // tick.
    setTimeout(() => { dragRef.current = null; }, 0);
  }, [startMomentum]);

  const resetView = useCallback(() => setView(HOME_VIEW), [HOME_VIEW]);

  // Scale factor for "non-scaling" SVG content. Multiply any radius or
  // stroke-width that should stay screen-pixel-stable as the user zooms
  // in by `kStable`. Without this, a 4px gauge dot at 1× zoom becomes a
  // 24px blob at 6× zoom because viewBox-units shrink relative to screen
  // pixels.
  // Referenced to the home framing (not the raw viewBox width) so markers
  // and labels are a readable, consistent fraction of the stage at every
  // aspect — and stay pixel-stable as you zoom in past home.
  const kStable = view.w / HOME_VIEW.w;

  const zoomBy = useCallback((factor: number) => {
    setView((v) => clampView({
      x: v.x + (v.w * (1 - factor)) / 2,
      y: v.y + (v.h * (1 - factor)) / 2,
      w: v.w * factor,
      h: v.h * factor,
    }));
  }, [clampView]);
  const zoomedIn = view.w < HOME_VIEW.w * 0.99;

  // Click handlers on individual features need to ignore the tail of a
  // drag-pan; otherwise dragging across a river or gauge focuses it on
  // mouseup. Wrap each feature click with this guard.
  const guardClick = useCallback(
    <E extends { stopPropagation: () => void }>(fn: (e: E) => void) => (e: E) => {
      if (dragRef.current?.moved) return;
      e.stopPropagation();
      fn(e);
    },
    [],
  );

  // Curated polylines + gradient recipes for the particle flow layer.
  const flowRivers = useMemo<FlowRiver[]>(() => {
    return props.rivers.map((r) => {
      // Primary-gauge percentile modulates particle speed within the
      // verdict's band (scrub-aware — the app swaps in the scrubbed day's
      // percentile, so replaying the month visibly changes the current).
      const primarySite = (r.gauges ?? []).find((g) => g.is_primary)?.site_id;
      return {
        id: r.id,
        pts: (r.geometry.coordinates as Array<[number, number]>).map(([lo, la]) =>
          project(lo, la),
        ),
        verdict: props.verdictByRiver[r.slug] ?? 'unknown',
        percentile: primarySite != null ? props.percentileByGauge[primarySite] ?? null : null,
      };
    });
    // Color no longer flows through here — wisps are neutral white — so this
    // intentionally does NOT depend on riverGradients.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.rivers, props.verdictByRiver, props.percentileByGauge, project]);

  // Terrain raster: AVIF first, PNG on decode failure (older Safari).
  const [hillshadeHref, setHillshadeHref] = useState('/mo-hillshade.avif');

  // Device-tier hint for the flow layer (lower = phone / low-end hardware):
  // it widens the self-degrade reaction window on weak devices. The sweep
  // count itself is geometry-driven, not budgeted by this. Sampled once per
  // mount (docs/mo-surface-water-observatory.md).
  const [maxParticles] = useState(() => {
    if (typeof window === 'undefined') return 240;
    const nav = navigator as Navigator & { deviceMemory?: number };
    const small = window.matchMedia('(max-width: 768px)').matches;
    const lowEnd = (navigator.hardwareConcurrency ?? 8) < 4 || (nav.deviceMemory ?? 8) < 4;
    return small || lowEnd ? 110 : 240;
  });

  // Sort rivers so lower-order paint underneath higher-order, and the
  // hovered/focused one always renders last (on top).
  const orderedRivers = useMemo(() => {
    return [...props.rivers].sort((a, b) => {
      const aTop = a.id === props.hoveredRiverId || a.id === props.focusedRiverId;
      const bTop = b.id === props.hoveredRiverId || b.id === props.focusedRiverId;
      if (aTop && !bTop) return 1;
      if (bTop && !aTop) return -1;
      return (a.length_miles ?? 0) - (b.length_miles ?? 0);
    });
  }, [props.rivers, props.hoveredRiverId, props.focusedRiverId]);

  // Geometry shared by both camera-driven SVGs: oversized by VIEW_BUFFER on
  // every side (viewBox — written imperatively by writeViewBox — expands to
  // match), origin pinned top-left so applyView's transform math holds.
  const CAMERA_SVG_STYLE: React.CSSProperties = {
    inset: `${-VIEW_BUFFER * 100}%`,
    width: `${(1 + 2 * VIEW_BUFFER) * 100}%`,
    height: `${(1 + 2 * VIEW_BUFFER) * 100}%`,
    transformOrigin: '0 0',
  };

  // ── Memoized static layers (perf) ──
  // The NHD basemap is 1,000+ <path> nodes; memoizing the JSX means a
  // view-commit / entry-frame / hover re-render reuses the same element
  // tree and React skips reconciling all of them. Deps exclude `view`, so
  // the basemap never re-reconciles on pan/zoom.
  const basemapLayer = useMemo(() => {
    const style: React.CSSProperties | undefined = reducedMotion
      ? undefined
      : { opacity: lit ? 1 : 0, transition: 'opacity 1200ms cubic-bezier(0.4,0,0.2,1) 650ms' };
    return (
      <g pointerEvents="none" style={style}>
        {basemapLakePaths.map((l) => (
          <path key={`lake-${l.name}`} d={l.d} fill="#7FB2C2" stroke="#3F8499" strokeWidth={0.6} opacity={0.5} />
        ))}
        {basemapRiverPaths.map((r) => (
          <path
            key={`bm-${r.name}`}
            d={r.d}
            stroke="#4E8DA1"
            strokeWidth={strokeWidthForBasemapRiver(r.lengthMi)}
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
            opacity={0.42}
          />
        ))}
      </g>
    );
  }, [basemapLakePaths, basemapRiverPaths, lit, reducedMotion]);

  // Context-site markers. `kStable` is in deps, so this recomputes on a zoom
  // commit but stays stable across a pan (kStable constant) — React skips
  // the up-to-180 groups while panning.
  const contextLayer = useMemo(() => {
    if (props.showSites === false || contextNodes.length === 0) return null;
    const style: React.CSSProperties | undefined = reducedMotion
      ? undefined
      : { opacity: lit ? 1 : 0, transition: 'opacity 1200ms cubic-bezier(0.4,0,0.2,1) 850ms' };
    return (
      <g style={style}>
        {contextNodes.map((n) => {
          const selected = props.selectedContextSiteId === n.site.site_no;
          const rr = n.r * kStable;
          return (
            <g
              key={n.site.site_no}
              transform={`translate(${n.x} ${n.y})`}
              className="mosw-ctx"
              style={{ cursor: 'pointer', opacity: selected ? 1 : n.fresh ? 0.8 : 0.4 }}
              onClick={guardClick(() => props.onClickContextSite?.(n.site))}
            >
              <title>
                {`${n.site.name ?? `USGS ${n.site.site_no}`} · ${Math.round(n.site.dischargeCfs)} cfs — context site, no float rating`}
              </title>
              <circle r={Math.max(9 * kStable, rr * 2)} fill="transparent" pointerEvents="all" />
              <circle r={rr * 1.9} fill="#1D525F" opacity={0.14} pointerEvents="none" />
              <circle
                r={rr}
                fill={n.fresh ? '#1D525F' : '#6B7E85'}
                stroke={selected ? '#F07052' : 'rgba(15,45,53,0.35)'}
                strokeWidth={(selected ? 1.8 : 0.7) * kStable}
                pointerEvents="none"
              />
            </g>
          );
        })}
      </g>
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [contextNodes, kStable, props.selectedContextSiteId, props.showSites, lit, reducedMotion, guardClick, props.onClickContextSite]);

  // site_no+river → curated gauge row. The marker loop used to run
  // rivers.find × gauges.find per marker per render — O(rivers×gauges)
  // on every hover. Also feeds the selection camera-nudge below.
  const gaugeMetaByKey = useMemo(() => {
    const m = new Map<string, { river: MORiver; gauge: NonNullable<MORiver['gauges']>[number] }>();
    for (const r of props.rivers) {
      for (const g of r.gauges ?? []) m.set(condKey(r.id, g.site_id), { river: r, gauge: g });
    }
    return m;
  }, [props.rivers]);

  // Rating gauges that aren't physically ON their river's drawn line don't
  // get a map marker — a pin floating in a blank basin reads as a data bug
  // ("phantom gauge"). Two ways this happens: a proxy gauge sitting on a
  // different stream than the one it rates (a creek with no gauge of its own
  // borrowing a neighbor's), and curated geometry that stops short of a
  // mainstem gauge (e.g. a line whose upstream end falls short of the gauge).
  // The threshold is generous — NHD simplification keeps true on-river gauges
  // within a few hundred meters — and the check self-heals: point a river at
  // its real on-river gauge, or extend the geometry, and the marker appears.
  // (Concrete example: migration 00164 found Huzzah + Courtois mis-wired to
  // Big River at Irondale — off in another basin, suppressed here — and
  // repointed both to the real Huzzah gauge at Steelville, 07014000. That
  // gauge sits ~0.02 mi off the Huzzah's own line, so the Huzzah marker now
  // shows; Courtois borrows the same gauge as a proxy and it lands ~1.9 mi
  // off the Courtois line, so Courtois stays suppressed here — still rated
  // via the proxy in the dock/cards, just no floating pin.) The gauge itself
  // rates its river in the dock, cards, and reach coloring regardless.
  const offRiverKeys = useMemo(() => {
    const KX = 54.6, KY = 69.0; // ≈ miles per degree at Missouri latitudes
    const MAX_MI = 1.5;
    const out = new Set<string>();
    for (const r of props.rivers) {
      const coords = r.geometry?.coordinates as Array<[number, number]> | undefined;
      if (!coords || coords.length < 2) continue;
      for (const g of r.gauges ?? []) {
        const px = g.lon * KX, py = g.lat * KY;
        let best = Infinity;
        for (let i = 0; i < coords.length - 1 && best > 0.01; i++) {
          const ax = coords[i][0] * KX, ay = coords[i][1] * KY;
          const bx = coords[i + 1][0] * KX, by = coords[i + 1][1] * KY;
          const dx = bx - ax, dy = by - ay;
          const L2 = dx * dx + dy * dy || 1e-9;
          const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / L2));
          const qx = ax + t * dx, qy = ay + t * dy;
          const d = Math.hypot(px - qx, py - qy);
          if (d < best) best = d;
        }
        if (best > MAX_MI) out.add(condKey(r.id, g.site_id));
      }
    }
    return out;
  }, [props.rivers]);

  // Hoisted from the marker loop so the memoized layer deps on a boolean,
  // not the continuously-changing view object.
  const otterZoom = view.w < HOME_VIEW.w * 0.5;

  // Gauge markers, memoized like contextLayer: recomputes on zoom commits,
  // data ticks, and hover/focus id changes — but NOT on pans or on the
  // hover-position renders that fire for every pointer move on a marker.
  const gaugeLayer = useMemo(() => {
    if (!props.showGauges) return null;
    return (
      <g style={fadeIn(1450, 800)}>
        {props.gauges.map((g) => {
          const meta = gaugeMetaByKey.get(condKey(g.river_id, g.site_no));
          if (!meta) return null;
          if (offRiverKeys.has(condKey(g.river_id, g.site_no))) return null;
          const gauge = meta.gauge;
          const [x, y] = project(gauge.lon, gauge.lat);
          const p = props.percentileByGauge[g.site_no] ?? g.percentile;
          const isHovered = props.hoveredGaugeId === g.site_no;
          const isFocused = props.focusedGaugeId === g.site_no;
          const verdict = props.conditionByGauge[condKey(g.river_id, g.site_no)] ?? 'unknown';
          const verdictColor = STAGE_VERDICTS[verdict]?.color ?? '#A49C8E';
          // Pulse the marker when the river is running high — by discharge
          // percentile when USGS publishes it, otherwise by the editorial
          // condition so stage-only gauges still flag rising water.
          const elevated = (p != null && p >= 75) || verdict === 'high' || verdict === 'dangerous';
          const iconHref = getEddyImageForCondition(verdict);
          // Condition chip: a crisp colored disc with a cream halo reads at
          // any zoom. The Eddy avatar is the personality layer — shown only
          // on hover/focus or once zoomed in (view < 0.5x), where it floats
          // just above the chip like a labeled pin so the anchor stays put.
          const showOtter = isHovered || isFocused || otterZoom;
          // Size encodes current discharge on the same sqrt scale as the
          // statewide context sites, so magnitude reads consistently.
          const baseR = magnitudeR(g.dischargeCfs, g.is_primary ? 3.4 : 2.6, 5.6);
          const chipR = (baseR + (isFocused ? 2.4 : isHovered ? 1.2 : 0)) * kStable;
          const otterSize = (isFocused ? 32 : 27) * kStable;
          const iconYOffset = -(chipR + otterSize * 0.58);
          // Generous invisible tap target — gauges are the primary touch
          // interaction and SVG <g> isn't covered by the global 44px rule.
          // Pinch-zoom (now supported) separates gauges that sit close.
          const hitR = (g.is_primary ? 24 : 20) * kStable;
          return (
            <g
              // Keyed per river+site: one physical gauge can serve two
              // rivers (07017200 → Courtois + Huzzah) and site_no alone
              // produced duplicate React keys.
              key={condKey(g.river_id, g.site_no)}
              transform={`translate(${x} ${y})`}
              // .mosw-marker: default focus ring off (a tap left a giant
              // blue pill around the group), branded ring on :focus-visible
              // so keyboard users keep their indicator (globals.css).
              className="mosw-marker"
              style={{ cursor: 'pointer' }}
              // Keyboard path: ten curated gauges are tabbable; Enter or
              // Space pins the detail rail, same as a click. The label
              // carries condition + reading so the color is never the
              // only channel.
              tabIndex={0}
              role="button"
              aria-label={`${g.river_name} gauge ${g.site_no} — ${STAGE_VERDICTS[verdict]?.label ?? 'no rating'}${g.gaugeHeightFt != null ? `, ${g.gaugeHeightFt.toFixed(2)} feet` : ''}${g.dischargeCfs != null ? `, ${Math.round(g.dischargeCfs)} cfs` : ''}. Open details`}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  props.onFocusGauge(g.site_no);
                }
              }}
              // Pointer (not mouse) events so touch can be excluded: iOS
              // fires a synthetic mouseenter before click, which flashed
              // the hover card for a frame before the sheet opened.
              onPointerEnter={(e) => {
                if (e.pointerType === 'touch') return;
                const rect = (e.currentTarget as SVGGElement).getBoundingClientRect();
                props.onHoverGauge(g.site_no, {
                  x: rect.left + rect.width / 2,
                  y: rect.top + rect.height / 2,
                });
              }}
              onPointerLeave={(e) => {
                if (e.pointerType === 'touch') return;
                props.onHoverGauge(null, null);
              }}
              onClick={guardClick(() => props.onFocusGauge(g.site_no))}
            >
              <circle r={hitR} fill="transparent" pointerEvents="all" />
              {/* soft glow halo — live data reads as lit */}
              <circle r={chipR * 2.3} fill={verdictColor} opacity={0.17} pointerEvents="none" />
              {elevated && !reducedMotion && (
                <circle r={chipR * 1.1} fill="none" stroke={verdictColor} strokeWidth={1.2 * kStable} opacity={0.7} pointerEvents="none">
                  <animate attributeName="r" from={chipR * 1.1} to={chipR * 3.4} dur="2.2s" repeatCount="indefinite" />
                  <animate attributeName="opacity" from="0.7" to="0" dur="2.2s" repeatCount="indefinite" />
                </circle>
              )}
              {showOtter && (
                <image
                  href={iconHref}
                  x={-otterSize / 2}
                  y={iconYOffset - otterSize / 2}
                  width={otterSize}
                  height={otterSize}
                  pointerEvents="none"
                  // Blob-store avatar can be blocked (offline, strict
                  // networks) — hide instead of a broken-image glyph.
                  onError={(e) => { (e.currentTarget as SVGImageElement).style.display = 'none'; }}
                  style={{
                    filter: isFocused
                      ? 'drop-shadow(0 1px 2px rgba(15,45,53,0.55))'
                      : 'drop-shadow(0 1px 1.5px rgba(15,45,53,0.35))',
                  }}
                />
              )}
              <circle
                r={chipR}
                fill={verdictColor}
                stroke="#FAF8F4"
                strokeWidth={1.5 * kStable}
                pointerEvents="none"
                style={{ filter: 'drop-shadow(0 1px 1px rgba(15,45,53,0.35))' }}
              />
            </g>
          );
        })}
      </g>
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    props.gauges, gaugeMetaByKey, offRiverKeys, kStable, otterZoom,
    props.hoveredGaugeId, props.focusedGaugeId,
    props.conditionByGauge, props.percentileByGauge, props.showGauges,
    reducedMotion, fadeIn, guardClick, project,
    props.onFocusGauge, props.onHoverGauge,
  ]);

  // ── Selection camera fit (mobile) ──
  // The peek sheet covers the bottom ~44% of the screen, and at the home
  // framing a selected river is a barely-legible sliver even when it is
  // technically "visible" above the sheet (which is why the old Y-only
  // nudge did nothing for deep links). When a selection lands, fit the
  // camera to the feature's projected bounds inside the still-visible band
  // above the sheet — zooming in or out as needed. Fires once per selection
  // (a ref, not deps, guards this), INCLUDING selections made while the
  // entry fly-in is still running: those fit as soon as the entry completes.
  // A user pointerdown cancels mid-flight.
  const fittedSelRef = useRef<string | null>(null);
  const selectionKey = `${props.focusedGaugeId ?? ''}|${props.focusedRiverId ?? ''}|${props.selectedContextSiteId ?? ''}`;
  useEffect(() => {
    if (!isSmallScreen || entryPhase !== 'done') return;
    if (selectionKey === '||') { fittedSelRef.current = null; return; }
    if (fittedSelRef.current === selectionKey) return;

    // Resolve the selection to a projected bbox. Point features (gauges,
    // context sites) get a synthetic box ~1/8 of the region so the camera
    // settles at a readable neighborhood zoom instead of a pin on a wall.
    let bbox: { x: number; y: number; w: number; h: number } | null = null;
    const pointBox = (lon: number, lat: number) => {
      const [x, y] = project(lon, lat);
      const s = regionBounds.w * 0.12;
      return { x: x - s / 2, y: y - s / 2, w: s, h: s };
    };
    if (props.focusedGaugeId) {
      const g = props.gauges.find((x) => x.site_no === props.focusedGaugeId);
      const meta = g ? gaugeMetaByKey.get(condKey(g.river_id, g.site_no)) : undefined;
      if (meta) bbox = pointBox(meta.gauge.lon, meta.gauge.lat);
    } else if (props.focusedRiverId) {
      const r = props.rivers.find((x) => x.id === props.focusedRiverId);
      if (r) {
        let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
        for (const [lon, lat] of r.geometry.coordinates as Array<[number, number]>) {
          const [x, y] = project(lon, lat);
          if (x < minX) minX = x;
          if (x > maxX) maxX = x;
          if (y < minY) minY = y;
          if (y > maxY) maxY = y;
        }
        if (minX < Infinity) bbox = { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
      }
    } else if (props.selectedContextSiteId) {
      const s = (props.contextSites ?? []).find((x) => x.site_no === props.selectedContextSiteId);
      if (s) bbox = pointBox(s.lon, s.lat);
    }
    const stage = stageRef.current;
    if (!bbox || !stage) return;
    fittedSelRef.current = selectionKey;

    // The band of the stage still visible above the peek sheet.
    const rect = stage.getBoundingClientRect();
    if (rect.width < 1 || rect.height < 1) return;
    const sheetTop = window.innerHeight - Math.round(window.innerHeight * SHEET_PEEK_FRACTION);
    const visibleFrac = Math.max(0.25, (Math.min(rect.bottom, sheetTop) - rect.top) / rect.height);

    // View width that fits the bbox into the band with breathing room (90%
    // of the stage width, 80% of the band height), at the stage aspect. The
    // bbox centers in the band; clampView bounds zoom + pan (long rivers cap
    // at the max-out zoom and fit best-effort).
    const from = { ...viewRef.current };
    const needW = Math.max(bbox.w / 0.9, (bbox.h / (visibleFrac * 0.8)) * stageAspect);
    const to = clampView({
      x: bbox.x + bbox.w / 2 - needW / 2,
      y: bbox.y + bbox.h / 2 - (needW / stageAspect) * (visibleFrac / 2),
      w: needW,
      h: needW / stageAspect,
    });

    if (reducedMotion) {
      applyView(to);
      setView(to);
      return;
    }
    let raf = 0;
    const D = 420;
    const t0 = performance.now();
    const easeInOut = (t: number) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);
    const tick = (t: number) => {
      const p = Math.min(1, (t - t0) / D);
      const e = easeInOut(p);
      applyView({
        x: from.x + (to.x - from.x) * e,
        y: from.y + (to.y - from.y) * e,
        w: from.w + (to.w - from.w) * e,
        h: from.h + (to.h - from.h) * e,
      });
      if (p >= 1) setView(viewRef.current);
      else raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    // The user grabbing the map mid-fit wins immediately.
    const cancel = () => { cancelAnimationFrame(raf); setView(viewRef.current); };
    window.addEventListener('pointerdown', cancel, { once: true });
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener('pointerdown', cancel);
    };
    // Keyed on the selection + entry completion; fittedSelRef makes it fire
    // once per selection (no re-fit after the user pans away).
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectionKey, entryPhase]);

  return (
    <>
    {/* Stage — owns pan/zoom/hover so events work identically across the
        base SVG, the flow canvas, and the marker SVG stacked inside it. */}
    <div
      ref={stageRef}
      className="absolute inset-0 overflow-hidden"
      style={{
        cursor: dragging ? 'grabbing' : 'grab',
        touchAction: 'none',
        // Deep-space canvas behind the landmass. CSS background is
        // viewport-fixed, so it correctly does NOT zoom with the map —
        // distant sky shouldn't parallax with a camera move.
        background:
          'radial-gradient(120% 105% at 62% 18%, #0C2833 0%, #071A22 44%, #030A0F 100%)',
        // Interactions wait for the fly-in; skip is on window, so a tap
        // still fast-forwards.
        pointerEvents: entryPhase === 'flying' ? 'none' : undefined,
      }}
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      onPointerCancel={onPointerUp}
      onDoubleClick={resetView}
      onMouseLeave={() => {
        // Per-river/per-gauge onMouseLeave doesn't always fire when the
        // cursor exits the viewport (off-screen, into browser chrome),
        // leaving hoveredRiverId/hoveredGaugeId stuck. Clear them here so
        // the hover-opened rail closes when the pointer leaves the map.
        props.onHoverRiver(null);
        props.onHoverGauge(null, null);
      }}
      onClick={(e) => {
        // Empty-area click clears focus — but only if we didn't just pan
        // or finish a pinch.
        if (dragRef.current?.moved || hadMultiTouchRef.current) return;
        if (e.target === svgRef.current || e.target === e.currentTarget) {
          props.onFocusRiver(null);
          props.onFocusGauge(null);
          props.onClickCampground(null);
          props.onClickAccessPoint(null);
          props.onClickPoi(null);
        }
      }}
    >
    {/* Distant sky — static, screen-fixed, behind the landmass. */}
    <Stars />
    <svg
      ref={svgRef}
      preserveAspectRatio="xMidYMid meet"
      className="absolute"
      style={CAMERA_SVG_STYLE}
    >
      <defs>
        <radialGradient id="mo-bg" cx="50%" cy="50%" r="85%">
          <stop offset="0%" stopColor="#F4ECDB" />
          <stop offset="60%" stopColor="#EADFC2" />
          <stop offset="100%" stopColor="#D4C394" />
        </radialGradient>
        {/* Soft drop shadow so the parchment silhouette lifts off the dark
            teal backdrop. Cast by a dark copy of the state path drawn just
            behind the parchment fill. */}
        <filter id="mo-shadow" x="-30%" y="-30%" width="160%" height="160%">
          <feDropShadow dx="0" dy="10" stdDeviation="16" floodColor="#04141A" floodOpacity="0.6" />
        </filter>
        <pattern id="mo-grain" width="180" height="180" patternUnits="userSpaceOnUse">
          {Array.from({ length: 70 }).map((_, i) => {
            const seed = (i * 9301 + 49297) % 233280;
            const x = seed % 180;
            const y = ((seed / 180) | 0) % 180;
            const r = ((seed % 7) / 10) + 0.3;
            return <circle key={i} cx={x} cy={y} r={r} fill="rgba(105,80,40,0.07)" />;
          })}
        </pattern>
        {/* Clip path so the parchment fill respects MO's borders even when
            the silhouette overflows the viewBox. */}
        <clipPath id="mo-clip">
          <path d={stateOutlinePath} />
        </clipPath>
      </defs>

      {/* Shadow caster — a dark copy of the state, blurred via the filter.
          The parchment group paints over its fill, leaving only the soft
          halo around MO's edges. */}
      <path d={stateOutlinePath} fill="#0B2027" filter="url(#mo-shadow)" />

      {/* State silhouette — parchment fill, clipped to state, plus a stroked
          border for definition. The state path may extend off-canvas; SVG
          clips it naturally. */}
      <g clipPath="url(#mo-clip)">
        <rect width={W} height={H} fill="url(#mo-bg)" />
        <rect width={W} height={H} fill="url(#mo-grain)" />

        {/* Real terrain relief — hillshade baked at build time from SRTM
            (AWS terrarium tiles) in this exact projection, so the Ozark
            plateau, river valleys, and the Bootheel drop-off read as
            actual landforms. Relief lives in the alpha channel (shadow
            ink + sun highlights over transparent flats), so it composites
            plainly on the parchment. One static raster, zero runtime tile
            fetches: AVIF (~200 KB — alpha-heavy content that WebP/PNG
            can't compress well) with the original PNG (~560 KB) as an
            onError fallback for browsers without AVIF.
            See scripts/build-mo-hillshade.ts. */}
        {props.showTerrain !== false && (
          <g style={fadeIn(350, 1400)} pointerEvents="none">
            <image
              href={hillshadeHref}
              x={0}
              y={0}
              width={W}
              height={H}
              preserveAspectRatio="none"
              opacity={0.75}
              onError={() => setHillshadeHref('/mo-hillshade.png')}
            />
          </g>
        )}

        {/* NHD basemap — lakes (filled polygons) under named perennial
            rivers (thin uniform blue). Renders inside the state clip so it
            never bleeds across MO's borders. Curated rivers, gauges, etc.
            paint OUTSIDE this group on top of the basemap. Kept low-contrast
            so the colored curated reaches read as the foreground. */}
        {basemapLayer}
      </g>
      <path
        d={stateOutlinePath}
        fill="none"
        stroke="rgba(80,60,30,0.65)"
        strokeWidth={2.2}
        strokeLinejoin="round"
      />

      {/* Cities */}
      <g style={fadeIn(1300, 900)}>
        {visibleCities.map((c) => {
          const [cx, cy] = project(c.lon, c.lat);
          const cityR = (c.type === 'metro' ? 4 : 2.8) * kStable;
          const labelOff = (c.type === 'metro' ? 8 : 6) * kStable;
          const labelSize = (c.type === 'metro' ? 13 : 11) * kStable;
          return (
            <g key={c.name} transform={`translate(${cx} ${cy})`}>
              <circle
                r={cityR}
                fill="rgba(45,42,36,0.78)"
                stroke="rgba(247,246,243,0.9)"
                strokeWidth={1.2 * kStable}
              />
              <text
                x={labelOff}
                y={4 * kStable}
                fontFamily="var(--font-mono), ui-monospace, monospace"
                fontSize={labelSize}
                fontWeight={c.type === 'metro' ? 700 : 500}
                fill="rgba(45,42,36,0.85)"
                paintOrder="stroke"
                stroke="rgba(242,234,216,0.92)"
                strokeWidth={2.5 * kStable}
                strokeLinejoin="round"
              >
                {c.name}
              </text>
            </g>
          );
        })}
      </g>

      {/* Statewide context sites — every active MO stream gauge with a
          current discharge reading. Neutral teal glow nodes: size encodes
          flow (sqrt), dimmed when the reading is older than 2 h. They sit
          UNDER the curated layer so the product's rivers stay foreground. */}
      {contextLayer}

      {/* Rivers — outer "casing" + per-gauge segmented main stroke. Each
          river is split at midpoints between its gauges and painted in
          bands so the river color "flows into" each gauge instead of
          showing one mean color across the whole reach.

          Wrapped in `clipPath="url(#mo-clip)"` so the curated lines stay
          inside MO's borders — Eleven Point's lower NHD reach legitimately
          continues into Arkansas, but on a Missouri-focused map we clip
          it the same way the basemap is clipped. */}
      <g clipPath="url(#mo-clip)" style={fadeIn(950, 1100)}>
      {orderedRivers.map((r) => {
        const d = riverPaths[r.id];
        if (!d) return null;
        const slug = r.slug;
        const verdict = props.verdictByRiver[slug] ?? 'unknown';
        const fallbackColor = STAGE_VERDICTS[verdict].color;
        const isHovered = props.hoveredRiverId === r.id;
        const isFocused = props.focusedRiverId === r.id;
        const isActive = isHovered || isFocused;
        const sw = strokeWidthForRiver(r.length_miles, isHovered, isFocused);
        // Two ways a reach recedes. Hover/focus is a soft de-emphasis (0.32,
        // keeps the rest of the map legible). A condition filter is a harder
        // exclusion — the reach isn't part of the answer — so it fades further
        // (0.16), enough that a bright, glowing flood reach stops out-shouting
        // the one muted match. The actively hovered/focused reach always wins.
        const filterActive = (props.conditionFilter?.size ?? 0) > 0;
        const outOfFilter =
          filterActive && !isActive && !props.conditionFilter!.has(verdict);
        const focusDim =
          !isActive && (!!props.focusedRiverId || !!props.hoveredRiverId);
        const reachOpacity = outOfFilter ? 0.16 : focusDim ? 0.32 : 1;
        const grad = riverGradients[r.id];
        const gradId = `mo-river-grad-${r.id}`;
        const gradStrokeRef = grad ? `url(#${gradId})` : fallbackColor;
        // Highlight the dangerous portion with a brief dashed inner
        // overlay if any gauge is at flood — limited to the segment
        // around that gauge so neighbors aren't visually contaminated.
        const floodGauges = grad?.stops.filter((s) => s.condition === 'dangerous') ?? [];

        return (
          <g
            key={r.id}
            style={{ opacity: reachOpacity, transition: 'opacity 200ms', cursor: 'pointer' }}
            // Pointer (not mouse) events so touch is excluded — iOS fires a
            // synthetic mouseenter before click, which flashed the hover
            // rail for a frame before the tap focused the river.
            onPointerEnter={(e) => { if (e.pointerType !== 'touch') props.onHoverRiver(r.id); }}
            onPointerLeave={(e) => { if (e.pointerType !== 'touch') props.onHoverRiver(null); }}
            onClick={guardClick(() => props.onFocusRiver(r.id))}
          >
            {grad && (
              <defs>
                <linearGradient
                  id={gradId}
                  gradientUnits="userSpaceOnUse"
                  x1={grad.x1}
                  y1={grad.y1}
                  x2={grad.x2}
                  y2={grad.y2}
                >
                  {grad.stops.map((s, i) => (
                    <stop key={`${gradId}-stop-${i}`} offset={s.offset} stopColor={s.color} />
                  ))}
                </linearGradient>
              </defs>
            )}
            {/* Hit target */}
            <path d={d} stroke="transparent" strokeWidth={Math.max(18, sw * 3)} fill="none" strokeLinecap="round" />
            {/* No dark casing — the bold condition band sits straight on the
                parchment now (the gray outline read as clutter). */}
            {/* Glow on hover/focus */}
            {(isHovered || isFocused) && (
              <path
                d={d}
                stroke={fallbackColor}
                strokeWidth={sw + 7}
                fill="none"
                strokeLinecap="round"
                opacity={0.35}
                style={{ filter: `drop-shadow(0 0 6px ${fallbackColor})` }}
              />
            )}
            {/* Solid gradient base — colors fade smoothly between adjacent
                gauges via the linearGradient stops above. One path per
                river instead of N segments. */}
            <path
              d={d}
              stroke={gradStrokeRef}
              strokeWidth={sw}
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            {/* Flood emphasis — when ANY gauge is at flood, draw a brief
                dashed overlay so the hazard reads even through the fade. */}
            {floodGauges.length > 0 && (
              <path
                d={d}
                stroke={STAGE_VERDICTS.dangerous.inner}
                strokeWidth={Math.max(1.2, sw * 0.42)}
                fill="none"
                strokeLinecap="round"
                strokeDasharray="4 3"
                opacity={0.7}
              />
            )}
          </g>
        );
      })}
      </g>

      {/* Flow animation keyframes — applied per-segment via inline style.
          One dash period = 22 viewBox units (14 dash + 8 gap). */}
      <style>{`
        .mosw-ctx:hover { opacity: 1 !important; }
        @keyframes mosw-breathe { 0%, 100% { opacity: 0.82; } 50% { opacity: 1; } }
      `}</style>

      {/* Access points */}
      {props.showAccessPoints && (
        <g>
          {props.rivers.flatMap((r) =>
            (r.access_points ?? []).map((a) => {
              const [x, y] = project(a.lon, a.lat);
              return (
                <g
                  key={a.id}
                  transform={`translate(${x} ${y})`}
                  style={{ cursor: 'pointer' }}
                  onClick={guardClick(() => props.onClickAccessPoint(a.id))}
                >
                  <circle r={14 * kStable} fill="transparent" pointerEvents="all" />
                  <circle r={3.6 * kStable} fill="#4EB86B" stroke="#1A3D23" strokeWidth={1.1 * kStable} pointerEvents="none" />
                </g>
              );
            }),
          )}
        </g>
      )}

      {/* Campgrounds */}
      {props.showCampgrounds && (
        <g>
          {props.campgrounds.map((c) => {
            const [x, y] = project(c.lon, c.lat);
            const screenR = c.total_sites != null
              ? Math.min(7, 3.5 + c.total_sites / 50)
              : 3.5;
            return (
              <g
                key={c.id}
                transform={`translate(${x} ${y})`}
                style={{ cursor: 'pointer' }}
                onClick={guardClick(() => props.onClickCampground(c.id))}
              >
                <circle r={Math.max(14, screenR + 8) * kStable} fill="transparent" pointerEvents="all" />
                <circle r={screenR * kStable} fill="#7A684B" stroke="#F2EAD8" strokeWidth={1.4 * kStable} opacity={0.95} pointerEvents="none" />
              </g>
            );
          })}
        </g>
      )}

      {/* POIs */}
      {props.showPOIs && (
        <g>
          {props.rivers.flatMap((r) =>
            (r.pois ?? []).map((p) => {
              const [x, y] = project(p.lon, p.lat);
              const tone = POI_TONES[p.type] ?? '#524D43';
              return (
                <g
                  key={p.id}
                  transform={`translate(${x} ${y})`}
                  style={{ cursor: 'pointer' }}
                  onClick={guardClick(() => props.onClickPoi(p.id))}
                >
                  <circle r={14 * kStable} fill="transparent" pointerEvents="all" />
                  <circle r={4.5 * kStable} fill={tone} stroke="#FAF8F4" strokeWidth={1.4 * kStable} pointerEvents="none" />
                </g>
              );
            }),
          )}
        </g>
      )}

      {/* Scale bar + north arrow — anchored to the viewport (screen-fixed) in
          the empty left-centre band so they never collide with the corner
          cards. Bar length tracks a tidy ground distance for the zoom. */}
      {(() => {
        const m = kStable;
        const km = niceDistance(view.w * 0.16 * kmPerUnit);
        const barUnits = km / kmPerUnit;
        const ox = view.x + view.w * 0.04;
        const oy = view.y + view.h * 0.5;
        const tick = 4.5 * m;
        // The bar floats over the dark canvas left of the state at the
        // default framing — parchment ink, not map-ink, or it vanishes.
        const ink = 'rgba(242,234,216,0.6)';
        return (
          <g pointerEvents="none" fontFamily="var(--font-mono), ui-monospace, monospace">
            <g transform={`translate(${ox + barUnits / 2} ${oy - 26 * m})`}>
              <path d={`M0 ${-9 * m} L${5 * m} ${5 * m} L${-5 * m} ${5 * m} Z`} fill={ink} />
              <text x={0} y={-12 * m} textAnchor="middle" fontSize={9 * m} fontWeight={700} fill={ink}>N</text>
            </g>
            <line x1={ox} y1={oy} x2={ox + barUnits} y2={oy} stroke={ink} strokeWidth={1.6 * m} strokeLinecap="round" />
            <line x1={ox} y1={oy - tick} x2={ox} y2={oy + tick} stroke={ink} strokeWidth={1.6 * m} />
            <line x1={ox + barUnits} y1={oy - tick} x2={ox + barUnits} y2={oy + tick} stroke={ink} strokeWidth={1.6 * m} />
            <text x={ox + barUnits / 2} y={oy - 5 * m} textAnchor="middle" fontSize={9 * m} fill={ink}>
              {km} km · {Math.round(km * 0.621371)} mi
            </text>
          </g>
        );
      })()}
    </svg>

    {/* Animated flow — comet particles on the curated rivers, above the
        river strokes but below the gauge markers (next SVG). Pointer
        events pass straight through. Mounted during the entry flight too:
        the canvas re-derives its viewBox transform from viewRef every
        frame, so particles ride the descending camera — the rivers are
        already breathing when the state settles into place. The fade
        matches the curated river strokes' reveal. */}
    {props.showFlow !== false && !reducedMotion && (
      <FlowLayer
        rivers={flowRivers}
        viewRef={viewRef}
        enabled={!props.flowPaused}
        maxParticles={maxParticles}
        pauseRef={gestureRef}
        style={fadeIn(950)}
      />
    )}

    {/* Marker overlay — gauges stay crisp above the particle stream.
        The SVG itself is transparent to the pointer; each marker opts
        back in, and its events bubble to the stage div for pan/zoom. */}
    <svg
      ref={markerSvgRef}
      preserveAspectRatio="xMidYMid meet"
      className="absolute"
      style={{ ...CAMERA_SVG_STYLE, pointerEvents: 'none' }}
    >
      {/* Gauges. Radii multiplied by kStable so the dot stays the same
          *screen* size at any zoom — at the state-wide view it doesn't
          dwarf the rivers, and zoomed in it doesn't balloon.
          Each marker has an invisible 14px screen hit-target as the
          first child so clicks register reliably even when the visible
          dot is only a few pixels across. (Memoized above — gaugeLayer.) */}
      {gaugeLayer}
    </svg>
    </div>

    {/* Title — screen-space overlay (not inside the pan/zoom SVG), so it
        stays pinned at the top and never clips as the map fills the stage or
        the user zooms. Desktop only: on phones the dock masthead + FAB
        already brand it, and the header row is tight. */}
    <div
      className="pointer-events-none absolute inset-x-0 top-2 z-10 hidden text-center md:block"
      style={{
        fontFamily: 'var(--font-mono), ui-monospace, monospace',
        fontSize: 13,
        letterSpacing: '0.45em',
        color: 'rgba(242,234,216,0.4)',
        fontWeight: 500,
      }}
    >
      MISSOURI &amp; ARKANSAS · LIVE RIVER NETWORK
    </div>

    {/* The color key and source attribution used to live here as two floating
        mono footer lines, but they duplicated the dock's legend ("color is the
        float verdict at the nearest gauge" + the statewide-sites note) and the
        NHD/NWIS provenance is plumbing, not something a floater needs to read.
        Dropped to keep the map canvas clean. */}

    {/* Zoom controls — overlay, not inside the SVG, so they stay fixed in
        screen coordinates regardless of the current view. Slides out of
        the way when the right rail is pinned (it used to hide beneath it);
        on phones the sheet owns the bottom of the screen, so the cluster
        fades out entirely instead of poking out half-buried behind it. */}
    <div
      className={`absolute top-1/2 -translate-y-1/2 flex flex-col gap-1 z-10 transition-[right,opacity] duration-300 right-4 ${
        props.railOpen ? 'md:right-[min(384px,calc(100vw-52px))] max-md:pointer-events-none max-md:opacity-0' : ''
      }`}
      style={{ fontFamily: 'var(--font-mono), ui-monospace, monospace' }}
    >
      <button
        type="button"
        aria-label="Zoom in"
        onClick={() => zoomBy(0.65)}
        className="w-9 h-9 grid place-items-center rounded-md border-2 select-none"
        style={{
          background: '#FAF8F4', color: '#2D2A24', borderColor: '#3F3B33',
          fontSize: 18, fontWeight: 700, lineHeight: 1,
          boxShadow: '2px 2px 0 #1A1814',
        }}
      >+</button>
      <button
        type="button"
        aria-label="Zoom out"
        onClick={() => zoomBy(1 / 0.65)}
        className="w-9 h-9 grid place-items-center rounded-md border-2 select-none"
        style={{
          background: '#FAF8F4', color: '#2D2A24', borderColor: '#3F3B33',
          fontSize: 22, fontWeight: 700, lineHeight: 1,
          boxShadow: '2px 2px 0 #1A1814',
        }}
      >−</button>
      <button
        type="button"
        aria-label="Reset view"
        onClick={resetView}
        disabled={!zoomedIn}
        className="w-9 h-9 grid place-items-center rounded-md border-2 select-none"
        style={{
          background: zoomedIn ? '#FAF8F4' : '#E8E2D5',
          color: zoomedIn ? '#2D2A24' : '#857D70',
          borderColor: '#3F3B33',
          fontSize: 9.5, fontWeight: 700, letterSpacing: '0', lineHeight: 1,
          boxShadow: zoomedIn ? '2px 2px 0 #1A1814' : 'none',
          cursor: zoomedIn ? 'pointer' : 'default',
        }}
        title="Reset view (or double-click the map)"
      >RESET</button>
    </div>
  </>
  );
}
