'use client';

// Pure SVG implementation of the Missouri Surface Water map.
//
// We deliberately do NOT use MapLibre / vector tiles / glyph PBFs / sprites
// here. Real Supabase geometry is projected from WGS84 into a 1600x1000 SVG
// viewBox via a simple Albers-like equal-area projection centered on
// Missouri. This sidesteps the entire CSP/glyph/style-validation surface
// MapLibre brings, and matches the Claude Design reference visually.
//
// Particles ride along the rendered <path> elements using
// getTotalLength() + getPointAtLength(), the same trick the design uses.

import { useEffect, useRef, useMemo } from 'react';
import {
  PERCENTILE_CLASSES,
  STAGE_VERDICTS,
  classifyPercentile,
  type MORiver,
  type MOCampground,
  type StageVerdict,
} from '@/lib/usgs/mo-statewide-data';
import type { MoStatewideGauge } from '@/app/api/usgs/mo-statewide/route';
import moOutline from '@/data/mo-outline.json';
import moBasemap from '@/data/mo-rivers-basemap.json';

type BasemapRiver = {
  type: 'Feature';
  properties: { name: string; length_mi: number };
  geometry: { type: 'LineString'; coordinates: number[][] };
};
type BasemapLake = {
  type: 'Feature';
  properties: { name: string; area_sqkm: number };
  geometry: { type: 'Polygon' | 'MultiPolygon'; coordinates: number[][][] | number[][][][] };
};
const BASEMAP_RIVERS = (moBasemap.rivers?.features ?? []) as BasemapRiver[];
const BASEMAP_LAKES = (moBasemap.lakes?.features ?? []) as BasemapLake[];

// ─── Projection ─────────────────────────────────────────────────────────
//
// The viewBox is fixed at 1600×1000 but the projection window is computed
// at runtime from the bounding box of the actual data (rivers + gauges +
// campgrounds), so the canvas auto-frames to wherever the data actually
// lives. The state silhouette renders in the same projection and is
// allowed to overflow the viewBox; it gets clipped naturally by SVG.

const W = 1600;
const H = 1000;
const PADDING = 60;

type Projector = (lon: number, lat: number) => [number, number];

function buildProjector(bbox: {
  minLon: number;
  maxLon: number;
  minLat: number;
  maxLat: number;
}): Projector {
  const lonSpan = bbox.maxLon - bbox.minLon || 0.001;
  const latSpan = bbox.maxLat - bbox.minLat || 0.001;
  const centerLon = (bbox.minLon + bbox.maxLon) / 2;
  const centerLat = (bbox.minLat + bbox.maxLat) / 2;
  const cosLat = Math.cos((centerLat * Math.PI) / 180);

  const innerW = W - 2 * PADDING;
  const innerH = H - 2 * PADDING;
  const scaleByLon = innerW / lonSpan;
  const scaleByLat = innerH / (latSpan / cosLat);
  const scale = Math.min(scaleByLon, scaleByLat);

  return (lon, lat) => {
    const x = (lon - centerLon) * scale + W / 2;
    const y = -(lat - centerLat) * (scale / cosLat) + H / 2;
    return [x, y];
  };
}

function lineToPath(coords: Array<[number, number]>, project: Projector): string {
  if (!coords.length) return '';
  return coords
    .map(([lon, lat], i) => {
      const [x, y] = project(lon, lat);
      return `${i === 0 ? 'M' : 'L'}${x.toFixed(1)} ${y.toFixed(1)}`;
    })
    .join(' ');
}

function polygonToPath(coords: Array<[number, number]>, project: Projector): string {
  return lineToPath(coords, project) + ' Z';
}

// ─── Static geometry ────────────────────────────────────────────────────

// Real TIGER/Line state boundary, simplified to ~150 vertices via Douglas-
// Peucker. Generated by `scripts/build-mo-outline.ts` from the topojson/
// us-atlas states-10m artifact (Census Cartographic Boundary cb_2023).
const MO_OUTLINE: Array<[number, number]> = (moOutline.coordinates[0] as Array<
  [number, number]
>);

const CITIES: Array<{ name: string; lon: number; lat: number; type: 'metro' | 'city' }> = [
  { name: 'Kansas City',   lon: -94.578, lat: 39.099, type: 'metro' },
  { name: 'St. Louis',     lon: -90.199, lat: 38.627, type: 'metro' },
  { name: 'Springfield',   lon: -93.298, lat: 37.209, type: 'metro' },
  { name: 'Columbia',      lon: -92.334, lat: 38.952, type: 'metro' },
  { name: 'Jefferson City',lon: -92.173, lat: 38.577, type: 'city'  },
  { name: 'Cape Girardeau',lon: -89.518, lat: 37.306, type: 'city'  },
  { name: 'Joplin',        lon: -94.513, lat: 37.084, type: 'city'  },
];

// ─── Component ──────────────────────────────────────────────────────────

interface MOMapProps {
  rivers: MORiver[];
  campgrounds: MOCampground[];
  gauges: MoStatewideGauge[];
  verdictByRiver: Record<string, StageVerdict>;
  percentileByRiver: Record<string, number | null>;
  percentileByGauge: Record<string, number | null>;
  hoveredRiverId: string | null;
  focusedRiverId: string | null;
  hoveredGaugeId: string | null;
  focusedGaugeId: string | null;
  showCampgrounds: boolean;
  showAccessPoints: boolean;
  showPOIs: boolean;
  onHoverRiver: (id: string | null) => void;
  onFocusRiver: (id: string | null) => void;
  onHoverGauge: (id: string | null) => void;
  onFocusGauge: (id: string | null) => void;
  onClickCampground: (id: string | null) => void;
  onClickAccessPoint: (id: string | null) => void;
  onClickPoi: (id: string | null) => void;
}

const POI_TONES: Record<string, string> = {
  spring: '#1D525F',
  cave: '#3D3425',
  historical_site: '#7A684B',
  scenic_viewpoint: '#347A47',
  waterfall: '#256574',
  geological: '#5C4E38',
  other: '#524D43',
};

function colorForPercentile(p: number | null | undefined): string {
  if (p == null || isNaN(p)) return '#857D70';
  return classifyPercentile(p).color;
}

function strokeWidthForRiver(
  lengthMiles: number | null | undefined,
  hovered: boolean,
  focused: boolean,
): number {
  // Curated rivers sit on top of the basemap network; keep them visible but
  // not so heavy they read as the only rivers in the state.
  const m = lengthMiles ?? 60;
  const base = Math.max(2.6, Math.min(4.8, 2.2 + m / 60));
  if (focused) return base + 2.4;
  if (hovered) return base + 1.4;
  return base;
}

function strokeWidthForBasemapRiver(lengthMi: number): number {
  // Thin, length-weighted strokes for the NHD basemap network. Mainstems
  // (Mississippi, Missouri, Osage) render heaviest; small named tributaries
  // taper to a hairline.
  if (lengthMi >= 200) return 1.6;
  if (lengthMi >= 100) return 1.2;
  if (lengthMi >= 50) return 0.95;
  return 0.7;
}

export default function MOMap(props: MOMapProps) {
  // Lock the projection window to the full Missouri state outline so the
  // map always reads as "Missouri", no matter what data subset is loaded.
  // Earlier we framed to the data bbox, which caused the southern half of
  // the state to fill the canvas and the visual to drift as data changed.
  const bbox = useMemo(() => {
    let minLon = Infinity, maxLon = -Infinity;
    let minLat = Infinity, maxLat = -Infinity;
    for (const [lon, lat] of MO_OUTLINE) {
      if (lon < minLon) minLon = lon;
      if (lon > maxLon) maxLon = lon;
      if (lat < minLat) minLat = lat;
      if (lat > maxLat) maxLat = lat;
    }
    // Tight padding — the state outline already has visual breathing room.
    const lonPad = (maxLon - minLon) * 0.02;
    const latPad = (maxLat - minLat) * 0.02;
    return {
      minLon: minLon - lonPad,
      maxLon: maxLon + lonPad,
      minLat: minLat - latPad,
      maxLat: maxLat + latPad,
    };
  }, []);

  const project = useMemo(() => buildProjector(bbox), [bbox]);

  const stateOutlinePath = useMemo(
    () => polygonToPath(MO_OUTLINE, project),
    [project],
  );
  const riverPaths = useMemo(() => {
    const out: Record<string, string> = {};
    for (const r of props.rivers) {
      out[r.id] = lineToPath(r.geometry.coordinates as Array<[number, number]>, project);
    }
    return out;
  }, [props.rivers, project]);

  // Basemap rivers — pre-projected once per `project` change, sorted by
  // length so longer rivers paint underneath shorter ones (so the smaller
  // tributaries don't get covered up).
  const basemapRiverPaths = useMemo(() => {
    return BASEMAP_RIVERS
      .map((f) => ({
        name: f.properties.name,
        lengthMi: f.properties.length_mi,
        d: lineToPath(f.geometry.coordinates as Array<[number, number]>, project),
      }))
      .filter((r) => r.d.length > 0)
      .sort((a, b) => b.lengthMi - a.lengthMi);
  }, [project]);

  // Basemap lakes — flatten Polygon and MultiPolygon outer rings into
  // individual SVG path strings. Holes (inner rings) are ignored at this
  // simplification level; reservoir holes don't render meaningfully here.
  const basemapLakePaths = useMemo(() => {
    const out: Array<{ name: string; d: string }> = [];
    for (const f of BASEMAP_LAKES) {
      const rings: Array<Array<[number, number]>> = [];
      if (f.geometry.type === 'Polygon') {
        const outer = (f.geometry.coordinates as number[][][])[0];
        if (outer) rings.push(outer as Array<[number, number]>);
      } else {
        for (const poly of f.geometry.coordinates as number[][][][]) {
          if (poly[0]) rings.push(poly[0] as Array<[number, number]>);
        }
      }
      const d = rings.map((r) => polygonToPath(r, project)).join(' ');
      if (d) out.push({ name: f.properties.name, d });
    }
    return out;
  }, [project]);

  // Cities visible in the framed area (plus a small buffer outside, so the
  // nearest metro still anchors the user's orientation).
  const visibleCities = useMemo(() => {
    const lonBuf = (bbox.maxLon - bbox.minLon) * 0.18;
    const latBuf = (bbox.maxLat - bbox.minLat) * 0.18;
    return CITIES.filter(
      (c) =>
        c.lon >= bbox.minLon - lonBuf &&
        c.lon <= bbox.maxLon + lonBuf &&
        c.lat >= bbox.minLat - latBuf &&
        c.lat <= bbox.maxLat + latBuf,
    );
  }, [bbox]);

  // ─── Particles ─────────────────────────────────────────────────────────
  // For each river that's "active" (mean percentile ≥ 60 or hovered/focused
  // or floatable+prime/pushy), seed N particles. On every frame walk each
  // particle's t, sample the rendered <path>'s point, and render as small
  // <circle>s. The DOM <path> elements have stable ids so we can grab them.
  const particlesContainerRef = useRef<SVGGElement | null>(null);
  const rafRef = useRef<number>(0);

  useEffect(() => {
    type P = { riverId: string; t: number; speed: number };
    const particles: P[] = [];
    for (const r of props.rivers) {
      const p = props.percentileByRiver[r.slug] ?? 50;
      const verdict = props.verdictByRiver[r.slug];
      const isActive =
        p >= 60 ||
        props.hoveredRiverId === r.id ||
        props.focusedRiverId === r.id ||
        verdict === 'prime' ||
        verdict === 'pushy';
      if (!isActive) continue;
      const n = p < 25 ? 2 : p < 75 ? 4 : 7;
      for (let i = 0; i < n; i++) {
        particles.push({
          riverId: r.id,
          t: i / n + Math.random() * 0.04,
          speed: 0.04 + (p / 100) * 0.08 + Math.random() * 0.02,
        });
      }
    }

    let last = performance.now();
    const draw = () => {
      const now = performance.now();
      const dt = Math.min(0.1, (now - last) / 1000);
      last = now;

      const g = particlesContainerRef.current;
      if (!g) {
        rafRef.current = requestAnimationFrame(draw);
        return;
      }

      // Clear and redraw all particles.
      while (g.firstChild) g.removeChild(g.firstChild);

      for (const p of particles) {
        p.t += p.speed * dt;
        if (p.t > 1) p.t -= 1;

        const path = document.getElementById(
          `mo-river-path-${p.riverId}`,
        ) as SVGPathElement | null;
        if (!path) continue;

        const len = path.getTotalLength();
        if (!len) continue;
        const pt = path.getPointAtLength(p.t * len);

        const verdict = props.verdictByRiver[
          props.rivers.find((r) => r.id === p.riverId)?.slug ?? ''
        ];
        const tone =
          verdict === 'prime'  ? STAGE_VERDICTS.prime.inner :
          verdict === 'pushy'  ? STAGE_VERDICTS.pushy.inner :
          verdict === 'hazard' ? STAGE_VERDICTS.hazard.inner :
          verdict === 'bony'   ? STAGE_VERDICTS.bony.inner :
          '#F2EAD8';

        const c1 = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        c1.setAttribute('cx', `${pt.x}`);
        c1.setAttribute('cy', `${pt.y}`);
        c1.setAttribute('r', '4');
        c1.setAttribute('fill', tone);
        c1.setAttribute('opacity', '0.55');
        g.appendChild(c1);

        const c2 = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        c2.setAttribute('cx', `${pt.x}`);
        c2.setAttribute('cy', `${pt.y}`);
        c2.setAttribute('r', '1.6');
        c2.setAttribute('fill', '#FAF8F4');
        g.appendChild(c2);
      }

      rafRef.current = requestAnimationFrame(draw);
    };
    rafRef.current = requestAnimationFrame(draw);
    return () => cancelAnimationFrame(rafRef.current);
  }, [
    props.rivers,
    props.percentileByRiver,
    props.verdictByRiver,
    props.hoveredRiverId,
    props.focusedRiverId,
  ]);

  // Sort rivers so lower-order paint underneath higher-order, and the
  // hovered/focused one always renders last (on top).
  const orderedRivers = useMemo(() => {
    return [...props.rivers].sort((a, b) => {
      const aTop = a.id === props.hoveredRiverId || a.id === props.focusedRiverId;
      const bTop = b.id === props.hoveredRiverId || b.id === props.focusedRiverId;
      if (aTop && !bTop) return 1;
      if (bTop && !aTop) return -1;
      return (a.length_miles ?? 0) - (b.length_miles ?? 0);
    });
  }, [props.rivers, props.hoveredRiverId, props.focusedRiverId]);

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      preserveAspectRatio="xMidYMid meet"
      className="absolute inset-0 h-full w-full"
      onClick={(e) => {
        // Empty-area click clears focus.
        if (e.target === e.currentTarget) {
          props.onFocusRiver(null);
          props.onFocusGauge(null);
          props.onClickCampground(null);
          props.onClickAccessPoint(null);
          props.onClickPoi(null);
        }
      }}
    >
      <defs>
        <radialGradient id="mo-bg" cx="50%" cy="50%" r="85%">
          <stop offset="0%" stopColor="#F4ECDB" />
          <stop offset="60%" stopColor="#EADFC2" />
          <stop offset="100%" stopColor="#D4C394" />
        </radialGradient>
        <pattern id="mo-grain" width="180" height="180" patternUnits="userSpaceOnUse">
          {Array.from({ length: 70 }).map((_, i) => {
            const seed = (i * 9301 + 49297) % 233280;
            const x = seed % 180;
            const y = ((seed / 180) | 0) % 180;
            const r = ((seed % 7) / 10) + 0.3;
            return <circle key={i} cx={x} cy={y} r={r} fill="rgba(105,80,40,0.07)" />;
          })}
        </pattern>
        {/* Clip path so the parchment fill respects MO's borders even when
            the silhouette overflows the viewBox. */}
        <clipPath id="mo-clip">
          <path d={stateOutlinePath} />
        </clipPath>
      </defs>

      {/* Backdrop (matches Eddy primary-900) */}
      <rect width={W} height={H} fill="#0F2D35" />

      {/* State silhouette — parchment fill, clipped to state, plus a stroked
          border for definition. The state path may extend off-canvas; SVG
          clips it naturally. */}
      <g clipPath="url(#mo-clip)">
        <rect width={W} height={H} fill="url(#mo-bg)" />
        <rect width={W} height={H} fill="url(#mo-grain)" />

        {/* NHD basemap — lakes (filled polygons) under named perennial
            rivers (thin uniform blue). Renders inside the state clip so it
            never bleeds across MO's borders. Curated rivers, gauges, etc.
            paint OUTSIDE this group on top of the basemap. */}
        <g pointerEvents="none">
          {basemapLakePaths.map((l) => (
            <path
              key={`lake-${l.name}`}
              d={l.d}
              fill="#7FB2C2"
              stroke="#3F8499"
              strokeWidth={0.6}
              opacity={0.78}
            />
          ))}
          {basemapRiverPaths.map((r) => (
            <path
              key={`bm-${r.name}`}
              d={r.d}
              stroke="#3F8499"
              strokeWidth={strokeWidthForBasemapRiver(r.lengthMi)}
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
              opacity={0.85}
            />
          ))}
        </g>
      </g>
      <path
        d={stateOutlinePath}
        fill="none"
        stroke="rgba(80,60,30,0.65)"
        strokeWidth={2.2}
        strokeLinejoin="round"
      />

      {/* Title */}
      <text
        x={W / 2}
        y={48}
        textAnchor="middle"
        fontFamily="var(--font-mono), ui-monospace, monospace"
        fontSize={13}
        letterSpacing="0.45em"
        fill="rgba(80,60,30,0.5)"
        fontWeight={500}
      >
        STATE OF MISSOURI · SURFACE WATER NETWORK
      </text>

      {/* Cities */}
      <g>
        {visibleCities.map((c) => {
          const [cx, cy] = project(c.lon, c.lat);
          return (
            <g key={c.name} transform={`translate(${cx} ${cy})`}>
              <circle
                r={c.type === 'metro' ? 5 : 3.5}
                fill="rgba(45,42,36,0.78)"
                stroke="rgba(247,246,243,0.9)"
                strokeWidth={1.5}
              />
              <text
                x={c.type === 'metro' ? 10 : 8}
                y={5}
                fontFamily="var(--font-mono), ui-monospace, monospace"
                fontSize={c.type === 'metro' ? 13 : 11}
                fontWeight={c.type === 'metro' ? 700 : 500}
                fill="rgba(45,42,36,0.85)"
                paintOrder="stroke"
                stroke="rgba(242,234,216,0.92)"
                strokeWidth={3}
                strokeLinejoin="round"
              >
                {c.name}
              </text>
            </g>
          );
        })}
      </g>

      {/* Rivers — outer "casing" + main stroke + verdict inner stroke */}
      {orderedRivers.map((r) => {
        const d = riverPaths[r.id];
        if (!d) return null;
        const slug = r.slug;
        const percentile = props.percentileByRiver[slug];
        const verdict = props.verdictByRiver[slug];
        const color = colorForPercentile(percentile);
        const isHovered = props.hoveredRiverId === r.id;
        const isFocused = props.focusedRiverId === r.id;
        const sw = strokeWidthForRiver(r.length_miles, isHovered, isFocused);
        const verdictTone =
          verdict === 'prime'  ? STAGE_VERDICTS.prime.inner :
          verdict === 'pushy'  ? STAGE_VERDICTS.pushy.inner :
          verdict === 'hazard' ? STAGE_VERDICTS.hazard.inner :
          verdict === 'bony'   ? STAGE_VERDICTS.bony.inner :
          'transparent';
        const dim =
          (props.focusedRiverId && !isFocused) ||
          (props.hoveredRiverId && !isHovered && !isFocused);

        return (
          <g
            key={r.id}
            style={{ opacity: dim ? 0.32 : 1, transition: 'opacity 200ms', cursor: 'pointer' }}
            onMouseEnter={() => props.onHoverRiver(r.id)}
            onMouseLeave={() => props.onHoverRiver(null)}
            onClick={(e) => {
              e.stopPropagation();
              props.onFocusRiver(r.id);
            }}
          >
            {/* Hit target */}
            <path d={d} stroke="transparent" strokeWidth={Math.max(18, sw * 3)} fill="none" strokeLinecap="round" />
            {/* Glow */}
            {(isHovered || isFocused) && (
              <path
                d={d}
                stroke={color}
                strokeWidth={sw + 7}
                fill="none"
                strokeLinecap="round"
                opacity={0.35}
                style={{ filter: `drop-shadow(0 0 6px ${color})` }}
              />
            )}
            {/* Main stroke */}
            <path
              id={`mo-river-path-${r.id}`}
              d={d}
              stroke={color}
              strokeWidth={sw}
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            {/* Verdict inner stroke */}
            {verdict !== 'unknown' && verdictTone !== 'transparent' && (
              <path
                d={d}
                stroke={verdictTone}
                strokeWidth={Math.max(1.2, sw * 0.42)}
                fill="none"
                strokeLinecap="round"
                strokeDasharray={verdict === 'hazard' ? '4 3' : undefined}
                opacity={isHovered || isFocused ? 1 : 0.92}
              />
            )}
          </g>
        );
      })}

      {/* Particles (continuously redrawn by the RAF effect above) */}
      <g ref={particlesContainerRef} pointerEvents="none" />

      {/* Gauges */}
      <g>
        {props.gauges.map((g) => {
          const r = props.rivers.find((x) => x.id === g.river_id);
          const gauge = r?.gauges?.find((x) => x.site_id === g.site_no);
          if (!gauge) return null;
          const [x, y] = project(gauge.lon, gauge.lat);
          const p = props.percentileByGauge[g.site_no] ?? g.percentile;
          const color = colorForPercentile(p);
          const isPeak = p != null && p >= 75;
          const isHovered = props.hoveredGaugeId === g.site_no;
          const isFocused = props.focusedGaugeId === g.site_no;
          return (
            <g
              key={g.site_no}
              transform={`translate(${x} ${y})`}
              style={{ cursor: 'pointer' }}
              onMouseEnter={() => props.onHoverGauge(g.site_no)}
              onMouseLeave={() => props.onHoverGauge(null)}
              onClick={(e) => {
                e.stopPropagation();
                props.onFocusGauge(g.site_no);
              }}
            >
              {isPeak && (
                <circle r={5} fill="none" stroke={color} strokeWidth={1.2} opacity={0.7}>
                  <animate attributeName="r" from="5" to="14" dur="2.2s" repeatCount="indefinite" />
                  <animate attributeName="opacity" from="0.7" to="0" dur="2.2s" repeatCount="indefinite" />
                </circle>
              )}
              <circle
                r={isFocused ? 8 : isHovered ? 7 : g.is_primary ? 6 : 4}
                fill="#FAF8F4"
                stroke={color}
                strokeWidth={g.is_primary ? 2.5 : 1.8}
              />
              {(isHovered || isFocused) && <circle r={1.8} fill={color} />}
            </g>
          );
        })}
      </g>

      {/* Access points */}
      {props.showAccessPoints && (
        <g>
          {props.rivers.flatMap((r) =>
            (r.access_points ?? []).map((a) => {
              const [x, y] = project(a.lon, a.lat);
              return (
                <g
                  key={a.id}
                  transform={`translate(${x} ${y})`}
                  style={{ cursor: 'pointer' }}
                  onClick={(e) => {
                    e.stopPropagation();
                    props.onClickAccessPoint(a.id);
                  }}
                >
                  <circle r={4} fill="#4EB86B" stroke="#F2EAD8" strokeWidth={1.5} />
                </g>
              );
            }),
          )}
        </g>
      )}

      {/* Campgrounds */}
      {props.showCampgrounds && (
        <g>
          {props.campgrounds.map((c) => {
            const [x, y] = project(c.lon, c.lat);
            const r = c.total_sites != null ? Math.min(10, 4 + c.total_sites / 25) : 4;
            return (
              <g
                key={c.id}
                transform={`translate(${x} ${y})`}
                style={{ cursor: 'pointer' }}
                onClick={(e) => {
                  e.stopPropagation();
                  props.onClickCampground(c.id);
                }}
              >
                <circle r={r} fill="#7A684B" stroke="#F2EAD8" strokeWidth={2} opacity={0.95} />
              </g>
            );
          })}
        </g>
      )}

      {/* POIs */}
      {props.showPOIs && (
        <g>
          {props.rivers.flatMap((r) =>
            (r.pois ?? []).map((p) => {
              const [x, y] = project(p.lon, p.lat);
              const tone = POI_TONES[p.type] ?? '#524D43';
              return (
                <g
                  key={p.id}
                  transform={`translate(${x} ${y})`}
                  style={{ cursor: 'pointer' }}
                  onClick={(e) => {
                    e.stopPropagation();
                    props.onClickPoi(p.id);
                  }}
                >
                  <circle r={5.5} fill={tone} stroke="#FAF8F4" strokeWidth={2} />
                </g>
              );
            }),
          )}
        </g>
      )}

      {/* Period of record footer note */}
      <text
        x={W - 14}
        y={H - 14}
        textAnchor="end"
        fontFamily="var(--font-mono), ui-monospace, monospace"
        fontSize={10}
        fill="rgba(80,60,30,0.55)"
      >
        Geometry: USGS NHD via Supabase · Live data: USGS NWIS
      </text>

      {/* Reference key for percentile coloring */}
      <text
        x={14}
        y={H - 14}
        fontFamily="var(--font-mono), ui-monospace, monospace"
        fontSize={9}
        letterSpacing="0.1em"
        fill="rgba(80,60,30,0.55)"
      >
        Stream colour: percentile vs. period of record · {PERCENTILE_CLASSES.length} bands
      </text>
    </svg>
  );
}
